### ISSUE TITLE
[Search] Investigate whether we can get rid of the index::text_layout (single vs collection) 

### ISSUE THREAD

**Issue by smehringer** [seqan/product_backlog#105]
### Description 

The output was unified by seqan/seqan3#1706 (related issue: #28).

The follow-up issue is to investigate whether we can remove the text layout from the index interface and also unify the internal implementation. First evaluations showed that using a single element collection had a performance drop of ~10% compared to the single text implementation. This needs to be re-evaluated once all the changes to the search design and the EPR dictionaries have been made.
Depending on a thorough investigation of the performance, we can plan the next steps.

### Acceptance Criteria

- [ ] Make a decision on whether we drop the differentiation between single text and text collection in the internal index implementation.

### Tasks

- [ ] Add macro benchmarks that test the search interface on a single text and a collection of a single elements.
- [ ] Post the benchmark results here and discuss the results with the core team.
- [ ] Make a decision whether we drop the differentiation between single text and text collection in the internal index implementation.

### Definition of Done

- [ ] Macrobenchmarks added
- [ ] Decision was made
