### ISSUE TITLE
gcc-11 support 

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#106]
### Description 

Bugs:
* [x] gcc-11 support (https://github.com/seqan/seqan3/issues/2030)
* [x] [FIX] gcc-11: error: incomplete type ‘std::numeric_limits<char>’ (https://github.com/seqan/seqan3/issues/2196)

Reported ICEs/Compiler Bugs:
* [x] [11 Regression] ICE: concepts with a fully known / complete type in requires (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95497) (thank you @eseiler for reducing)
* [x] [11 Regression] ICE: in output_constructor_regular_field, at varasm.c:5223 (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96863)
* [x] [11 Regression] ICE: Segmentation fault (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96872)
* [x] [11 Regression][concepts] Not working with explicit types in function signatures? (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=97704)
  * This is bad, because of http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#2369 :(( 
* [x] [10/11 Regression] -Wdeprecated-declarations where non-should be? (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99318)
* [x] [11 Regression] custom friend pipe-operator| conflicts with range adaptor? (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99433)
* [ ] constexpr defined arrays within constexpr functions would benefit from lookup-tables (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99320)
* [ ] std::views::{take, drop} don't type erase (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100139)
* [x] __cpp_lib_to_chars not defined (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100146)
* [ ] [11 Regression] error: invalid use of non-static data member (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100205)
* [ ] [10/11/12] std::views::elements only accepts types that are defined on std::get (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100233)

### Acceptance Criteria

- [ ] test 1
- [ ] test 2
- [ ] test 3

### Tasks

 

- [ ] task 1
- [ ] task 2
- [ ] task 3

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by eseiler** [comment]
GCC 11.1 has been released 
https://gcc.gnu.org/gcc-11/

**Comment by marehr** [comment]
After a lot of work, we finally got gcc-11 to work.

See our dashboard http://cdash.seqan.de/index.php?project=SeqAn3.

We added gcc-11 to the CI (https://github.com/seqan/product_backlog/issues/106), too.

I'm closing this for now :)
