### ISSUE TITLE
doxygen 1.8.19 support

### ISSUE THREAD

**Issue by eseiler** [seqan/product_backlog#107]
### Reported bugs

* [X] [\todo ignores EXCLUDE_SYMBOLS](https://github.com/doxygen/doxygen/issues/7738)
* [X] [Empty string in PREDEFINED throws](https://github.com/doxygen/doxygen/issues/7833)
* [x] [Macro expansion broken](https://github.com/doxygen/doxygen/issues/7890)

### Fixed issues

* [x] [undocumented macro](https://github.com/seqan/seqan3/pull/1955)

### Tasks

 

- Monitor the [nightly documentation builds](https://cdash.seqan.de/index.php?project=SeqAn3#!#documentation). These are build with the master branch of doxygen.
- If there is an error, investigate it and either report it upstream or adjust our documentation.

### Definition of Done

- [x] doxygen 1.8.19 is released and works with our documentation.
