### ISSUE TITLE
Add seqan3::simd::simd_traits<simd_t>::rebind

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#108]
### Description 

We already have

```c++
using int32x_t = seqan3::simd_type_t<int>;
 // same as int32x_t{} == int32x_t{};
typename seqan3::simd_traits<int32x_t>::mask_type;
 // same as seqan3::simd_type_t<uint8_t>;
typename seqan3::simd_traits<int32x_t>::swizzle_type;
```

We should add a

```c++
//  same length, same max_length, but with new scalar_t;
// gives nice compiler error if new scalar t has not same bit size as 
typename simd_traits<int32x_t>::rebind<new_scalar_t>
```

---

```c++
typename simd_traits<int32x_t>::rebind<unsigned> // unsigned simd type
typename simd_traits<int32x_t>::rebind<float> // float simd type (if float == 32bit)
```

Original Idea: https://github.com/seqan/seqan3/pull/1819#discussion_r432830539

### Acceptance Criteria

- [ ] The bit size of the rebind type must be the same as the original data type, otherwise the compiler emits an error.

### Tasks

 

- [ ] add the rebind function to the simd_traits.
- [ ] constraint the rebind type to have the same byte size as the original scalar type of the simd vector.
- [ ] add tests for the rebind variants including floating point rebind to integral type.

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Changelog entry added
