### ISSUE TITLE
[Alignment] Vectorised alignment: banded score

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#114]
Add support for the vectorised banded alignment computing score only.

### Tasks

- [ ] Add test for banded global affine alignment
- [ ] Test sequences with same length
- [ ] Test sequences with different length
- [ ] Check that if band does not cover last cell of one matrix that only that matrix has not a valid value (we need the option to not throw in the end).
- [ ] Enable the feature in the alignment module
- [ ] Make micro benchmark
