### ISSUE TITLE
Adapt the accessor interfaces for the search result.

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#119]
### Description 

The search result interface changes it's return type based on the configuration and denotes this with seqan3::detail::empty_type. This is not a public API type and based on the documentation the user does not know that the type might be not what it is promised. 

### Acceptance Criteria

- [x] Calling the search result on a non-configured type causes a static assert instead of a runtime error.
- [x] We can then use the `seqan3::detail::empty_type` internally.

### Tasks

 

- [x] Make the return type of the accessor functions `auto`
- [x] Document that calling an accessor for an element that was not configured before the behaviour is undefined.
- [x] Replace the runtime error with a static assert.

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] API documentation updated
- [ ] Tutorial/teaching material updated
- [ ] Changelog entry updated
