### ISSUE TITLE
[Alignment] vectroised alignment: enable protein profile score

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#121]
### Description

When computing the simd alignment we can use a profile score to efficiently lookup the score of the alignment score matrix.

### Acceptance criteria

- [ ] Allow a simd profile score to efficiently retrieve the scores from the scoring scheme.

### Tasks

- [ ] which use cases can allow profile score
- [ ] how to implement profile score for different architectures
- [ ] apply profile score in alignment computation
