### ISSUE TITLE
List of snippets to compare against python

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#122]
### Description 

Check some code examples in C++ vs. biopython and maybe other libraries such that we can compare the performances.

### Acceptance Criteria

- [ ] generate for an ambiguous sequence (IUPAC) the neighborhood in dna4: https://stackoverflow.com/questions/27551921/how-to-extend-ambiguous-dna-sequence

### Tasks

 

- [ ] implement the snippets in c++ and the repeat the benchmark

### Definition of Done

- [ ] Implementation and design approved
- [ ] Tutorial/teaching material updated?
