### ISSUE TITLE
[Design] Disabling ADL within SeqAn3

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#123]
### Description 

As library implementer we often deal with generic type. If we write a generic free function and call this unqualified then ADL will lookup all associtated namespaces from the passed arguments for a potential overload. This potentially increases the compile time and even worse could lead to compile errors if there are ambigious overloads or maybe a more generic specialisation of the same free function in another namespace. To avoid this one could disable ADL over some complex mechanisms. We so far decided to disable it by applying the following rule (resolution from 10.06.2020):

Possibilities:

* we qualify everything and no named hidden friends (no operators)?
* all free functions are implemented as function objects or if looking for other namespaces is necessary implemented as CPOs
* For operators we have the same problem, but it is very unlikely since it is a very standard behavior of the language.

    in general, due to ADL calling free functions unqualified can always produce very unexpected results. So calling free functions inside of the seqan3 namespace should be called qualified.

### Resolution (10.06.2020):

    All public member free functions are converted to either a CPO if ADL is required or a function object together with a inline constexpr variable for this function object.
    All detail free functions are implemented as function objects. An inline constexpr variable is not needed.

Problem: https://godbolt.org/z/MXK-En

Solution: https://godbolt.org/z/LyacmH

It follows that within the user code all public free functions need to be called either qualified or by importing the seqan3 namespace which we do not recommend in our tutorials and snippets.

The only question is is there a scenario where this is not wanted/needed/possible? Where we want ADL to kick in, which cannot be resolved via a CPO?

Options:
* Use Function Objects / Lambdas
* Fully-Qualified or use Lambda Functions

Documentation:
* Function Objects / Lambdas must be declared as free-function?

### Acceptance Criteria

- [ ]  all free functions in seqan3 namespace are either a customisation point object (CPO) if ADL is desired or a simple stateless function object (FO) with a dedicated constexpr variable so that it looks like calling a function.
- [ ] all free function in detail namespace are stateless function objects but do not add an explicit variable for it.
- [ ] Do not use hidden friends anywhere in the seqan3 code, except when implementing operators.
 
### Tasks

 

- [ ] make seqan3::get a CPO
- [ ] make align_pairwise a FO
- [ ] make search a FO
- [ ] ...
- [ ] ...
- [ ] Update the documentation accordingly -> using `\fn` to document it as a free function.
- [ ] Add special test template to show that it actually works

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by marehr** [comment]
2020-06-17 Core-Meeting
---

Hannes had not further ideas, he would do it like we said.

Ask the Team how we want this! Prepare a small presentation.

Open Questions
---

For function object, lambda or fully qualified:
* All solve the problem!
* Documentation (delcare \\fn?)
* What would the compiler error look like?

Resolution
----

Detail implementation / vote will dictate how to use it public:
* Use fully qualified or not?
* Use lambda in simple cases / or not?
* Use multi_invocable?
* Use function objects or not?
