### ISSUE TITLE
A Life Without range-v3

### ISSUE THREAD

**Issue by eseiler** [seqan/product_backlog#124]
### Description 

<details><summary>Click me</summary>

#### Stuff to reimplement or to abandon:
* [x] #include <range/v3/utility/semiregular_box.hpp> (https://github.com/seqan/seqan3/pull/2963)
* [ ] #include <range/v3/view/zip.hpp> (https://github.com/seqan/product_backlog/issues/132)
* [ ] #include <range/v3/view/chunk.hpp>
* [ ] #include <range/v3/utility/common_tuple.hpp>
* [ ] #include <range/v3/range/conversion.hpp>
* [ ] #include <range/v3/view/join.hpp> (std::views::join does not have a delimiter option)

#### Concepts library:

> grep -rnw . -e "#include <concepts"

* [x] ./std/concepts:17: (These are okay, because they are needed for our fallback)
  * [x] #include \<concepts>
  * [x] #include <concepts/concepts.hpp>

#### Meta library:

> grep -rnw . -e "#include <meta"

* [x] ./core/algorithm/concept.hpp:18:
  * [x] #include <meta/meta.hpp>
* [x] ./core/algorithm/configuration.hpp:17:
  * [x] #include <meta/meta.hpp>
* [x] ./core/algorithm/configuration_utility.hpp:18:
  * [x] #include <meta/meta.hpp>
* [x] ./core/type_list/type_list.hpp:15:
  * [x] #include <meta/meta.hpp>
* [x] ./core/bit_manipulation.hpp:16:
  * [x] #include <meta/meta.hpp>
* [x] ./io/record.hpp:17:
  * [x] #include <meta/meta.hpp>
* [x] ./alphabet/composite/alphabet_variant.hpp:23:
  * [x] #include <meta/meta.hpp>
* [x] ./alphabet/composite/alphabet_tuple_base.hpp:18:
  * [x] #include <meta/meta.hpp>
* [x] ./alignment/pairwise/align_pairwise.hpp:20:
  * [x] #include <meta/meta.hpp>

(**TODO**: What to do!)

#### Ranges library:

> grep -rnw . -e "#include <range"

* [x] ./core/common_tuple.hpp:15:
  * [ ] #include <range/v3/utility/common_tuple.hpp> (**OPEN - Not sure what to do; Reimplement?**)
* [x] ./std/algorithm:27: (These are okay, because they are needed for our fallback)
  * [x] #include <range/v3/algorithm/all_of.hpp>
  * [x] #include <range/v3/algorithm/copy.hpp>
  * [x] #include <range/v3/algorithm/copy_n.hpp>
  * [x] #include <range/v3/algorithm/equal.hpp>
  * [x] #include <range/v3/algorithm/fill.hpp>
  * [x] #include <range/v3/algorithm/find_if_not.hpp>
  * [x] #include <range/v3/algorithm/find_if.hpp>
  * [x] #include <range/v3/algorithm/find.hpp>
  * [x] #include <range/v3/algorithm/for_each.hpp>
  * [x] #include <range/v3/algorithm/generate.hpp>
  * [x] #include <range/v3/algorithm/min_element.hpp>
  * [x] #include <range/v3/algorithm/max_element.hpp>
  * [x] #include <range/v3/algorithm/move_backward.hpp>
  * [x] #include <range/v3/algorithm/move.hpp>
  * [x] #include <range/v3/algorithm/reverse.hpp>
  * [x] #include <range/v3/algorithm/sort.hpp>
  * [x] #include <range/v3/algorithm/transform.hpp>
* [x] ./std/iterator:38: (These are okay, because they are needed for our fallback)
  * [x] #include <range/v3/iterator/access.hpp>
  * [x] #include <range/v3/iterator/concepts.hpp>
  * [x] #include <range/v3/iterator/default_sentinel.hpp>
  * [x] #include <range/v3/iterator/insert_iterators.hpp>
  * [x] #include <range/v3/iterator/operations.hpp>
  * [x] #include <range/v3/iterator/stream_iterators.hpp>
  * [x] #include <range/v3/iterator/traits.hpp>
* [x] ./std/ranges:23: (These are okay, because they are needed for our fallback)
  * [x] #include <range/v3/range/concepts.hpp>
  * [x] #include <range/v3/range/concepts.hpp>
  * [x] #include <range/v3/iterator/insert_iterators.hpp>
  * [x] #include <range/v3/view/all.hpp>
  * [x] #include <range/v3/view/any_view.hpp>
  * [x] #include <range/v3/view/common.hpp>
  * [x] #include <range/v3/view/drop.hpp>
  * [x] #include <range/v3/view/drop_while.hpp>
  * [x] #include <range/v3/view/filter.hpp>
  * [x] #include <range/v3/view/iota.hpp>
  * [x] #include <range/v3/view/istream.hpp>
  * [x] #include <range/v3/view/join.hpp>
  * [x] #include <range/v3/view/map.hpp>
  * [x] #include <range/v3/view/reverse.hpp>
  * [x] #include <range/v3/view/single.hpp>
  * [x] #include <range/v3/view/split.hpp>
  * [x] #include <range/v3/view/subrange.hpp>
  * [x] #include <range/v3/view/take.hpp>
  * [x] #include <range/v3/view/take_while.hpp>
  * [x] #include <range/v3/view/transform.hpp>
* [x] ./std/concepts:81: (These are okay, because they are needed for our fallback)
  * [x] #include <range/v3/functional/concepts.hpp>
  * [x] #include <range/v3/utility/common_type.hpp>
* [x] ./search/configuration/max_error_rate.hpp:16:
  * [x] #include <range/v3/numeric/accumulate.hpp>
  * (It seems that no rangified version landed in the standard, it seems that the whole `<numeric>` didn't get an update)
* [x] ./search/fm_index/fm_index_cursor.hpp:20:
  * [x] #include <range/v3/view/slice.hpp>
  * (We could use <seqan3/range/views/slice.hpp> instead)
* [ ] ./range/views/join.hpp:15:
  * [ ] #include <range/v3/view/join.hpp>
  * (We assume that the view has a delimiter option, which the `std::views::join` doesn't support)
* [x] ./range/views/repeat.hpp:15:
  * [x] #include <range/v3/view/single.hpp>
  * (We could use <seqan3/std/algorithm> instead)
* [ ] ./range/views/to.hpp:15:
  * [ ] #include <range/v3/range/conversion.hpp>
  * (**OPEN - Not sure what to do**)
* [ ] ./range/views/chunk.hpp:15:
  * [ ] #include <range/v3/view/chunk.hpp>
  * (**OPEN - Not sure what to do**)
* [x] ./range/views/persist.hpp:15:
  * [x] #include <range/v3/algorithm/copy.hpp>
  * (We could use `<seqan3/std/algorithm>` instead)
* [ ] ./range/views/zip.hpp:15:
  * [ ] #include <range/v3/view/zip.hpp>
  * (**OPEN - Not sure what to do; Reimplement?**)
* [ ] ./range/views/interleave.hpp:17:
  * [ ] #include <range/v3/view/chunk.hpp>
  * (**OPEN - Not sure what to do; Reimplement?**)
* [x] ./range/views/take.hpp:15:
  * [x] #include <range/v3/algorithm/copy.hpp>
  * (We could use `<seqan3/std/algorithm>` instead)
* [x] ./io/detail/in_file_iterator.hpp:17:
  * [x] #include <range/v3/range_fwd.hpp>
  * (We could use `<seqan3/std/range>` instead, but I'm not sure why we forward declare, `<seqan3/std/iterator>` might be enough.)
* [x] ./io/detail/out_file_iterator.hpp:17:
  * [x] #include <range/v3/range_fwd.hpp>
  * (We could use `<seqan3/std/range>` instead, but I'm not sure why we forward declare, `<seqan3/std/iterator>` might be enough.)
* [ ] ./io/alignment_file/detail.hpp:29:
  * [ ] #include <range/v3/view/zip.hpp>
  * (**OPEN - Not sure what to do; Reimplement?**)
* [x] ./io/stream/iterator.hpp:20:
  * [x] #include <range/v3/iterator/stream_iterators.hpp>
  * (We could use <seqan3/std/iterator> instead; It seems that we don't even use this.)
* [ ] ./io/sequence_file/format_genbank.hpp:20:
  * [ ] #include <range/v3/view/chunk.hpp>
  * (**OPEN - Not sure what to do; Reimplement?**)
* [x] ./alignment/aligned_sequence/aligned_sequence_concept.hpp:19:
  * [x] #include <range/v3/algorithm/for_each.hpp>
  * (We could use <seqan3/std/algorithm> instead)
* [x] ./alignment/scoring/aminoacid_scoring_scheme.hpp:16:
  * [x] #include <range/v3/algorithm/copy.hpp>
  * (We could use <seqan3/std/algorithm> instead)
* [x] ./alignment/scoring/scoring_scheme_base.hpp:16:
  * [x] #include <range/v3/algorithm/copy.hpp>
  * (We could use <seqan3/std/algorithm> instead)
* [x] ./alignment/pairwise/edit_distance_unbanded.hpp:19:
  * [x] #include <range/v3/algorithm/copy.hpp>
  * (We could use <seqan3/std/algorithm> instead)

</details>

Stuff to reimplement or copy into contrib:
- [x] common_tuple (@eseiler, https://github.com/seqan/seqan3/pull/2971)
- [x] zip (@eseiler, https://github.com/seqan/seqan3/pull/2971)
- [x] join_with (@eseiler, https://github.com/seqan/seqan3/pull/2973)
- [x] chunk (@smehringer, https://github.com/seqan/seqan3/pull/2975)
- [x] to (range/v3/conversion.hpp) seqan/seqan3#2969
- [x] After removing range-v3, remove specifications in `namespace concepts` in `common_tuple` and `common_pair`

Stuff to delete/deprecate and implement with other means (@SGSSGene)
- [x] sliding seqan/seqan3#2967
- [x] semiregular_box seqan/seqan3#2963
- [x] take/single seqan/seqan3#2968
- [x] filter seqan/seqan3#2965
- [x] slice seqan/seqan3#2965
- [x] range_fwd seqan/seqan3#2965

Follow-up: https://github.com/seqan/product_backlog/issues/263

**Comment by marehr** [comment]
I refined the ticket a bit.

**Comment by smehringer** [comment]
#### Core Meeting 07.02.2022

supporting gcc-12 depends on 2 fixes upstream in the ranges-v3 library (see #402 ). Since we want to be independent of the ranges library in the near future anyway, The following could be the in-the-meantime solution: 

We fork the range-v3 library "now" and apply our fixes.
