### ISSUE TITLE
clang-git support

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#127]
Keeps track of all changes for clang10

Bugfixes:

* [x] [FIX] initialise std::type_identity in type_list traits (seqan/seqan3#1557)
* [x] [FIX] clang10: struct / class should be the same in all declarations (seqan/seqan3#1558)
* [x] [FIX] clang: -Wlogical-op-parentheses (seqan/seqan3#2055)
* [x] [FIX] clang: use constexpr version of next_power_of_two (seqan/seqan3#2056)
* [x] [FIX] use feature-testing macro for std::type_identity in type_traits (seqan/seqan3#2057)
* [x] [TEST] simplify overly complicated decltype in single_pass_input_test (seqan/seqan3#2058)

Reported Compiler Bugs:
* [x] <version> header is missing __cpp_lib_type_identity and other macros  (https://bugs.llvm.org/show_bug.cgi?id=47261)
* [x] deleted functions in requires clauses don't SFINAE in concepts (https://bugs.llvm.org/show_bug.cgi?id=44833)
* [x] [trunk] Assertion `!isValueDependent() && "Expression evaluator can't be called on a dependent expression."' failed. (https://github.com/saarraz/clang-concepts-monorepo/issues/54)
* [x] Concept causes infinite loops at compile time (-Wstack-exhausted) (https://bugs.llvm.org/show_bug.cgi?id=44959)
* [x] ICE with concepts (https://bugs.llvm.org/show_bug.cgi?id=47174)
* [x] [concepts] [ice] substitution into constraint expression resulted in a non-constant expression (https://bugs.llvm.org/show_bug.cgi?id=51503)
* [x] [concepts] [ice] deduction guide (https://bugs.llvm.org/show_bug.cgi?id=51537)

### Follow up tasks:

- [x] update supported platforms: http://docs.seqan.de/seqan/3-master-user/setup.html and https://github.com/seqan/seqan3/blob/master/README.md

**Comment by eseiler** [comment]
Closing, will reopen a new Compiler support meta issue.
