### ISSUE TITLE
Install wordpress version plugin to easily roll back if website issues occur after installing or updating plugins.

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#14]
### Description

Use a git integration in order to rollback to a working version of the website after plugins have been updated or installed.

### Acceptance Criteria

- [ ] Test that a rollback to a previous version works without destroying the website
- [ ] Test that we can also go to a more recent commit after a roll back in order to actually fix the issues there. 

### Tasks
- [ ] read the blog article for setting it up: https://t3n.de/news/wordpress-und-git-einstieg-748318/
- [ ] install and configure https://versionpress.com/

**Comment by simonsasse** [comment]
"VersionPress is still a developer preview and should not or only with caution be used in production."
Since the installation of `VersionPress` is not as easy as thought and we do not have the necessary resources for web-development, this issue has been closed.
