### ISSUE TITLE
Define iterator/sentinels from a view outside a view

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#141]
### Description 

For example the `view_take` defines the iterator within the class itself:

```c++
template <std::ranges::view urng_t, bool exactly, bool or_throw>
class view_take : public std::ranges::view_interface<view_take<urng_t, exactly, or_throw>>
{
...
    template <typename rng_t>
    class iterator_type : public inherited_iterator_base<iterator_type<rng_t>, std::ranges::iterator_t<rng_t>>
    {
... // iterator content
    }
};
```
https://github.com/seqan/seqan3/blob/22d1a70e039e68188a5003ff8cc339eb30f420dc/include/seqan3/range/views/take.hpp#L65-L67

Just declare the iterator within the view itself and move the actual implementation outside:

```c++
template <std::ranges::view urng_t, bool exactly, bool or_throw>
class view_take : public std::ranges::view_interface<view_take<urng_t, exactly, or_throw>>
{
...
    template <typename rng_t>
    class iterator_type; // just forward declare
};

template <std::ranges::view urng_t, bool exactly, bool or_throw>
template <typename rng_t>
class view_take<urng_t, exactly, or_throw>::iterator_type : public inherited_iterator_base<iterator_type<rng_t>, std::ranges::iterator_t<rng_t>>;
    // actual definition
{
... // iterator content
};
```

See [`kmer_hash`](https://github.com/seqan/seqan3/blob/22d1a70e039e68188a5003ff8cc339eb30f420dc/include/seqan3/range/views/kmer_hash.hpp#L51-L54) how this looks like after separating of declaration and defition.

### Acceptance Criteria

- [ ] Declaration / Definition are separate.

### Tasks

 

- [ ] Find and list all left-over views where the iterator / sentinel is not defined out-of-class
- [ ] separate Declaration / Definition:
  - [x] `take_view`
  - [x] view_take_until (already done)
  - [x] pairwise_combine_view
  - [x] repeat_view
  - [x] alignment_column_type ? Must not be done in this issue, we can think about containers later :)
  - [x] The tutorial for writing a view ?

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by simonsasse** [comment]
### VIEWS to be changed:

- [x] take_view
- [x] view_take_until (already done)
- [x] pairwise_combine_view
- [x] repeat_view
- [x] alignment_column_type ? Must not be done in this issue, we can think about containers later :)
- [x] The tutorial for writing a view ? (Was already separated)

**Comment by marehr** [comment]
Can you update you master? Because view_take_until was already done in a recent PR.

**Comment by rrahn** [comment]
Resolved by seqan/seqan3#1914
