### ISSUE TITLE
Suggestion from hannes concerning : seqan/seqan3#1542

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#145]
Former resolution: https://github.com/seqan/seqan3/pull/1892

* The `to_rev_cursor` is inefficient and unintuitive.
* The use case to search unidirectional in both directions is valid (although not yet used anywhere)

Proposal : 
* Remove `to_rev_cursor` and `to_forward_cursor` for now as they are not used. 
* `to_forward_cursor` is useless anyway because you could to everything on the bidirectional cursor (search unidirectional to the left).
* If the feature request is asked for, rather supply a "mirror" of the bidirectional index, that calls internally does extend_right if the user calls extend_left (search unidirectional to the left). When locating, we can automatically locate on the forward index and get the correct positions.

### Resolution (24.06.2020) 

We remove the `to_rev_interface` and the `to_forward_interface` since it is in the current state not stable or clearly defined what the expected behaviour should be.

### Tasks

- [x] Remove the `to_rev_cursor` interface from the `bi_fm_index_cursor`
- [x] Remove the `to_forward_interface` interface from the `bi_fm_index_cursor`
- [x] Fix tests accordingly
- [x] Update documentation/tutorial accordingly
- [x]  Add API break changelog

**Comment by eseiler** [comment]
Closed via https://github.com/seqan/seqan3/pull/1892
