### ISSUE TITLE
Performance of minimiser view with second range 

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#148]
### Description 

The minimiser view is faster in combination with the second range if the second range is given explicitly. 
But we would like to have the following interface which uses the zipped input ranges with an aggregation as it is more generic from the design:
```cpp
auto v = seqan3::views::minimiser(seqan3::views::zip(r1, r2) | std::transform(pair_min)), 10) | another_view;
```

### Acceptance Criteria

- [ ] Find why the current minimiser with the second range is faster than on the zipped input
- [ ] Allow the proposed interface with the same performance.

### Tasks

 

- [ ] add micro benchmarks
- [ ] implement the new view design and optimise the performance. 

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
