### ISSUE TITLE
std::common_with requirement in seqan3::complement CPO triggers ICE

### ISSUE THREAD

**Issue by smehringer** [seqan/product_backlog#149]
### Description 

* seqan 3.0.1
* Compiler GCC7.5/8.4 : ICE
* Compiler GCC9.3 : `fatal error: template instantiation depth exceeds maximum of 900`

The following triggers an ICE when compiling the `bitcompressed_vector_test`: 

https://github.com/seqan/seqan3/blob/master/include/seqan3/alphabet/nucleotide/concept.hpp#L46

(Also see related PR https://github.com/seqan/seqan3/pull/1923)

Although the following works:

```cpp
TEST(bitcompressed_vector_test, common_with_ice)
{
    EXPECT_TRUE((std::common_with<seqan3::bitcompressed_vector<seqan3::dna4>::reference, seqan3::dna4>));
    EXPECT_TRUE((std::common_with<seqan3::dna4, seqan3::bitcompressed_vector<seqan3::dna4>::reference>));
}
```

### Acceptance Criteria

Code compiles

### Tasks

- [ ] Investigate ICE

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by marehr** [comment]
Which compiler? Isn't this a bug? This should then be a bug report in seqan/seqan3, or?

**Comment by rrahn** [comment]
Can you please add the missing line of code or the test case that triggers the ICE for reproduction. Also please add the missing compiler and system information as suggested by @marehr. Thank you.

**Comment by smehringer** [comment]
I included the line and the compiler

>  Isn't this a bug?

I am not sure because I did not have time to investigate. The Problem is, as mentioned in the description, that the concept check itself
```
EXPECT_TRUE((std::common_with<seqan3::bitcompressed_vector<seqan3::dna4>::reference, seqan3::dna4>));
```
Does not trigger the error. So it seems to be an issue of the CPO
