### ISSUE TITLE
Fix some displaying issues after the update of the avada theme.

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#15]
### Description

After the update of the avada theme some of the features of the website broke like the header is displayed above and beneith the slider.

### Acceptance criteria
- [x] The website behaves as expected and can be maintained

###  Tasks
- [x] Fix the double header
- [x] Fix the circles on the main page which seem to be a little clinched
- [x] Fix the acordion widget on the peoples page. For some people it collapses directly after unfolding it.
- [x] Fix the toggle icon in the inner accordion widget.
- [x] Delete hoverable text on seqan.de displaying `tooltip here?`.
- [x] Add dots after finished sentences.
- [x] Fix Icon Images on Start Page. 
- [x] Removed question mark after `WELCOME TO THE SEQAN LIBRARY` Heading on `getting started` page.
- [ ] Update WP and some PlugIns.

**Comment by simonsasse** [comment]
fixed accordion toggle:
`Toolset -> Settings -> General -> Bootstraps Layou`t and changed the radio button to `This site is not using Bootstrap CSS`.
link:`https://toolset.com/forums/topic/avada-fusion-toggle-stop-working-as-accordion-when-view-is-activated/`

**Comment by simonsasse** [comment]
on seqan.de in the `data structures` box, there is a greyish part of the text: `sequence analysis`
if you hover over it, a small box appears displaying `tooltip here?`
I think I can delete the hover link right ? seems like this is a leftover of some experiment.
<img width="571" alt="Bildschirmfoto 2020-04-01 um 13 19 35" src="https://user-images.githubusercontent.com/59832939/78131506-7ab76600-741b-11ea-8fdf-0ebd9d701192.png">
