### ISSUE TITLE
Refactor the container_test_template.hpp do not use dna4 explicitily

### ISSUE THREAD

**Issue by smehringer** [seqan/product_backlog#150]
### Description 

Currently the `container_test` (and after https://github.com/seqan/seqan3/pull/1923 is merged the `container_test_template.hpp`) is explicitly using `seqan3::dna4` but it should not. Instead the container test template should be refactored to be templatised over the alphabet. 

### Tasks

- [ ] Refactor container_test_template

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
