### ISSUE TITLE
SAM benchmark takes too long

### ISSUE THREAD

**Issue by eseiler** [seqan/product_backlog#157]
### Description 

The format sam benchmarks get timed out in the nightlies (15min+ runtime):
https://cdash.seqan.de/index.php?project=SeqAn3#!#performance

### Acceptance Criteria

- Perforamnce benchmarks (Debug) do not lead to timeout

### Tasks

- [x] Reduce parameters in sam benchmark and run benchmark in Debug mode

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
