### ISSUE TITLE
Core / Utility Split

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#160]
We split the core module into core module and utility module: ([Card](https://github.com/orgs/seqan/projects/4#card-26785084))

* core is everything strongly coupled with our library, required by > 1 module, and is not stand-alone.
* utility contains features not related to biological use cases and could potentially live as stand-alone libraries outside of SeqAn.
*    [Here](https://gist.github.com/rrahn/f6b09ad67bebd14bd9c58f77c53e0450) is a gist with an overview of the current state of core and the possible split.

https://gist.github.com/rrahn/f6b09ad67bebd14bd9c58f77c53e0450

for extracting core into utility; e.g. tuple etc, type_traits into utility.

@marehr

---
09.12.2019

---
We will split all files into either utility or core. see the protocol for further details

https://github.com/seqan/seqan3/wiki/Core-Meeting-notes#2019-12-09-rrahn

---

### Acceptance criteria

* Including the old header should not break the current code.
* Including the old header should raise a deprecation warning and output the new header that needs to be included.
 
### Tasks per header
 - [ ] copy the header to the correct place
 - [ ] shortly check if all header includes are correct: remove unused, order alphabetically, put `seqan3/std/*` headers to the top
 - [ ] possibly rename the header
 - [ ] deprecate old header with header deprecation macro: 
     ```cpp
    SEQAN3_DEPRECATED_HEADER(
        "This header is deprecated and will be removed in SeqAn-3.1.0; Please #include <seqan3/alphabet/aminoacid/translation_new.hpp> instead.")
    ```
 - [ ] deprecate old header doxygen file section: add `[DEPRECATED]` at begin of brief and add `\deprecated This header is deprecated and will be removed in SeqAn-3.1.0; Please  \#include <new header> instead.` tag.
 - [ ] move all related tests, snippets etc to match new folder structure
 - [ ] run all tests to see if nothing depends on old header anymore
 - [ ] live happily ever after

### submodule/header assignment (please see gist https://gist.github.com/rrahn/f6b09ad67bebd14bd9c58f77c53e0450)
 - [x] algorithm [@Irallia]
  **Open Questions:**
   * algorithm/pipeable_config_element.hpp -> **Needs discussion/resolution**
 - [x] char_operations [@smehringer]
 - [x] concept [@simonsasse]
   - [x]  Move `core/concept/core_language.hpp` -> `utility/detail/exposition_only_concept.hpp` [@sgssgene] (https://github.com/seqan/seqan3/pull/2351)
 - [x] detail (except debug_stream?) [@eseiler]
 - [x] parallel [@MitraDarja]
 - [x] simd [@marehr]
  Open Questions:
   * `utility/simd/simd_algorithm.hpp` -> `utility/simd/algorithm.hpp`? (https://github.com/seqan/seqan3/pull/2260#discussion_r523984711)
 - [x] type_list submodule [@rrahn]
 - [x] type_traits [@joergi-w]
 - [x] top-level header [@Irallia]
   - [x] bit_manipulation.hpp [@marehr & @Irallia] (https://github.com/seqan/seqan3/pull/2292 & https://github.com/seqan/seqan3/pull/2294)
   - [x] common_tuple [@eaasna] 
   - [x] math.hpp [@marehr]
   - [x] pod_tuple [@eaasna, @smehringer]
   - [x] tuple_utility.hpp [@sgssgene]
  **Open Questions:**
   * add_enum_bitwise_operators.hpp
   * all.hpp
   * debug_stream.hpp

**Comment by rrahn** [comment]
### Core meeting 2020-11-10

How to split the modules on a technical level.

### Requirements:
* Including the old header should not break the current code.
* Including the old header should raise a deprecation warning and output the new header that needs to be included.

### Open questions:
* What happens with the header-tests?
   * We will use some deprecation macro that allows us to deprecate an unused header.
   * This macro will be disabled when running the header tests.
* Should we, and if so how, also deprecate the header documentation?
  * In the file description add doxygen comment (See above https://github.com/seqan/product_backlog/issues/160#issue-655820550)
  * add `[DEPRECATED]` at the beginning of the brief section of the file block.

**Comment by rrahn** [comment]
### Resolution - Core meeting 2020-11-23

* We will remove detail/all.hpp headers and public all.hpp should not include detail headers.
* We remove them without any deprecation notice.

* If an existing all header includes partially from deprecated headers we add a 
   ```cpp
   #if SEQAN3_VERSION_MAJOR == 3 && SEQAN3_VERSION_MAJOR >= 1
        #pragma warning "DEV NOTICE: Remove the deprecated header #include <deprecated_header>."
   #endif
   ```

**Comment by smehringer** [comment]
Resolution 14-12-2020

* [ ]  `pipeable_config_element` should be moved into detail (@rrahn will tackle this)
  - [ ] Move file to core/configuration/detail
  - [ ] Move to `seqan3::detail` namespace
  - [ ] Rename to `configuration_element_base`
  - [ ] Make sure that the documentation of the configuration class does not refer any detail stuff (regarding the detail::pipeable_config_element).
  - [ ] Follow up: Check if interface documentation of "pipeability" could be put into `pipeable_config_element` and every config element can pull in this documentation.
  - See follow-up ticket https://github.com/seqan/product_backlog/issues/288

* [x] Move `core/concept/core_language.hpp` -> `utility/detail/exposition_only_concept.hpp`
  (Later we might discuss if we should remove some of the concept completely)
  * Done by https://github.com/seqan/seqan3/pull/2351

* [x] Move `core/simd/simd_algorithm` -> `utility/simd/algorithm.hpp` (@marehr )
  * Done by https://github.com/seqan/seqan3/pull/2260

**Comment by marehr** [comment]
I close this now, because it is mainly done. We have one follow-up ticket https://github.com/seqan/product_backlog/issues/288
