### ISSUE TITLE
[MSA] Tests for seqan2 / seqan3 hybrid MSA

### ISSUE THREAD

**Issue by smehringer** [seqan/product_backlog#162]
### Description 

We want extensive tests for MSA

### Tasks

- [x] Test default configuration on dna4
- [x] Test default configuration on rna5
- [x] Test default configuration on aa27
- [x] Test different gap score configurations
- [x] Test banded alignment on dna4
- [x] Test gap cost conversion with pairwise alignment.

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by smehringer** [comment]
Fixed by smehringer/seqan3#6

**Comment by marehr** [comment]
?

**Comment by smehringer** [comment]
If you want to reopen all of these issues there are more in the MSA epic ;)
