### ISSUE TITLE
[MSA] Add seqan3/seqan2 alphabet conversion functions to detail.hpp

### ISSUE THREAD

**Issue by smehringer** [seqan/product_backlog#163]
### Description 

Since the MSA does not work with seqan3 alphabets, we need to convert the respecitve alphabets into each other

### Tasks

- [x] Check which alphabets correspond to each other in seqan2 and seqan3
- [x] Add `convert_alph_3_to_2` overload for each pair of alphabets

**Comment by eseiler** [comment]
(For when you want to convert ranges)
In some PR I had conversion functionality for 3->2 which we did not end up using:

```cpp
template <typename to_t, typename from_t, template <typename> typename range_t>
    requires (seqan3::alphabet<from_t> && std::ranges::forward_range<range_t<from_t>>)
seqan::String<to_t> convert_single_range(range_t<from_t> const & original_range)
{
    seqan::String<to_t> result_range;
    seqan::reserve(result_range, std::ranges::size(original_range));

    for (auto const & element : original_range)
        appendValue(result_range, seqan3::to_char(element));

    return result_range;
}

template <typename to_t, typename from_t, template <typename> typename range_t>
    requires (seqan3::alphabet<from_t> && std::ranges::forward_range<range_t<from_t>>)
seqan::StringSet<seqan::String<to_t>> convert_range_of_range(std::vector<range_t<from_t>> const & original_range)
{
    seqan::StringSet<seqan::String<to_t>> result_range;

    for (auto const & single_range : original_range)
        appendValue(result_range, convert_single_range<to_t>(single_range));

    return result_range;
}
```

Can be used like `auto seqan2_sequence = convert_single_range<seqan2_alphabet_t>(sequence_seqan3);`

**Comment by smehringer** [comment]
Nice, but I think it is not quite what we need. Although we know the input type `from_t` we need to choose the output type automatically. So those functions cannot be applied as easily.

Current design (I know the name is horrible but it's just a draft)
```cpp

seqan::Dna convert_alphabet_3_to_2(seqan3::dna4 element)
{
    return seqan::Dna{seqan3::to_char(element)};
}

template <typename input_range_type>
align_multiple(input_range_type && input)
{
    // ...
       // here the from_t is std::ranges::range_value_t<input_range_type> but the to_t must be chosen accordingly
       appendValue(seqan2_sequence, convert_alphabet_3_to_2(current_character));
   // ...
}

```

We could do a function though that directly outputs a range.

**Comment by eseiler** [comment]
Yes, it's not exactly what you need, it is just kinda related.
I read the ticket in my notifications and was reminded that I did something similar once.

And because the stuff is only part of some force-push, it's not easily findable.

Btw, if the assignment from `char` to SeqAn3 and SeqAn2 alphabets is the same - should be -, then you only need to determine the `to_t` once and then just append the character representation - depending on what you really need (and what the compiler wants to (not) optimize), you may actually use the `convert_*_range` after all :)

To determine `to_t` from `from_t` could just be a really long `std::conditional_t` :D

**Comment by smehringer** [comment]
I'll look into it again :) Thanks for the input

**Comment by simonsasse** [comment]
LIST OF (corresponding) TYPES:
- [x] seqan3::aa27 -> seqan::AminoAcid
- [x] seqan3::aa10murphy ? -> seqan::Murphy10
- [x] seqan3::aa10li ? -> seqan::Li10
- [x] seqan3::dna4 -> seqan::Dna
- [x] seqan3:: dna5 -> seqan::Dna5
- [x] seqan3:: dna15 -> seqan:: Iupac
- [x] seqan3::rna4 -> seqan::Rna
- [x] seqan3::rna5 -> seqan::Rna5

no corresponding alphabets found:
- [ ] seqan3:: rna15 -> seqan::??
- [ ] seqan3:: sam_dna16 -> seqan::??
- [ ] seqan3:: dna3bs -> seqan::??
- [ ] seqan3:: ? -> seqan::DnaQ
- [ ] seqan3:: ? -> seqan::Dna5Q
- [ ] seqan3::aa20 ? -> seqan::ReducedAminoAcid is just a template for Li10 and Murphy10..

I am not sure wether we need conversions for the Quality alphabets and the cigar alphabet ?

**Comment by rrahn** [comment]
Would it not be easier to just use `char` at the moment for SeqAn2? It would probably require some generic adaptor to convert the scoring matrix into a char matrix but that would be all. Or at least I don't know any specific place where we have an advantage using bit compression during the alignments. And also the whole msa machinery should probably work with a simple char alphabet.

**Comment by smehringer** [comment]
Maybe I don't understand your suggestion, but I think it's easier to add the alphabet conversions (which is really just a one liner for each alphabet) instead of converting the scoring matrices. But I haven't worked with the scoring matrices yet.

Anyway, we can always change this once the initial draft is ready and the tests are set up? :)
(This is just a first draft, especially the namings are awkward :D But I didn't want to spend time on them yet)

**Comment by smehringer** [comment]
Fixed by smehringer/seqan3#5

**Comment by rrahn** [comment]
I just wanted to make your life easy by suggesting some sort of type erasure to the base type char 😊.
