### ISSUE TITLE
Search configuration: Enable on_result configuration for the search

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#169]
### Description 

Provide the mechanism to define a user callback for the search instead of returning the search algorithm.

### Acceptance Criteria

- [x] on_result works

### Tasks

 

- [x] implement, test and document search_cfg::on_result.

### Definition of Done

- [x] Implementation and design approved
- [x] Unit tests pass
- [x] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [x] API documentation added
- [x] Tutorial/teaching material added
- [x] Test suite compiles in less than 30 seconds (on travis)
- [x] Changelog entry added

**Comment by rrahn** [comment]
resolved by seqan/seqan3#2019
