### ISSUE TITLE
Update the content on the seqan website

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#17]
### Description 

The content on the website is a little outdated. For example the peoples page needs to be updated and also the projects might not be accurate anymore.

### Acceptance Criteria

- [x] The peoples page shows current members and alumnis, contributors accordingly
- [x] The projects are uptodate.

### Tasks

 

- [x] Update the peoples page
- [x] Update the projects/application page

**Comment by rrahn** [comment]
@simonsasse since you are workin on this. Can you request from every new person the detals for adding them to the peoples page? Thanks
