### ISSUE TITLE
Upgrade to ranges v3 0.11.0

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#170]
A new version of ranges was released. 

### Tasks

- [x] Upgrade the ranges submodule
- [x] Update the ranges version in platform.hpp 
- [x] Check that everything works

**Comment by rrahn** [comment]
resolved by seqan/seqan3#2014
