### ISSUE TITLE
[Alignment Config] Change align_cfg::gap to align_cfg::gap_cost_affine

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#176]
### Description 

We remove the gap cost scheme and implement a direct high-level configuration element for the affine gap scheme. 

Here is the proposed change of the interface:

```
seqan3::align_cfg::gap_cost_affine    [optional]

construction

seqan3::align_cfg::gap_cost_affine affine{seqan3::align_cfg::open_score{-10}, seqan3::align_cfg::extension_score{-1}};

later access and set

affine.open_score = seqan3::align_cfg::open_score{-10};
affine.extension_score = seqan3::align_cfg::extension_score{-1};

or by seqan::get

auto && affine = seqan3::get<seqan3::align_cfg::gap_cost_affine>(config);
affine.open_score = seqan3::align_cfg::open_score{-10};
affine.extension_score = seqan3::align_cfg::extension_score{-1};

query if configuration was piped

config_t::template exists<seqan3::align_cfg::gap_cost_affine>()
```

### Acceptance Criteria

- [x] All of the alignment works with the changed align_cfg::gap_cost_affine

### Tasks

 

- [x] Add an implementation for the align_cfg::gap_cost_affine
- [x] Make the basic tests for the new configuration element 
- [x] Replace any occurrence of align_cfg::gap with the new config
- [x] Remove old align_cfg::gap configuration
- [x] Update the documentation and snippets accordingly
- [x] Deprecate gap_scheme

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
