### ISSUE TITLE
[Alignment Configuration] Change align_cfg::scoring to align_cfg::scoring_scheme

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#177]
### Description 

We rename the align_cfg::scoring config to align_cfg::scoring_scheme. 

Here the proposed change of the interface:

```
seqan3::align_cfg::scoring_scheme    [required]

auto my_scoring_scheme = seqan3::nucleotide_scoring_scheme{seqan3::match_score{5}, seqan3::mismatch_score{-3}};

construction

seqan3::align_cfg::scoring_scheme scheme{my_scoring_scheme}; 

later access and set

scheme.scheme = my_scoring_scheme;    

or by seqan::get

auto && scheme = seqan3::get<seqan3::align_cfg::scoring_scheme>(config);
scheme.scheme = my_scoring_scheme;

query if configuration was piped

config_t::template exists<seqan3::align_cfg::scoring_scheme>() 
```

### Acceptance Criteria

- [ ] All of the alignment works with the renamed align_cfg::scoring_scheme and the above interface.

### Tasks

 

- [ ] Rename align_cfg::scoring to align_cfg::scoring_scheme
- [ ] Update the documentation and snippets accordingly

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by wvdtoorn** [comment]
Fixed by https://github.com/seqan/seqan3/pull/2027.
