### ISSUE TITLE
[Alinment Configuration] Change align_cfg::vectorise to align_cfg::vectorised

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#178]
### Description 

Here is the proposed change of the interface:

```
construction - no construction since it is a tag

seqan3::align_cfg::vectorised;
// this is an instance of seqan3::align_cfg::vectorised_tag     

only check if present!

constexpr bool is_vectorised = config_t::template exists<seqan3::align_cfg::vectorised_tag>();
```

### Acceptance Criteria

- [x] All of the alignment works with the changed align_cfg::vectorised

### Tasks

 

- [x] Rename align_cfg::vectorise to align_cfg::vectorised
- [x] Rename the class to align_cfg::vectorised_tag
- [x] Update the documentation and snippets accordingly

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by wvdtoorn** [comment]
fixed by https://github.com/seqan/seqan3/pull/2026
