### ISSUE TITLE
[Alignment Configuration] Replace using_score_type tag for align_cfg::output with align_cfg::score_type

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#179]
### Description 

Before the score type of the alignment could be set via an additional property of the align_cfg::output option. 
This should now introduce a stand alone option called align_cfg::score_type that allows to choose the score type and is orthogonal to the existing output configuration. The old using_score_type flag will be removed.

Here is the proposed change of the interface:

```
seqan3::align_cfg::score_type    [optional]
If this config was not set it calculates with int32_t

usage: seqan3::align_cfg::score_type<float>

construction - no construction since it is a tag

seqan3::align_cfg::score_type<float>;
// this is an instance of seqan3::align_cfg::score_type_tag     

access by seqan::get:

auto && var = seqan3::get<seqan3::align_cfg::score_type_tag>(config);

check if present:

constexpr bool has_score_type = config_t::template exists<seqan3::align_cfg::score_type_tag>();```
```

### Acceptance Criteria

- [ ] All of the alignment works with the new align_cfg::result_type flag
- [ ] The old interface using the using_score_type flag is disabled

### Tasks

 

- [ ] Make a new configuration object align_cfg::score_type
- [ ] Replace the instances of old mechanism with using_score_type with the new configuration object.
- [ ] Update the documentation and snippets accordingly

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
