### ISSUE TITLE
EPR Dictionaries

### ISSUE THREAD

**Issue by cpockrandt** [seqan/product_backlog#18]
EPR-dictionary should be a specialization of the wavelet tree and implement die wavelet tree interface (rank + access)

### Tasks

- [ ] Implement the dictionary
- [ ] Add micro benchmarks
- [ ] add macro benchmarks

**Comment by eseiler** [comment]
https://github.com/xxsds/sdsl-lite/pull/75
