### ISSUE TITLE
[Alignment Configuration] Change the align_cfg::output to high-level configuration elements.

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#180]
### Description 

Before the align_cfg::output was a top-level class that could be specified with constructor arguments to enable certain outputs of the alignment. They were inclusive, such that choosing alignment also generated the score, the begin and end coordinates. This will be changed such that each configured output option is a top-level configuration element which can be combined with the others to generate a 

Here is the proposed change of the interface:

```
Output Configurations
If none of the output options was given then the alignment result contains all outputs.
seqan3::align_cfg::output_score    [optional]
If this config the alignment result does not contain the score, unless none of the output options is set.

usage: seqan3::align_cfg::output_score

construction - no construction since it is a tag

seqan3::align_cfg::output_score;
// this is an instance of seqan3::align_cfg::output_score_tag     

access by seqan::get:

auto && var = seqan3::get<seqan3::align_cfg::output_score_tag>(config);

check if present:

constexpr bool with_score = config_t::template exists<seqan3::align_cfg::output_score_tag>();

seqan3::align_cfg::output_end_position    [optional]
If this config is set the alignment result contains the end positions of the actual alignment within the sequences.

usage: seqan3::align_cfg::output_end_position

construction - no construction since it is a tag

seqan3::align_cfg::output_end_position;
// this is an instance of seqan3::align_cfg::output_end_position_tag     

access by seqan::get:

auto && var = seqan3::get<seqan3::align_cfg::output_end_position_tag>(config);

check if present:

constexpr bool with_end_position = config_t::template exists<seqan3::align_cfg::output_end_position_tag>();

seqan3::align_cfg::output_begin_position    [optional]
If this config is set the alignment result contains the begin positions of the actual alignment within the sequences.

usage: seqan3::align_cfg::output_begin_position

construction - no construction since it is a tag

seqan3::align_cfg::output_begin_position;
// this is an instance of seqan3::align_cfg::output_begin_position_tag     

access by seqan::get:

auto && var = seqan3::get<seqan3::align_cfg::output_begin_position_tag>(config);

check if present:

constexpr bool with_begin_position = config_t::template exists<seqan3::align_cfg::output_begin_position_tag>();

seqan3::align_cfg::output_alignment    [optional]
If this config is set the alignment result contains the alignment (traceback).

usage: seqan3::align_cfg::output_alignment

construction - no construction since it is a tag

seqan3::align_cfg::output_alignment;
// this is an instance of seqan3::align_cfg::output_alignment_tag     

access by seqan::get:

auto && var = seqan3::get<seqan3::align_cfg::output_alignment_tag>(config);

check if present:

constexpr bool with_alignment = config_t::template exists<seqan3::align_cfg::output_alignment_tag>();

seqan3::align_cfg::output_sequence1_id    [optional]
If this config is set the alignment result contains the id of the reference sequence.

usage: seqan3::align_cfg::output_sequence1_id

construction - no construction since it is a tag

seqan3::align_cfg::output_sequence1_id;
// this is an instance of seqan3::align_cfg::output_sequence1_id_tag     

access by seqan::get:

auto && var = seqan3::get<seqan3::align_cfg::output_sequence1_id_tag>(config);

check if present:

constexpr bool with_alignment = config_t::template exists<seqan3::align_cfg::output_sequence1_id_tag>();
seqan3::align_cfg::output_sequence2_id    [optional]
same as output_sequence1_id
```

### Acceptance Criteria

- [ ] The new output configurations are implemented and work with the alignment 
- [ ] The old interface with the nested structure is disabled.

### Tasks

 

- [x] Add the new configuration align_cfg::output_score
- [x] Add the new configuration align_cfg::output_end_position
- [x] Add the new configuration align_cfg::output_begin_position
- [x] Add the new configuration align_cfg::output_alignment
- [x] Add the new configuration align_cfg::output_sequence1_id
- [x] Add the new configuration align_cfg::output_sequence2_id
- [x] Replace the instances of the old mechanism with the new configuration elements.
- [x] Update the documentation and snippets accordingly

### Definition of Done

- [x] Implementation and design approved
- [x] Unit tests pass
- [x] Test coverage = 100%
- [x] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [x] API documentation added
- [x] Tutorial/teaching material added
- [x] Test suite compiles in less than 30 seconds (on travis)
- [x] Changelog entry added
