### ISSUE TITLE
[Alignemnt Configuration] Put align_cfg::debug into align_cfg::detail::debug

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#181]
### Description 

We want the align_cfg::detail subnamespace for alignment configurations.
Here is the proposed change of the interface:

```
seqan3::align_cfg::detail::debug    [optional]
usage: seqan3::align_cfg::detail::debug

construction - no construction since it is a tag

seqan3::align_cfg::detail::debug;
// this is an instance of seqan3::align_cfg::detail::debug_tag     

access by seqan::get:

auto && var = seqan3::get<seqan3::align_cfg::detail::debug_tag>(config);

check if present:

constexpr bool in_debug_mode = config_t::template exists<seqan3::align_cfg::detail::debug_tag>();
```

### Acceptance Criteria

- [ ] Introduce and documented subnamespace align_cfg::detail

### Tasks

 

- [ ] Put the debug option into seqan3::align_cfg::detail subnamespace.

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by smehringer** [comment]
Fixed by seqan/seqan3#2020
