### ISSUE TITLE
[Alignment Configuration] Change the align_cfg::max_error to align_cfg::min_score

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#182]
### Description 

Before we had the align_cfg::max_error which was used to indicate the maximum errors for the edit alignment. But one can also translate it to min_score and thus make it applicable for non-edit scoring schemes as well.
Here is the proposed change of the interface:

```
seqan3::align_cfg::min_score    [optional]
Produces an alignment result for every score which has at least min_score. (i.e. report results with min_score <= score)
Returns empty alignment results if the score could not be reached.

construction

seqan3::align_cfg::min_score min_score{-5};    

later access and set

min_score.score = -5;    

access by seqan::get:

auto && min_score = seqan3::get<seqan3::align_cfg::min_score>(config);
min_score.score = -5;

check if present:

config_t::template exists<seqan3::align_cfg::min_score>();
```

### Acceptance Criteria

- [ ] The alignment now works with align_cfg::min_score instead of align_cfg::max_error

### Tasks

 

- [ ] Rename align_cfg::max_error to align_cfg::min_score and also change the access of the stored value.
- [ ] Update the documentation and snippets if applicable.

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by rrahn** [comment]
fixed by seqan/seqan3#2021
