### ISSUE TITLE
[Alignment Configuration] Rename align_cfg::alignment_result_capture to align_cfg::detail::result_type

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#183]
### Description 

Here is the proposed change of the interface:

```
seqan3::align_cfg::detail::result_type    [optional]
If not set defaults to seqan3::detail::empty_type

usage: seqan3::align_cfg::detail::result_type<alignment_result_type<...>>

construction - no construction since it is a tag

template <typename result_t>
    requires seqan3::detail::is_type_specialisation_of_v<result_t, seqan3::alignment_result>
seqan3::align_cfg::detail::result_type;
// this is an instance of seqan3::align_cfg::detail::alignment_result_tag     

access by seqan::get:

auto && var = seqan3::get<seqan3::align_cfg::detail::alignment_result_tag>(config);

check if present:

constexpr bool has_result_type = config_t::template exists<seqan3::align_cfg::detail::alignment_result_tag>();
```

### Acceptance Criteria

- [ ] The configuration element was renamed and everything works as expected.

### Tasks

 

- [ ] Rename the align_cfg::alignment_result_capture to align_cfg::detail::result_type

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
