### ISSUE TITLE
doxygen 1.9.0 support

### ISSUE THREAD

**Issue by eseiler** [seqan/product_backlog#184]
### Reported bugs

* [x] [Markdown image includes not working](https://github.com/doxygen/doxygen/issues/8132)
* [x] [Segfault](https://github.com/doxygen/doxygen/issues/8139)
* [x] [Excluded symbols are looked up](https://github.com/doxygen/doxygen/issues/8143)
* [x] [Private symbols are looked up](https://github.com/doxygen/doxygen/issues/8148)
* [x] [inline namespace broken](https://github.com/doxygen/doxygen/issues/8167)
* [x] [excluded inline namespace broken](https://github.com/doxygen/doxygen/issues/8192)

### Fixed issues

* [x] [Use fully qualified namespace in copydoc](https://github.com/seqan/seqan3/pull/2229)

### Tasks

 

- Monitor the [nightly documentation builds](https://cdash.seqan.de/index.php?project=SeqAn3#!#documentation). These are build with the master branch of doxygen.
- If there is an error, investigate it and either report it upstream or adjust our documentation.

### Definition of Done

- [x] doxygen 1.9.0 is released and works with our documentation.

**Comment by eseiler** [comment]
Final PR https://github.com/seqan/seqan3/pull/2327
