### ISSUE TITLE
[MSA] Make seqan3::scoring_scheme work with seqan3::align_multiple

### ISSUE THREAD

**Issue by smehringer** [seqan/product_backlog#185]
### Description 

Right now you can only adapt the gap scores. We should also be able to provide a scoring scheme.

### Tasks

- [x] Investigate how seqan2 uses scoring matrices and which can be used in the MSA algorithm in seqan2
- [x] Make align_multiple work with `seqan3::align_cfg::scoring_scheme`
- [x] Add tests

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by smehringer** [comment]
Fixed by aff7e36
