### ISSUE TITLE
[MSA] Validate the configuration for seqan3::align_multiple

### ISSUE THREAD

**Issue by smehringer** [seqan/product_backlog#188]
### Description 

Currently the function `seqan3::align_multiple` just excepts any configuration and picks out the useful stuff.
We shouldn't allow to give just any configuration but restrict the config to the following:

* `seqan3::gap`
* `seqan3::band_fixed_size`

for now. 
Can be extended later.

### Tasks

- [ ] Write a function `validate_configuration(config)` which gets the config
- [ ] Inside validate_configuration, check whether only the valid configurations are set

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by smehringer** [comment]
Fixed by smehringer/seqan3#8
