### ISSUE TITLE
GCB 2020 - 14. September 2020 Tutorial

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#189]
### Description 

Important Dates:

* [x] Registration Deadline: 21.08.2020
* [x] Test Run: 01.09.2020 - 10.09
* [ ] Workshop: 14.09.2020 09:00-12:30, 13:30-17:00/18:00 (7h - 8h)
* [x] zoom meeting room for test
* [x] Daniel Wibberg register on de.NBI website + survey link
* [ ] Presentation extended filter 
* [x] Schedule breaks
* [ ] Concepts basic chapter
* [ ] Send setup guide until Friday

Will be held with zoom.

Workshop: https://gcb2020.de/workshops.html

Our course description: https://gcb2020.de/WS4.html

### TODOS:

Orga:
- [ ] how and when to register (you get a private link) [21.08.2020]
- [ ] what to present (?????) [all]
- [ ] who presents? [@rrahn, @smehringer, @marehr, @eseiler (@joergi-w, @Irallia)?]
- [ ] check that the de.NBI/Elixir logo is displayed on the GCB site []
- [ ] Please take a moment to review the details we have listed for your tutorial and send me any updates or changes: https://gcb2020.de/WS4.htm. []
- [ ] registration at de.NBI (write daniel wibberg a mail with the registration template) [@marehr]
- [ ] twitter, email announcement [@rrahn]
