### ISSUE TITLE
[SPIKE] Analyse the performance differences of EPR dictionaries in the SDSL compared to SeqAn2

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#19]
### Description 

Reduce the benchmark which  shows performance differences
How is the code comparable? Can we further reduce the functionality to spot what's causing the difference.

### Acceptance Criteria

- [x] Based on this evaluation decide where to implement the EPR: SeqAn3 or SDSL.

### Tasks

 

- [x] Isolate the EPR dictionaries from SeqAn
- [x] Isolate the EPR dictionaries from SeqAn3/SDSL
- [x] Measure performance of both implementations
- [x] Track performance difference by iteratively reducing the test

**Comment by rrahn** [comment]
@svnbgnk @eseiler do we have a first result on this? What is our take? Do we know how much sentinels in our sdsl adaption play a role for the performance drop? Would you think GSA and the adaption of the SACA for GSA can improve the performance? I remember that a micro-benchmark by @smehringer comparing a single text with a text-collection with one text had a 10% somewhat performance drop. I would try to tackle the SACA etc in this sprint. But we should make sure that we focus on the things that give the biggest bang for the buck. So the goal of this would be to get the index search of Lambda3 ported to SeqAn3

**Comment by eseiler** [comment]
We identified the **in-block-rank-query** as the component that causes the performance difference:

### **SDSL**
```cpp
    uint32_t word_prefix_rank(const uint64_t* data, const size_type idx, const value_type v) const
    {
        size_type const bit_pos = idx * sigma_bits;
        uint64_t const w = *(data + (bit_pos / bits_per_word));
        return bits::cnt(set_positions_prefix(w, v) & bits::lo_set[(bit_pos % bits_per_word) + 1] );
    }
```

`data` is a pointer to the text - jumping back into the text is an (almost) guaranteed cache miss for sufficiently big texts.

### **SeqAn2**
The in-block-rank-query information is stored *within* the block - this is much more cache friendly.

### Timings

SDSL 
```console
--------------------------------------------------------------
Benchmark                    Time             CPU   Iterations
--------------------------------------------------------------
rank<4>/100               12.2 ns         12.0 ns     56000000
rank<4>/10000             12.6 ns         12.6 ns     56000000
rank<4>/1000000           13.0 ns         12.9 ns     49777778
rank<4>/100000000         76.3 ns         76.7 ns      8960000
rank<4>/1000000000         105 ns          103 ns      6400000
rank<27>/100              11.7 ns         11.7 ns     56000000
rank<27>/10000            12.8 ns         12.9 ns     64000000
rank<27>/1000000          16.5 ns         16.5 ns     40727273
rank<27>/100000000         129 ns          128 ns      5600000
rank<27>/1000000000        177 ns          176 ns      4072727
```
---
SeqAn2
```console
----------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations
----------------------------------------------------------------------------
rank<seqan::Dna>/100                    14.6 ns         14.4 ns     49777778
rank<seqan::Dna>/10000                  14.5 ns         14.4 ns     49777778
rank<seqan::Dna>/1000000                14.7 ns         14.8 ns     49777778
rank<seqan::Dna>/100000000              67.2 ns         67.0 ns     11200000
rank<seqan::Dna>/1000000000             75.0 ns         75.3 ns     11200000
rank<seqan::AminoAcid>/100              14.3 ns         14.4 ns     49777778
rank<seqan::AminoAcid>/10000            14.3 ns         14.1 ns     49777778
rank<seqan::AminoAcid>/1000000          23.7 ns         23.4 ns     32000000
rank<seqan::AminoAcid>/100000000        84.1 ns         83.7 ns      8960000
rank<seqan::AminoAcid>/1000000000        123 ns          123 ns      5600000
```
---

As can be seen, the SDSL performance is comparable to the SeqAn2 performance until a certain text size - after that most in-block-rank-queries are cache misses and the performance degrades.

**Comment by rrahn** [comment]
Ok, here is my last night update on the benchmark:
```
Run on (16 X 2927 MHz CPU s)
CPU Caches:
  L1 Data 32K (x8)
  L1 Instruction 32K (x8)
  L2 Unified 256K (x8)
  L3 Unified 8192K (x2)
Load Average: 1.39, 1.47, 1.40
----------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations
----------------------------------------------------------------------------
rank<seqan::Dna>/100                    38.7 ns         38.7 ns     18101139
rank<seqan::Dna>/10000                  38.8 ns         38.8 ns     18063871
rank<seqan::Dna>/1000000                40.4 ns         40.4 ns     17322857
rank<seqan::Dna>/100000000               104 ns          104 ns      6731921
rank<seqan::Dna>/1000000000              127 ns          127 ns      5449463
rank<seqan::AminoAcid>/100              38.8 ns         38.8 ns     18046667
rank<seqan::AminoAcid>/10000            39.3 ns         39.3 ns     17789259
rank<seqan::AminoAcid>/1000000          57.7 ns         57.7 ns     11971766
rank<seqan::AminoAcid>/100000000         137 ns          137 ns      5679486
rank<seqan::AminoAcid>/1000000000        217 ns          217 ns      3226827
```

and now sdsl epr ranks:

```
--------------------------------------------------------------
Benchmark                    Time             CPU   Iterations
--------------------------------------------------------------
rank<4>/100               37.5 ns         37.5 ns     18664892
rank<4>/10000             37.6 ns         37.6 ns     18603129
rank<4>/1000000           39.6 ns         39.6 ns     17695698
rank<4>/100000000          113 ns          113 ns      6183010
rank<4>/1000000000         126 ns          125 ns      4695291
rank<27>/100              38.2 ns         38.2 ns     18324643
rank<27>/10000            38.9 ns         38.9 ns     17956369
rank<27>/1000000          59.5 ns         59.5 ns     11636891
rank<27>/100000000         144 ns          143 ns      5037389
rank<27>/1000000000        223 ns          223 ns      3154966
```
So it is getting faster. We are now in a 5-8% performance window around SeqAn. The message basically is that the sdsl int_vector and its iterator implementation is very slow. Operating on the iterators for the block and superblock int_vectors inside of the rank function killed most of the performance. Now I store the blocks and superblocks in std::array structures (similar to SeqAn which uses our seqan::Tuple implementation). For the text I use a simple bit compressed storage. I could extend this for the blocks, since we know at compile time how many bits are needed to store the block counts. Everything else could then relate to some better arithmetic operations inside of SeqAn. But I would propose, to first get the full EPR working without any additional text copies and plugging this into lambda to see what difference this makes.

**Comment by rrahn** [comment]
I have now an implementation that seems to be at least as good or faster depending on the CPU. Let's see what happens if the implementation is tested within Lambda and other tools. But I think this can be closed now.
