### ISSUE TITLE
[Alignment Configuration] Make sure that only the id of the sequences is provided if the output option is set.

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#191]
### Description 

This is a follow up issue from #180. After changing from align_cfg::result to align_cfg::output we made all output options non-inclusive. This means that if I specify for example align_cfg::output_alignment, the score won't be accessible through the alignment_result object. 
This works so far for all output configurations except the sequence_id1 and sequence_id2. Since we haven't yet implemented the interface to pass the ids from outside we have to use internal ids. But we can already provide the interface, i.e. the ids represent only the position of the pair within the set and that they are only available in the default case or if explicitly enabled. Later we need to adapt the interface to allow the user to provide ids

### Acceptance Criteria

- [ ] sequence1 id and sequnce2 id are available if no output option was given in the alignment configuration.
- [ ] otherwise sequence1 id is only available if the option seqan3::align_cfg::output_sequence1_id was given
- [ ] also sequence2 id is only available if the option seqan3::align_cfg::output_sequence2_id was  given
- [ ] for the moment sequence 1 id and sequence2 id correspond to the index of the sequence pair.

### Tasks

 

- [ ] make the sequence1_id not default available in the seqan3::alignment_result
- [ ] make the sequence2_id not default available in the seqan3::alignment_result
- [ ] Change the alignment result builder to only store the id if the option was specified.
- [ ] Adapt the tests, that require the id
- [ ] Adapt the snippets that document the id as default
- [ ] Adapt the API docs and the tutorials if applicable.

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by marehr** [comment]
Can you give an example?

**Comment by smehringer** [comment]
@rrahn Isn't this fixed by seqan/seqan3#2064 ? Or is there somehting missing?

**Comment by rrahn** [comment]
fixed by seqan/seqan3#2064
