### ISSUE TITLE
[Alignment] edit_distance aligment: allow free_end_gaps in the second sequence, too

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#194]
### Description 

Currently, the edit distance algorithm only supports `seqan3::free_ends_first`, but from a theoretical POV it would be perfectly fine to support the "transposed" mode `seqan3::free_ends_second`, by swapping the two sequences and using `seqan3::free_ends_first`.

Some things to consider:
* Update documentation to state that only `seqan3::free_ends_first` is supported (see https://github.com/seqan/seqan3/blame/1e5d75a57672e7b2cc931c1e6b7d253777101e9f/doc/tutorial/pairwise_alignment/index.md#L310-L313)
* Is this working for the max_errors case? It should, right?
* In theory, it should also be possible to support the complete `seqan3::free_end_gaps` configuration without any swapping, right? 
  * Score-Matrix:
    |       | Ɛ | s | e | q | u | e | n | c | e | 1 |
    |-------|---|---|---|---|---|---|---|---|---|---|
    | **Ɛ** | x | x | x | x | x | x | x | x | x | x |
    | **s** | y | ? | ? | ? | ? | ? | ? | ? | ? | b |
    | **e** | y | ? | ? | ? | ? | ? | ? | ? | ? | b |
    | **q** | y | ? | ? | ? | ? | ? | ? | ? | ? | b |
    | **u** | y | ? | ? | ? | ? | ? | ? | ? | ? | b |
    | **e** | y | ? | ? | ? | ? | ? | ? | ? | ? | b |
    | **n** | y | ? | ? | ? | ? | ? | ? | ? | ? | b |
    | **c** | y | ? | ? | ? | ? | ? | ? | ? | ? | b |
    | **e** | y | ? | ? | ? | ? | ? | ? | ? | ? | b |
    | **2** | y | a | a | a | a | a | a | a | a | a |
  * free_end_gaps_sequence1_leading = true: means that we can start somewhere in the first row (set x = 0)
  * free_end_gaps_sequence2_leading = true: means that we can start somewhere in the first column (set y = 0)
  * free_end_gaps_sequence1_trailing = true: search optimum in the last row
  * free_end_gaps_sequence2_trailing = true: search optimum in the last column (can be done in extra O(n/w) steps; maybe we could have a smarter algorithm for this, since it is a kind of prefix-sum)

### Acceptance Criteria

- [ ] test 1
- [ ] test 2
- [ ] test 3

### Tasks

 

- [ ] Find out if two sequences can be internally swapped, without that the user sees this swap (within the edit_distance).

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
