### ISSUE TITLE
Rename scoring_scheme concept to scoring_scheme_for to adhere standard's concept naming rules

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#196]
### Description 

Follow-up on https://github.com/seqan/seqan3/pull/2027#pullrequestreview-466587635.
For concepts that require additional template arguments the standard introduced concept names ending with a preposition, e.g. `same_as` or `sized_sentinel_for`. To adhere this naming scheme we should rename the scoring scheme concept to scoring_scheme_for as it expresses that a type models scoring scheme if it works for the given alphabet types.

### Tasks

 

- [ ] rename all instances of seqan3::scoring_scheme to seqan3::scoring_scheme_for

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by rrahn** [comment]
fixed by seqan/seqan3#2063
