### ISSUE TITLE
Fix broken/wrong cppreference links

### ISSUE THREAD

**Issue by eseiler** [seqan/product_backlog#197]
### Description 

We have quite a few broken cppreference links (mostly from before concepts / cpp20 was fixed).

We can check with (my simple script, run from directory containing the seqan3 directory):

```bash
for URL in $(grep -ohr "https://en.cppreference.com[^\) \"]*" seqan3)
do
  CONTENT="$(curl -s $URL)"
  if ! (( $(echo $CONTENT | grep -c "There is currently no text in this page.") == 0 ))
  then
    echo "Link BROKE: " $URL
  else
    if ! (( $(echo $CONTENT | grep -c "has been moved") == 0 ))
    then
      echo "Link MOVED: " $URL
    else
      echo "Link OK   : " $URL
    fi
  fi
  sleep 2s
done
```

This yields a number of broken/moved links.

### Acceptance Criteria

- [ ] Script reports no broken links

### Tasks

 

* Search for above broken links in code base
* Look at the context and search for fitting cppreference link; e.g. `https://en.cppreference.com/w/cpp/named_req/SequenceContainer` fits quite good where `https://en.cppreference.com/w/cpp/concept/SequenceConcept` was used
* After replacing all links, run script again to make sure

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by smehringer** [comment]
Fixed by  seqan/seqan3#2042
