### ISSUE TITLE
Introduce seqan3/std/bit and deprecate most of seqan3/core/bit_manipulation.hpp

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#199]
### Description 

Since c++20 we have new constexpr functions for bit_manipulation (see https://en.cppreference.com/w/cpp/header/bit). We should deprecate our functions in favour for the std ones.

- [ ] `seqan3::detail::sizeof_bits<int8_t>` -> seems to have no std:: alternative?
  * The standard uses [`std::numeric_limits<unsigned_t>::digits`](https://en.cppreference.com/w/cpp/types/numeric_limits/digits) for unsigned types
  * **NOTE:** This is not equivalent for signed types, because they have `int | CHAR_BIT*sizeof(int)-1`
- [x] `seqan3::detail::is_power_of_two(1)` -> `std::has_single_bit(1)`
- [x] `seqan3::detail::next_power_of_two(3)` -> `std::bit_ceil(3)`
- [x] `seqan3::detail::most_significant_bit_set<unsigned_t>(0b0111)` -> `std::bit_width`
  * NOTE: the std version is off by one and defines it as
  * `std::numeric_limits<T>::digits - std::countl_zero(x);`
  * we define it as `std::numeric_limits<T>::digits - std::countl_zero(x) - 1;`
  * This is the same as `floor(log2(x))  + 1`
- [x] `seqan3::detail::count_leading_zeros` -> `std::countl_zero`
- [x] `seqan3::detail::count_trailing_zeros` -> `std::countr_zero`
- [x] `seqan3::detail::popcount` -> `std::popcount`
- [ ] `seqan3::detail::to_little_endian` -> seems to have no std:: alternative?

#### External dependencies

* [ ] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=97759

### Acceptance Criteria

- [ ] test 1
- [ ] test 2
- [ ] test 3

### Tasks

 

- [ ] task 1
- [ ] task 2
- [ ] task 3

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by marehr** [comment]
I created a performance ticket https://gcc.gnu.org/bugzilla/show_bug.cgi?id=97759

**Comment by smehringer** [comment]
@marehr is this done, now that the PR seqan/seqan3#2292 was merged?
