### ISSUE TITLE
Add doxygen support for API documentation and the tutorials

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#2]
### Description

In order to make it easier to maintain an application of another developer a proper API documentation is essential. Also a nice tutorial explaining the tool and it's usage are good for the user of this application.

### Acceptance criteria

- [x] doxygen is incoroporated in the cmake scaffold
- [x] the developer can built the documentation via a make target

### Tasks

- [x] Create a doxygen config file and add the doxygen generation to CMake as a target.
- [x] Document the code of the application template
- [ ] Write a tutorial how to use the app and explain the options (e.g. their combinability), constraints on input files etc.

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
