### ISSUE TITLE
Port Lambda's search engine to use EPR dictionaries within SeqAn3/SDSL

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#20]
### Description 

Lambda uses the EPR dictionaries and the search interface of SeqAn3.

### Acceptance Criteria

- [ ] The performance with the SeqAn3-EPR is at most 10% slower than with the index and search of SeqAn2.
- [ ] Lambda runs sucessfully on all test cases.

### Tasks

 

- [ ] Update lambda to use SeqAn3 EPR dictionary

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by smehringer** [comment]
This is outdated because lambda is now using the implementation of @SGSSGene
