### ISSUE TITLE
[Argument Parser] Follow up: Document POSIX conventions that are implemented in the argument parser

### ISSUE THREAD

**Issue by smehringer** [seqan/product_backlog#201]
### Description 

This is a follow up of https://github.com/seqan/seqan3/pull/1859#discussion_r481098752. 
We follow the official [POSIX conventions](http://www.iitk.ac.in/esc101/05Aug/tutorial/essential/attributes/_posix.html) when parsing the command line. We should still document them and show the usage. For example, one might not know that `--` terminates the options and signals that only position option arguments follow (enabling the user to use e.g. `-f` as an argument without it being misinterpreted as an option identifier).

### Tasks

- [ ] Search the seqan3::argument_parser documentation and the tutorial for mentionings of POSIX conventions 
- [ ] Fill in missing documentation

### Definition of Done

- [ ] API documentation added
- [ ] Tutorial/teaching material added
