### ISSUE TITLE
[Alignment] Vectorised alignment with protein sequences

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#206]
### Description 

For various applications including lambda we need fast vectorised protein sequence alignment such that the overall runtime of these applications that heavily use sequence alignments is reduced. The implemented feature should be at least as fast as SeqAn2. We also want a special version that uses profile scores to speed up the alignment computation.

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/1529364/92575810-0fef3e00-f289-11ea-8d1d-acafabe29939.png">

### Tasks
- [ ] microbenchmarks
- [ ] macrobenchmarks
- [ ] simd score matrix using gather operation
- [ ] simd score matrix using profile score
- [ ] choose alignment between gather and profile implementation based on input sequences
- [ ] extend the computation to all configurations (trace, begin/end positions, banded etc.)
- [ ] integrate it into lambda
