### ISSUE TITLE
Micobenchmark for vectorised protein sequence alignment

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#207]
### Description 

As the developer of the vectorised protein sequence alignment I want microbenchmarks so I can evaluate the current performance of the module in comparison to SeqAn2 and to evaluate if the implemented features do boost the performance.

### Acceptance Criteria

- [ ] microbenchmark for the score computation using protein sequences in simd mode
- [ ] comparison to SeqAn2 is possible

### Tasks

 

- [ ] Add tests for global alignment with protein sequences.
- [ ] Add microbenchmark for seqan3 
- [ ] Add microbenchmark for seqan2 

### Definition of Done

- [ ] Implementation and design approved
