### ISSUE TITLE
[Alignment] Macrobenchmark for protein sequence alignment

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#208]
### Description 

To market the library we want to compare the seqan3 vectorised alignment against other implementations so we can provide useful hints to the community of why they should use SeqAn rather then other solutions. One of the crucial points would be a better performance while using easier interfaces.

### Acceptance Criteria

- [ ] Different benchmark scenarios can be evaluated against other libraries.

### Tasks

 

- [ ] Provide a test case using a simple protein database search (BLAST replacement without prefiltering).
- [ ] Provide a test case computing all pairwise alignments for a given set of sequences.
- [ ] Add code to evaluate Parasail
- [ ] Add code to evaluate AnySeq?
- [ ] Add code to evaluate ksw
- [ ] Add code to evaluate swipe and respective library implementations

### Definition of Done

- [ ] Implementation and design approved
- [ ] Changelog entry added
