### ISSUE TITLE
[Alignment] Simd protein score matrix with gather operation

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#209]
### Description 

Update the current score matrix for protein sequences to use efficient gather operations to improve the performance of the protein sequence alignment.

### Acceptance Criteria

- [ ] Calling score on the matrix based simd scoring scheme uses efficient simd instructions.
- [ ] The score method gets two vectors from which it generates the memory address offsets to 
- [ ] When using a linearlised memory model for the score matrix the column index can be pre-computed once per column (only do one multiplication per column). 

### Tasks

 

- [ ] provide microbenchmarks to check if auto-vectorisation can be used in favor of specific instructions for different simd implementations.
- [ ] provide microbenchmark to check if linearlised memory layout is more efficient in the implementation than a nested array (current protein score structure)
- [ ] implement and test the most efficient strategy for gathering the scores from the score matrix based scoring scheme.
- [ ] add version for SSE4
- [ ] add version for AVX2

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Changelog entry added
