### ISSUE TITLE
[Alignment] Simd profile score

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#210]
### Description 

For protein database searches I want a simd profile scoring scheme so I can query a single sequence against a set of sequences more efficiently than using a gather operation.

### Acceptance Criteria

- [ ] The profile score can be used when the second sequence is a single sequence.
- [ ] Add early tests for checking on the performance with the profile generation vs the gather operation.

### Tasks

 

- [ ] Add a simd profile scoring scheme that gets a profile and a single character
- [ ] Add a new score matrix policy that allows to convert the sequence vector of the first sequences to a profile score
- [ ] Make a specific simd profile scoring scheme that implements a score function using a profile and a single charcater
- [ ] The profile score must be able to expose its internal matrix for the score matrix policy to convert the character to a profile
- [ ] Update the alignment code to call specific conversion to profile score. 
- [ ] add profile computation for SSE4
- [ ] add profile computation for AVX2
- [ ] add profile computation for AVX512

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
