### ISSUE TITLE
[Alignment] Extend pairwise alignment interface to distinguish different user inputs

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#211]
### Description 

As an implementer for the vectorised sequence alignment I want to be able to distinguish the user input so I can dispatch to the most effcient implementation inside of the alignment configuration. Concrete, in vectorised mode I need to evaluate which scoring strategy to use, i.e. using simple simd score (match/mismatch only and many-vs-many), using gather operation (many-vs-many with matrix based scoring scheme), or using a profile score (one-vs-many).

### Acceptance Criteria

- [ ] The alignment configuration can differentiate between the different modes.
- [ ] The sequence ids are preserved accordingly and can be customised by the user.
- [ ] The most efficient implementation is used based on the given input. 

### Tasks

 

- [ ] Design and implement the new pairwise alignment design.
- [ ] Adapt the tests and documentation

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
