### ISSUE TITLE
[Alignment] Select simd scoring scheme implementation dynamically

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#212]
### Description 

As a user I want to provide my own scoring scheme and I want the alignment to configure the correct scoring scheme for the simd execution so I can run the correct alignment with the best alignment performance possible.

### Acceptance Criteria

- [ ] If the user provides a simple score where only match and mismatch are different between the symbols the simple simd scoring scheme should  be used.
- [ ] It user provides a scoring matrix the simd-ified scoring scheme using gather respectively profile score should be used.
- [ ] The selection of the internal simd scoring scheme does not depend on the seqan specific types anymore.
- [ ] The user can provide its own scoring scheme and call the alignment accordingly.

### Tasks

 

- [ ] Add a configuration step to check if the scoring scheme given by the user can be modeled with a simple scoring scheme or requires the advanced scoring matrix scheme using gather/profile scores.
- [ ] Test the different inputs: nucleotide_scoring_scheme simple, nucleotide_scoring_scheme matrix, aminoacid_scoring_scheme matrix, user scheme simple and user scheme matrix.
- [ ] Add a snippet in the cookbook to write your own scoring scheme and use it inside of the alignment.

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
