### ISSUE TITLE
[DOC, TEST] Consistent use of `benchmark::DoNotOptimize`

### ISSUE THREAD

**Issue by smehringer** [seqan/product_backlog#214]
### Description 

Currently the benchmarks are not consistent in how we use `benchmark::DoNotOptimize`.

Google Benchmark states:

> DoNotOptimize(<expr>) forces the result of <expr> to be stored in either memory or a register. For GNU based compilers it acts as read/write barrier for global memory. More specifically, it forces the compiler to flush pending writes to memory and reload any other values as necessary.

>  Note that DoNotOptimize(<expr>) does not prevent optimizations on <expr> in any way. <expr> may even be removed entirely when the result is already known.

But they themselves often still avoid wrapping the main algorithm to execute with `benchmark::DoNotOptimize`.

So instead of

```cpp
    size_t sum{};
    for (auto _ : state)
    {
        auto results = search(reads, index, cfg);
        benchmark::DoNotOptimize(sum += std::ranges::distance(results));
    }
```
we should do
```cpp
    size_t sum{};
    for (auto _ : state)
    {
        auto results = search(reads, index, cfg);
        sum += std::ranges::distance(results);
    }
    benchmark::DoNotOptimize(sum);
```
Just to be very clear that `benchmark::DoNotOptimize` does not affect performance.

See https://github.com/seqan/seqan3/pull/2112 for an example on how this might affect benchmark times.

We should document this in the wiki and make benchmarks consistent.

### Tasks

- [ ] Write a wiki entry on this issue and link it on the main wiki page
- [ ] Go through existing benchmarks and make them consistent in not wrapping "the main task to execute in `DoNotOptimize`" but a variable outside the loop.

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
