### ISSUE TITLE
Left-over for 3.0.2 release with configurations

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#217]
### Description 
Last things to do in the configuration design before the release.

### Tasks

 

* [x] move configuration stuff in right namespace (align_cfg::detail should be used consistently)
* [x] final documentation sweep
* [x] `pipeable_config_element` should be changed (before it contained the value, now the configuration element itself contains the value)
* [x] Make member types non strong-types.

#### Check design for default constructable configs and what the defaults are: 

Here is a look and feel including the resolution for the defaults to set: https://gist.github.com/rrahn/00bb5d17e37584732a30ccc7d56ccf9b

##### Alignment
* [x] band
* [x] debug
* [x] edit
* [x] gap_cost_affine
* [x] method
* [x] min_score
* [x] on_result
* [x] output
* [x] parallel
* [x] result_type
* [x] score_type
* [x] scoring_scheme
* [x] vectorised

##### Search

* [x] hit
* [x] max_error
* [x] on_result
* [x] output
* [x] parallel
* [x] result_type

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by rrahn** [comment]
This is done from my POV.
