### ISSUE TITLE
Index construction

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#22]
### Tasks

- [ ] Sentinel free implementation in SDSL
- [ ] Generalised suffix array construction
- [ ] Supply suffix array construction algorithm from outside
- [ ] Use Index configuration object to allow configuration of SACA
- [ ] Generalised SA without sentinels in SDSL -> Adapt libsufsort
- [ ] Add parallel libsufsort to SDSL as construction algorithm
- [ ] Configuration communication between SDSL (construction config builder) and SeqAn?
- [ ] Memory Mapping in SDSL for SACA?

**Comment by MitraDarja** [comment]
Once we have improved the fm index, we should compare it to this tool: https://www.biorxiv.org/content/biorxiv/early/2021/01/14/2021.01.12.426474.full.pdf

**Comment by eseiler** [comment]
Duplicate of https://github.com/seqan/product_backlog/issues/236
