### ISSUE TITLE
[Alignment] Add a documentation for parallel and vectorised alignment interface

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#229]
### Description 

As a reader of the tutorials I want to learn more about the accelerated alignment so I can use parallel and vectorised alignments in my application.

### Acceptance Criteria

- [ ] The reader understands how to accelerate the alignments using multi-threading
- [ ] The reader understands how to accelerate the alignments using vectorisation
- [ ] The reader understands how to use the continuation interface for the alignment algorithm.

### Tasks

 

- [ ] Extend the alignment tutorial by a proper section for:
   - [ ] parallel
   - [ ] vectorised
   - [ ] continuation

### Definition of Done

- [ ] Tutorial/teaching material added
- [ ] Changelog entry added
