### ISSUE TITLE
Header tests should catch self-include

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#232]
### Description 

Header tests should circular includes

For example, we have

```c++
// seqan3/search/fm_index/bi_fm_index_cursor.hpp
#pragma once

#include <array>

#include <sdsl/suffix_trees.hpp>

#include <seqan3/alphabet/adaptation/char.hpp>
#include <seqan3/alphabet/adaptation/uint.hpp>
#include <seqan3/alphabet/concept.hpp>
#include <seqan3/core/type_traits/range.hpp>
#include <seqan3/range/views/slice.hpp>
#include <seqan3/search/fm_index/bi_fm_index.hpp>
```

includes `bi_fm_index.hpp`

```c++
// seqan3/search/fm_index/bi_fm_index.hpp
#pragma once

#include <utility>

#include <seqan3/core/type_traits/range.hpp>
#include <seqan3/std/filesystem>
#include <seqan3/range/views/persist.hpp>
#include <seqan3/search/fm_index/fm_index.hpp>
#include <seqan3/search/fm_index/bi_fm_index_cursor.hpp>
#include <seqan3/std/ranges>
```

so `bi_fm_index_cursor` -> `bi_fm_index` -> `bi_fm_index_cursor`, a self-include (cycle).

We don't want to have cyclic includes, since they make automatic (like creduce or cvise) or manual code reduction harder than necessary.

### Acceptance Criteria

- [ ] Change the header tests, such that self-includes will be detected.

### Tasks

 

- [ ] Change the header tests, such that self-includes will be detected.

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
