### ISSUE TITLE
[Argument Parser] Remove restriction for `-` in subparser app name

### ISSUE THREAD

**Issue by smehringer** [seqan/product_backlog#234]
### Description 

See [discussion](https://github.com/seqan/seqan3/pull/2179#discussion_r501622686) in original PR.

A subparser's app name is set internally to `[TOPLEVELNAME]-[SUBNAME]` which, when implementing, made me (or someone) require that the `[SUBNAME]` did not contain any dashes (`-`). But this restriction seems too strict as nothing happens if multiple dashed are in the name of the parser. 

When working on this, take a close look on the update notifications though but I think sub parsers disable update notifications anyway so this should not be a problem.

### Acceptance Criteria
- [ ] You can add subparser with a name that contains `-`

### Tasks

- [ ] Change the restriction from the construction of the argument parser to use the normal app name regex
- [ ] Remove the specil regex member
- [ ] Add a test with a subparser that has a dash in it and remove the test that throws on this occasion.

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by marehr** [comment]
I think we did this to disallow security related problems? Don't we pass that name to `wget`?

**Comment by smehringer** [comment]
> I think we did this to disallow security related problems? Don't we pass that name to `wget`?

In general yes, we disallowed all characters but certain ones for security issues. This ticket only concerns the dash `-`. We currently allow dashes in the parser name but not in the subparser name. This is only to lift this extra restriction on the subparser name.
I am pretty sure that the subparsers are not inlcuded in update notifications anyway but that's why I added the note, to check twize.
