### ISSUE TITLE
[Search] SDSL Index improvements and Index construction ideas

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#236]
### Description 

Currently, the SeqAn way of handling sequences does not fit well with SDSL index constructions.
The SeqAn3 alphabets are represented by their ranks and start with rank 0. The SDSL assumes that texts are based on chars and does not allow any text with the value `\0`, which is used internally for the sentinel.
These changes might affect the SDSL stable API and are thus relevant for the 3.1 release.

related:
 * Add support for generalised CSAs in the sdsl, such that we can index text collections without artificially adding a sentinel character to our indices. https://github.com/seqan/product_backlog/issues/24
 * Add a sentinel-free implementation of the CSA to the SDSL such that we don't have to transform the text by increasing the ranks by one and increase the performance. https://github.com/seqan/product_backlog/issues/23
 * Provide mechanism to allow specification of the SACA algorithm from outside in order to have a better control over the index construction for different use cases. https://github.com/seqan/product_backlog/issues/25

### Index construction Tasks

- [ ] Sentinel free implementation in SDSL
- [ ] Generalised suffix array construction
- [ ] Supply suffix array construction algorithm from outside
- [ ] Use Index configuration object to allow configuration of SACA
- [ ] Generalised SA without sentinels in SDSL -> Adapt libsufsort
- [ ] Add parallel libsufsort to SDSL as construction algorithm
- [ ] Configuration communication between SDSL (construction config builder) and SeqAn?
- [ ] Memory Mapping in SDSL for SACA?

### Tasks

<details><summary>Definition of Done</summary>
<p>

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

</p>
</details>

**Comment by smehringer** [comment]
From #22

### Tasks

- [ ] Sentinel free implementation in SDSL
- [ ] Generalised suffix array construction
- [ ] Supply suffix array construction algorithm from outside
- [ ] Use Index configuration object to allow configuration of SACA
- [ ] Generalised SA without sentinels in SDSL -> Adapt libsufsort
- [ ] Add parallel libsufsort to SDSL as construction algorithm
- [ ] Configuration communication between SDSL (construction config builder) and SeqAn?
- [ ] Memory Mapping in SDSL for SACA?
