### ISSUE TITLE
!! C++20 like views

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#238]
### Description !!!

Make all views as similar as possible to the C++20 standard, since this gives us the highest chance that they will work together in composable view definitions and are stable for the future. It is also a good practice, since the standard documents how they are implemented and every developer can follow these guidelines.

---

Already discussed:

* [x] https://github.com/seqan/product_backlog/issues/49
  **Core meeting 2020-12-07**: Everything is done already
* [x] All views shall have explicit constructors https://github.com/seqan/seqan3/issues/941 still valid?
  **Core meeting 2020-12-07:** Yes, they should be explicit if only one argument is given, e.g. http://eel.is/c++draft/range.join which does the same. 
  TODO: Make an issue for this. (Old issue is being re-used; I reopened)
* [x] change behaviour of take/drop according to P1739/P1664
  **Core meeting 2020-12-07:**
  Declare take/drop view as experimental; The reason is that the standard take/drop view seems to have the same properties.
  TODO: This should be benchmarked and if there is a regression this should be backported to the standard.
* [x] view::persist should downgrage ContiguousIterator/Range to RandomAccessIterator/Range because contiguous suggests you can directly access the memory whose lifetime might end, if not access via view::persist. Should we still offer view::persist or remove it entirely 
   **Core meeting 2020-12-07**: We remove this as discussed already here https://github.com/orgs/seqan/projects/4#card-41487782
* [x] Give up our own definitions in <concepts> once  ericniebler/range-v3#1322 is resolved. Still valid?
  **Core meeting 2020-12-07**: This is done, see: https://github.com/seqan/product_backlog/issues/190
* [x] some changes to `views::pairwise_combine`:
    - rename to `views::all_pairs` -> we decided against this
    - make view factory instead of adaptor
    - have single param interface (like now)
    - add two-param interface where all pairs between the sets are generated
    - change the tuple-type to be `(seq1, seq2, id1, id2)` where id1 and id2 are numbers that indicate the original IDs of the sequences

### Tasks

<details><summary>Definition of Done</summary>
<p>

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

</p>
</details>

**Comment by marehr** [comment]
2021-04-16 Core Meeting

`views::pairwise_combine` has a slight preferential over `views::all_pairs`, we'll keep the `pairwise_combine` name.

[Wiki](https://en.wikipedia.org/wiki/Combination) calls it `k-combination`, so in this case `2-combination` which is closer to `pairwise_combine`.

**Comment by rrahn** [comment]
This came from @h-2. I just transferred it into the new issue system.

**Comment by marehr** [comment]
From my POV done; open a new issue if needed
