### ISSUE TITLE
[I/O] General I/O related issues

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#241]
### General
* https://github.com/seqan/product_backlog/issues/242
* move `views::istreambuf` to the IO module
* `views::istreambuf` should be moved to `io/stream` from the ranges module.
* remove ostream_iterator and ostreambuf_iterator, use from std module instead.
* `output_stream_over` is a wrong name, because we are not checking if the second argument is the value type of the stream. It can be an arbitrary type as long as it can be streamable...
I am not sure we need these concepts at all. One should just not take constrained template parameters of stream, just take istream or ostream or whatever directly. It's all virtual in any case.

### Sequence IO

* Add [Sequence IO] BAM support (see https://github.com/seqan/seqan3/pull/1470)
* Improve FastQ I/O 
* The field types in `sequence_file_output` never undergo any type checking, e.g. the seq field should at least be required to be an input range over an alphabet type. -> sequence concept

### SAM/BAM  IO
- [x] BAM unknown reference name https://github.com/seqan/seqan3/issues/1201
* [IO] Possible improvements for the SAM/BAM format parsing: https://github.com/seqan/product_backlog/issues/226
* [IO] SAM/BAM performance: https://github.com/seqan/product_backlog/issues/227
* What happens on PPC with bam tests when the byte order should be converted to big endian.

### Tasks

<details><summary>Definition of Done</summary>
<p>

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

</p>
</details>
