### ISSUE TITLE
!!! Split out utility functionality from core

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#244]
### Description

Split out the utility functionality from the core such that everything that is part of core is not part of the stable API and is subject to change at all time. The core provides deep functionality that is used by multiple modules. It does not have any dependencies to other modules. The utility module is a more a library inside of a library and should also be self-contained, i.e. it does not have any dependencies to any other module (also not core?).

What is core? What is utility?

disucssed:
* [x] Core / Utility Split: https://github.com/seqan/product_backlog/issues/160
   * ~~Put configuration stuff into a subdirectory within core/algorithm/configuration~~

* [x] Module  dependencies, Hannes Proposal: -> created issue https://github.com/seqan/product_backlog/issues/387
    We should establish these rules:
    - modules may not depend on each other, with the following exceptions:
    - all except std and contrib may depend on core and detail
    - alignment, search and i/o may depend on alphabet and range but not on each other
       - Current exception is the debug_stream. 
       - Algorithms should depend on alphabet module only by include the alphabet concepts
       - Some data structures with default settings may include specific alphabets, e.g. in I/O or scoring scheme.
    - **Resolution (2020-11-10)**: we don't want to have inter-module dependencies except for the points listed above. 
        - TODO: make sure that search/alignment/io adhere to these rules.
        - TODO: make ticket out of this.

* [x] Handling of "bit-patterns"  is inconsistent. The `dynamic_bitset` takes string literals`"0101"` while the shape gets an extra strong type that is initialised with a numeric literal in binary notation: `bin_literal{0b10101}`. -> created issue https://github.com/seqan/product_backlog/issues/388
    I suggest the following:
    1. rename `bin_literal` to `bits`
    2. give `bits` a constructor from number and one from string_view.
    3. introduce `0b101_bits` and `"101"_bits` as user defined literals of type `bits`.
    4. Use `bits` in the constructors of dynamic_bitset and shape.
    *Thoughts: 2020-11-10*
        * shape gets strong_type for `ungapped{5}` or `bin_literal{0b10101}` -> "101"_bits 
        * we have already a literal: `0b101011_shape` -> shape // static
        * can we have `10_ungapped_shape` -> shape ungapped of size 10? not possible as runtime parameter
        * seqan2 has: dynamic_gapped_shape, dynamic_ungapped_shape, static_gapped_shape and static_ungapped_shape
        * extension of shapes as static/dynamic, idea: use first class templates using mechanism like in span.
            * **RESOLUTION:** we need more use cases: document it as NO_API/Experimental must not be stable for 3.1 *TODO:* which dependencies are affected.   

* Make call of get in seqan3::configuration consistent https://github.com/seqan/product_backlog/issues/195 -> using get CP
  * **RESOLUTION:** https://github.com/seqan/product_backlog/issues/195#issuecomment-727897166

* [x] `seqan3::is_in_alphabet<>` (char operations) can be removed, because we have `seqan3::char_is_valid_for<>` (alphabet module) => No!!! Because it does not support the same functionality like combining them with || operator. But it could be implemented by means of the other.
  * **RESOLUTION:** https://github.com/seqan/product_backlog/issues/244#issuecomment-727907210
  * Issue: https://github.com/seqan/product_backlog/issues/262
* [x] type_list_specialisation is a weird name. before the great concept rename it was called `TypeList`, so snake casing it would have been a name conflict. Are there other concept names that had this conflict? [CARD](https://github.com/orgs/seqan/projects/4#card-27343940)
  * **RESOLUTION:** https://github.com/seqan/product_backlog/issues/244#issuecomment-727907210
  * Issue: https://github.com/seqan/product_backlog/issues/259
* [x] the algorithm result generator range returned by algorithms should be a (move-only) range.
  * **RESOLUTION:** https://github.com/seqan/product_backlog/issues/244#issuecomment-727907210
  * Issue: https://github.com/seqan/product_backlog/issues/263
    * from alignment/search: already are
    * async_input_buffer view
    * single_pass_input view
---
needs discussion:

* [x] add_enum_bitwise_operators issues? https://github.com/seqan/product_backlog/issues/260
    * Remove the `add_enum_bitwise_operators` from the public API documentation using `//cond DEV`
    * Document the bitwise functionality in each enum that uses  `add_enum_bitwise_operators`
    * Pull `add_enum_bitwise_operators` into the detail namespace such that it works for enums that are declared    in the detail namespace
    * Do the same for strong types!
SPIKE?

### Tasks

<details><summary>Definition of Done</summary>
<p>

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

</p>
</details>

**Comment by rrahn** [comment]
#### Core Meeting 16.11.2020 - Resolution

* `seqan3::is_in_alphabet<>` (char operations) can be removed,
Yes, we remove it!

We checked the usage of `seqan3::is_in_alphabet<>` in the code and there is only one place where we negate the result but no one is using the message feature. Hence, it can also be replaced by the `char_is_valid_for` on all these places. This also removes the dependency to the alphabet module. 

* type_list_specialisation is a weird name.
We remove this entirely and use a generic concept definition that resolves to `seqan3::detail::is_type_specialisation_of_v` with the name `seqan3::detail::template_specialisation_of`.
Also do we need to have a concept for `seqan3::detail::is_value_specialisation_of_v`? The name is not accurate, since it is also a type specialisation just with non-type template arguments.
We might not have any use case for the `is_value_specialisation_of_v` and thus do not need an additional concept for this.
Some usages are not correct, e.g. `fm_index_specialisation` and `aphabet_tuple_base_specialisation` as they define additional requirements. These need dedicated concepts.

* the algorithm result generator range returned by algorithms should be a (move-only) range

  We decided that the following views should be move-only:

  *  from alignment/search: already are
  *  async_input_buffer view
  *  single_pass_input view

**Comment by marehr** [comment]
The general thing is done, left-overs were made issues.
