### ISSUE TITLE
[Sharg] File extension handling in file validator

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#245]
### Description 

For my application I want an easy way to specify the list of extensions that are checked by the in/out file validator such that I do not end up having different extensions set in the validator and extensions set in the file.

This change greatly depends on the way how we going to pursue the I/O refactoring and should be kept in mind.
The following issues are related to this:
- [ ] change way of providing custom file extensions to the argument parser.
- [ ] Should the validator types be semiregular?
- [x] ArgParser: extension containing . accepted, but fail: https://github.com/seqan/seqan3/issues/1176
- [ ] Sequence file input validator does not accept gzipped files: seqan/sharg-parser#77

### Tasks

<details><summary>Definition of Done</summary>
<p>

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

</p>
</details>
