### ISSUE TITLE
General alphabet cleanup

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#248]
### Description

* [ ] nucleotide_base converting constructor is under-constrained. Should require constexpr_writable_alphabet and have non-constexpr fallback.
* [ ] `convert_through_char_representation` is underconstrained, should require constexpr_writable_alphabet.
* [x] `convert_through_char_representation` has SeqAn2-style wrong order of parameters (first out than in) (fixed by https://github.com/seqan/seqan3/pull/2870).
* [ ] make union_composition require the same char_type on alternatives
* [x] alphabet test: remove `#include <.../all.hpp>` calls and replace them with the minimal needed includes, like in https://github.com/seqan/seqan3/blob/53cce95d0743d453b73e6ece549a86e00dce7552/test/unit/alphabet/mask/mask_test.cpp#L11 and https://github.com/seqan/seqan3/blob/53cce95d0743d453b73e6ece549a86e00dce7552/test/unit/alphabet/nucleotide/nucleotide_conversion_integration_test.cpp#L12

### Tasks

<details><summary>Definition of Done</summary>
<p>

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

</p>
</details>

**Comment by marehr** [comment]
Moved to Release 3.2.0 and moved listed parts to https://github.com/seqan/product_backlog/issues/389. That means https://github.com/seqan/product_backlog/issues/389 supersedes this issue now.
