### ISSUE TITLE
Test naming scheme

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#257]
#### Not matching header name

We have a couple of files that do not follow our test naming scheme, which is

* a header [/include/seqan3]/module/submodule/some_class.hpp has a 
* corresponding test [/test/unit]/module/submodule/some_class_test.cpp

One easy example is that `views/view_as_const_test.cpp` should be named `views/as_const_test.cpp`, since the header is named `views/as_const.hpp`.

#### Split test cases

But, there are some other examples where we don't have a rule for a naming in place.

For example tests that needed to be split, because otherwise compile time would be way too high:

* alignment/pairwise/global_affine_banded_test.cpp
* alignment/pairwise/global_affine_banded_collection_simd_test.cpp
* alignment/pairwise/global_affine_unbanded_test.cpp
* alignment/pairwise/global_affine_unbanded_aa27_test.cpp
* alignment/pairwise/global_affine_unbanded_callback_test.cpp
* alignment/pairwise/global_affine_unbanded_collection_test.cpp
* alignment/pairwise/global_affine_unbanded_collection_callback_test.cpp
* alignment/pairwise/global_affine_unbanded_collection_simd_test.cpp
* alignment/pairwise/global_affine_unbanded_collection_simd_aa27_test.cpp
* alignment/pairwise/local_affine_banded_test.cpp
* alignment/pairwise/local_affine_unbanded_test.cpp

It is not clear whether these tests test the generic alignment algorithm directly or all those cases via the general align_pairwise interface. In fact, they test `align_pairwise` for specific alignment fixtures.

My proposal is to rename those tests to:

* align_pairwise_test.global.affine.banded.dna4.cpp
* align_pairwise_test.global.affine.banded.collection.simd.dna4.cpp
* align_pairwise_test.global.affine.unbanded.dna4.cpp
* align_pairwise_test.global.affine.unbanded.aa27.cpp
* align_pairwise_test.global.affine.unbanded.callback.dna4.cpp
* align_pairwise_test.global.affine.unbanded.collection.dna4.cpp
* align_pairwise_test.global.affine.unbanded.collection.callback.dna4.cpp
* align_pairwise_test.global.affine.unbanded.collection.simd.dna4.cpp
* align_pairwise_test.global.affine.unbanded.collection.simd.aa27.cpp
* align_pairwise_test.local.affine.banded.dna4.cpp
* align_pairwise_test.local.affine.unbanded.dna4.cpp

This makes it cleat that all those tests belong to the `align_pairwise.hpp` header.

Another example would be

* search/fm_index/bi_fm_index_aa27_test.cpp -> search/fm_index/bi_fm_index_test.aa27.cpp
* search/fm_index/bi_fm_index_char_test.cpp -> search/fm_index/bi_fm_index_test.char.cpp
* search/fm_index/bi_fm_index_dna4_test.cpp -> search/fm_index/bi_fm_index_test.dna4.cpp

This means we introduce a new naming scheme `<header_name>_test.<subtest>.cpp`.

Note: <subtest> could simply be the type for which a test template is instantiated.

#### Problem with unique test target names

We have sometime `<module>_concept_test.cpp` for `module/concept.hpp`, e.g.
* `io/concept.hpp` and `alphabet/concept.hpp` or
* `std/move.hpp` and `views/move.hpp`.

Here we could two things, first use 
* `concept_test.module.cpp`, e.g. making them always unique, or 
* `concept_test.cpp` and introduce a new cmake syntax for those (rare!) cases: `seqan3_test(concept_test.cpp TARGET module_concept_test`), e.g. really following header implies test name.

### Acceptance Criteria

- [ ] test 1
- [ ] test 2
- [ ] test 3

### Tasks

 

* [ ] view tests, fixed by https://github.com/seqan/seqan3/pull/2238
* [ ] alignment test ...

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
