### ISSUE TITLE
[MISC] Concept name `[...]_specialisation` revision

### ISSUE THREAD

**Issue by smehringer** [seqan/product_backlog#259]
## Description

We cannot have the concept `type_list` because it clashes with the class name, we had a concept called `type_list_specialisation`. This concept name is not very meaningful if not looked at in this specific context and basically just checks `is_type_specialisation_of<mytype, seqan3::type_list>`. 

Therefore we will change the concept naming, s.t. 
* everything that is called `[...]_specialisation` and is just checking  `is_type_specialisation_of_v<mytype, [...]>` will be removed and replaced with the generic concept `seqan3::template_specialisation_of<mytpe, [...]>`.
* everything that is called `[...]_specialisation` and is doing **more** than checking `is_type_specialisation_of_v<mytype, [...]>` will get a more meaningful name then the `_specialisation` suffix.

## Tasks

- [x] Add a new concept called `seqan3::detail::template_specialisation_of` that takes a type as first argument (`mytype`) and a type template as second argument (`[...]`) and simply delegates to `is_type_specialisation_of_v<mytype, [...]>`. (seqan/seqan3#2263)
- [x] Remove the concept `type_list_specialisation<some_type>` and replace it with `seqan3::detail::template_specialisation_of<some_type, seqan3::type_list>` (seqan/seqan3#2267)
- [x] Rename `strong_type_specialisation` to `derived_from_strong_type` (seqan/seqan3#2322)
- [x] Rename `config_element_specialisation` to `config_element` (seqan/seqan3#2322)
- [x] Rename `alphabet_tuple_base_specialisation` to `alphabet_tuple_like` (seqan/seqan3#2322)
- [x] Remove concept `fm_index_cursor_specialisation`and concept `bi_fm_index_cursor_specialisation` and replace occurrences of such with `seqan3::detail::template_specialisation_of<mytype, seqan3::fm_index_cursor>` and `seqan3::detail::template_specialisation_of<mytype, seqan3::bi_fm_index_cursor>` or disjunction of both where they are used. (seqan/seqan3#2339)
- [x] Remove concept `bi_fm_index_specialisation` and replace occurrences of such with seqan3::detail::template_specialisation_of<typename mytype::cursor_type, seqan3::bi_fm_index_cursor> (seqan/seqan3#2348)
- [x] Remove concept `fm_index_specialisation` and replace it with unconstrained templates. (seqan/seqan3#2348)

## Design decisions

NO NEED TO READ THIS FOR THE PERSON WHO IS WORKING ON THIS

Before the great concept rename it was called `TypeList`, so snake casing it would have been a name conflict. Are there other concept names that had this conflict?

---

https://gist.github.com/bad-ed/72d7d1310b988ffd8ea6dc2bd21ffcda

--- 

**Results of discussing it on 2019-11-11, @h-2:**

 * For checking whether something `T` is a specialisation of `foo<>` we often need a shortcut that is defined as `is_type_specialisation_of_v<T, foo>` or semantically equivalent.
 * The name `foo_specialisation` is clear, but not beautiful.
 * If we change it, we should follow concept naming guidelines, i.e. it should be a noun.
 * Independent of this we might want a concept for `type_specialisation_of` for the generic case. But depending on the resolution of certain NB comments, concepts with incomplete types may become ill-formed.

**Resolution 2020-16-11 from Core meeting:**

We remove this entirely and use a generic concept definition that resolves to `seqan3::detail::is_type_specialisation_of_v` with the name `seqan3::detail::template_specialisation_of`.
Also do we need to have a concept for `seqan3::detail::is_value_specialisation_of_v`? The name is not accurate, since it is also a type specialisation just with non-type template arguments.
We might not have any use case for the is_value_specialisation_of_v and thus do not need an additional concept for this.
Some usages are not correct, e.g. `fm_index_specialisation` and `aphabet_tuple_base_specialisation` as they define additional requirements. These need dedicated concepts.

**Outstanding decisions/proposals:**

What about the naming of the following our current concept that are suffixed with `_specialisation`.
They all imply something like "behaves like this", namely they describe an *Abstraction*. 

Nice wrap-up about concept naming and its issues: http://open-std.org/JTC1/SC22/WG21/docs/papers/2019/p1851r0.html

We are mostly in case 4 or 5 which has no great solution in the standard, except being creative. Some examples:
* `std::iterator` is already a class name, so the concept is called `std::input_or_output_iterator`
*  `std::view` was a namespace name, so the namespace was renamed to `std::views` so the concept can be called `std::view`
* `std::tuple` is already a class name, so the concept is named `std:tuple_like`.

### Resolution Core Meeting - 2020-11-18:

* `detail::strong_type_specialisation` 
  We never actually use this concept, **except** for our custom debug_stream overload for our class `strong_type`. This is basically a helper concept to beautify the debug_stream overload error message. The main check is whether the type is derived from the `seqan3::strong_type` class, so the concept will be named `derived_from_strong_type`.
* `detail::config_element_specialisation` 
   Rename it to -> `detail::config_element` (we don't have this name yet :D, the class is called pipeable_config_element) 
* `detail::alphabet_tuple_base_specialisation`
  This is more general than the strong type specialization concept. We will therefore rename it to `detail::alphabet_tuple_like`. The name is close to the concept `std::tuple_like`.

* `fm_index_cursor_specialisation`/`bi_fm_index_cursor_specialisation` 
  Those are concepts are highly specialized and don't really fit into the idea of "describing general requirements". No one will ever write their own cursor to be used in our fm_index (or if so we can still add a concept, but I doubt it). Both concepts are hardly used at all. The only place where it has an actual meaning is in the `seqan3::search_result` describing the type and in the `fm_index_specialisation`/`bi_fm_index_specialisation` concept. It is never used for overload resolution.
  Delete the concept (but keep it for the tests). In the two use cases of the `seqan3::search_result` it can be replaced with `seqan3::detail::template_specialisation_of<..., seqan3::fm_index_cursor> | seqan3::detail::template_specialisation_of<..., seqan3::bi_fm_index_cursor>`. We might want to name this `fm_or_bi_fm_cursor`.
* `fm_index_specialisation`/`bi_fm_index_specialisation` 
  Also highly specialised but they may take part in overload resolution in the `seqan3::search interface`. Remove the concept and reevaluate the need once generic use cases appear. 

* `detail::fields_specialisation` We should wait for this until we know that we keep fields.

**Comment by marehr** [comment]
### 2021-02-01 Core Meeting.

The task for `seqan3::(bi_)fm_index_specialisation` contained an error and corrected the description.

We rediscover our resolution that we want to remove `seqan3::(bi_)fm_index_specialisation` and as replacement check whether the cursor type is a fm_index cursor or bi_fm_index cursor.

**Comment by SGSSGene** [comment]
### 1. Issue:
`bi_fm_index_specialisation` was inheriting from `fm_index_specialisation`. Just checking if cursor is of type `bi_fm_index_cursor` or `fm_index_cursor` doesn't work.

### 1. Resolution:
- check for `bi_fm_index_cursor` if function used to be `bi_fm_index_specialisation`.
- Use unconstrained type if it used to be `fm_index_specialisation`.

### 2. Issue+Resolution:
 - Remove `concept_check`. It is not needed any more, since we are deleting the concept for the fm indices.
 
### 3. Issue+Resolution:
 - There seems to be a left-over `is_bi_fm_index` variable in the unit tests. Check if they can be removed.
