### ISSUE TITLE
Make input_views move-only

### ISSUE THREAD

**Issue by eseiler** [seqan/product_backlog#263]
### Description 

We have a few views that should be move-only:

* `async_input_buffer_view`
* `single_pass_input_view`

The [algorithm and search results](https://github.com/seqan/seqan3/blob/d37ba83a333992a551ec835097e564d8b9a00604/include/seqan3/core/algorithm/algorithm_result_generator_range.hpp#L43) are already move-only views.

### Tasks

- [ ] make `async_input_buffer_view` move-only
- [ ] make `single_pass_input_view` move-only
- [ ] add changelog entry

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Changelog entry added

**Comment by marehr** [comment]
### 2021-01-25 Core Meeting:

As long as we have the range-v3 dependency (they only support copy-only iterators/ranges), we can't really tackle this issue.

We postpone it after resolving https://github.com/seqan/product_backlog/issues/124
