### ISSUE TITLE
Remove unnecessary module dependencies

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#264]
### Description 

Remove inter-module dependencies such that include dependencies are not spread over the modules. This has the benefit that modules can be used more independent, which is also a goal for offering c++20 modules at some point in the future. Another reason are better code structure, easier to track bugs and ICEs.

### Acceptance Criteria

- [ ] The alignment module only depends on utility, core and alphabet and ranges
- [ ] The alphabet module only depends on utility, core and ranges
- [ ] The argument parser module only depends on core and utility
- [ ] The contrib module only depends on core and utility
- [ ] The core module only depends on the utility
- [ ] The io module only depends on core, utility, alphabet and ranges
- [ ] The search module only depends on core, utility, alphabet and ranges
- [ ] The utility module does not depend on any other module (except core/platform.hpp)

### Tasks

 

- [ ] Scan each module and make a list of includes to modules that are not allowed
- [ ] Try to remove these dependencies
- [ ]  if not possible discuss the unresolvable includes with the core team
- [ ] Write a wiki entry in the module structure section describing the dependencies

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by MitraDarja** [comment]
### Alignment
As far as I can see already only depending on utility, core and alphabet and ranges

### Alphabet
As far as I can see already only depending on utility, core and ranges

### Argument Parser

include/seqan3/argument_parser/argument_parser.hpp
- #include <seqan3/io/stream/concept.hpp> 

include/seqan3/argument_parser/auxiliary.hpp
-  #include <seqan3/io/stream/concept.hpp>

include/seqan3/argument_parser/validators.hpp
- #include <seqan3/io/detail/misc.hpp>
- #include <seqan3/io/detail/safe_filesystem_entry.hpp>
- #include <seqan3/range/container/concept.hpp>
- #include <seqan3/range/views/join.hpp>

include/seqan3/argument_parser/detail/version_check.hpp
- #include <seqan3/io/detail/misc.hpp>
- #include <seqan3/io/detail/safe_filesystem_entry.hpp>

### Contrib

include/seqan3/contrib/parallel/buffer_queue.hpp
- #include <seqan3/range/container/concept.hpp>

include/seqan3/contrib/stream/bgzf_istream.hpp
- #include <seqan3/io/exception.hpp> -> Part of https://github.com/seqan/seqan3/pull/2297

include/seqan3/contrib/stream/bgzf_stream_util.hpp
- #include <seqan3/io/detail/magic_header.hpp>
- #include <seqan3/io/exception.hpp>

### Core

include/seqan3/core/algorithm/detail/execution_handler_parallel.hpp
- #include <seqan3/contrib/parallel/buffer_queue.hpp>

include/seqan3/core/detail/debug_stream_alphabet.hpp
- #include <seqan3/alphabet/concept.hpp> -> Part of https://github.com/seqan/seqan3/pull/2297
- #include <seqan3/alphabet/mask/mask.hpp>
- #include <seqan3/io/stream/concept.hpp>

include/seqan3/core/detail/debug_stream_range.hpp
- #include <seqan3/alphabet/adaptation/char.hpp>
- #include <seqan3/alphabet/adaptation/uint.hpp>
- #include <seqan3/alphabet/concept.hpp> -> Part of https://github.com/seqan/seqan3/pull/2297
- #include <seqan3/range/concept.hpp>

include/seqan3/core/detail/debug_stream_tuple.hpp
- #include <seqan3/alphabet/concept.hpp>

include/seqan3/core/simd/view_to_simd.hpp
- #include <seqan3/alphabet/concept.hpp> -> Part of https://github.com/seqan/seqan3/pull/2297
- #include <seqan3/range/views/detail.hpp> -> Part of https://github.com/seqan/seqan3/pull/2297
- #include <seqan3/range/views/type_reduce.hpp>
- #include <seqan3/range/views/zip.hpp>

include/seqan3/core/debug_stream.hpp
- #include <seqan3/alignment/aligned_sequence/aligned_sequence_concept.hpp> -> Part of https://github.com/seqan/seqan3/pull/2297

### IO

include/seqan3/io/alignment_file/detail.hpp
- #include <seqan3/alignment/aligned_sequence/aligned_sequence_concept.hpp>

include/seqan3/io/detail/misc_input.hpp
- #include <seqan3/contrib/stream/bgzf_istream.hpp>
- #include <seqan3/contrib/stream/bgzf_stream_util.hpp>
- #include <seqan3/contrib/stream/gz_istream.hpp>

include/seqan3/io/detail/misc_output.hpp
-  #include <seqan3/contrib/stream/bgzf_ostream.hpp>
-  #include <seqan3/contrib/stream/gz_ostream.hpp>

### Search
As far as I can see already only depending on utility, core and alphabet and ranges

### Utility

include/seqan3/utility/char_operations/predicate_detail.hpp
- #include <seqan3/alphabet/concept.hpp> 

include/seqan3/utility/char_operations/predicate.hpp
- #include <seqan3/alphabet/concept.hpp> 

include/seqan3/utility/char_operations/transform.hpp
- #include <seqan3/core/concept/core_language.hpp>

include/seqan3/utility/parallel/detail/reader_writer_manager.hpp
- #include <seqan3/core/detail/strong_type.hpp>

include/seqan3/utility/tuple/concept.hpp
- #include <seqan3/core/detail/template_inspection.hpp> -> Part of https://github.com/seqan/seqan3/pull/2297

include/seqan3/utility/type_list/type_list.hpp
- #include <seqan3/core/detail/template_inspection.hpp>

For utility I tried to ignore things that are currently in core, but are going to be utility according to #160

**Comment by rrahn** [comment]
### Resolution 2020-12-14

* We remove the unused includes
* We postpone resolving the dependencies when we have clang support.

**Comment by marehr** [comment]
Close because
1. Was merged
2. Opened a new ticket for clang support https://github.com/seqan/product_backlog/issues/276
