### ISSUE TITLE
Document shape and its associated entities with `\experimental`

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#265]
### Description 

Mark the shapes and all associated data structures as `experimental` for the 3.1 release. We do not have enough use cases to find a suitable naming convention and API to handle the issue with initialising the dynamic_bitset differently then the shapes.

From the original ticket
```
Handling of "bit-patterns" is inconsistent. The dynamic_bitset takes string literals"0101" while the shape gets an extra strong type that is initialised with a numeric literal in binary notation: bin_literal{0b10101}.
I suggest the following:
    rename bin_literal to bits
    give bits a constructor from number and one from string_view.
    introduce 0b101_bits and "101"_bits as user defined literals of type bits.
    Use bits in the constructors of dynamic_bitset and shape.
    Thoughts: 2020-11-10
        shape gets strong_type for ungapped{5} or bin_literal{0b10101} -> "101"_bits
        we have already a literal: 0b101011_shape -> shape // static
        can we have 10_ungapped_shape -> shape ungapped of size 10? not possible as runtime parameter
        seqan2 has: dynamic_gapped_shape, dynamic_ungapped_shape, static_gapped_shape and static_ungapped_shape
        extension of shapes as static/dynamic, idea: use first class templates using mechanism like in span.
```
### Acceptance Criteria

- [ ] In the documentation of the shape and all it associated data structures add a documentation entry using `\experimental` keyword.

### Tasks

 

- [ ] find all public data structures and functions that use the `seqan3::shape`
- [ ] mark them with `\experimental` in the details section of the API documentation
- [ ] Change the message of experimental to `The interface of this entity is experimental and might change in future releases of SeqAn3. Do not rely on it in stable releases of your application.`

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
