### ISSUE TITLE
[ALPHABET, DOC] Improve documentation of the quality alphabets

### ISSUE THREAD

**Issue by smehringer** [seqan/product_backlog#266]
### Description 

Should be tackled after the new alphabet #267 is included!

The quality alphabets are not understood easily. Should I use `phred42` pr `phred63`? What's the difference? And which "Format" (regarding the Sanger/Illumina/Solexa encoding) is used? 

Our documentation is not completely clear about this and should be improved.

References:
* Wikipedia on phred scores: https://en.wikipedia.org/wiki/FASTQ_format#Quality
* Our [documentation](http://docs.seqan.de/seqan/3-master-dev/group__quality.html) on the quality landing page
* Hannes Dissertation (see [issue comment here](https://github.com/seqan/product_backlog/issues/249#issuecomment-735598796) for an excerpt)
* **[EDIT (irallia)]** Explanation about Phred+33 and Phred+64 http://people.duke.edu/~ccc14/duke-hts-2018/bioinformatics/quality_scores.html#Phred-Encodings

### Tasks

- [x] Work yourself into what the phred alphabet is representing. **First** by reading our documentation, s.t. you have hands-on experience which parts are confusing.
- [x] Improve the documentation on the quality landing page s.t. it is clearer to users what quality alphabet they should use in which case. Kind of a guide to follow.   
- [x] Also reference (`\ref`) the landing page documentation on the individual quality alphabets (`phred42/63/68legacy`) documentation, s.t. the user is pointed to the detailed documentation
- [x] **[EDIT (irallia)]** Add a tutorial Phred score part to the alphabet tutorial. Add a snippet which represents a dna phred score combination to show the context for phred scores.
- [x] **[EDIT (irallia)]** Give also an explanation about Phred+33 and Phred+64 (we use only Phred+33?)?
