### ISSUE TITLE
[ALPHABET] Add the quality alphabet seqan3::phred94 

### ISSUE THREAD

**Issue by smehringer** [seqan/product_backlog#267]
### Description 

We currently support the Sanger/Illumina 1.8 encoding (score offset +33) with two different alphabets: `seqan3::phred42` and `seqan3::phred63`, both do not represent the full range of possible values (for memory and compression reasons, and also because common score rarely exceed a score of 62). We also want to support the full range of phred scores, because this is the default range and because PacBio Reads emit the full range of quality scores (use case).

(Follow up issue from discussion on https://github.com/seqan/product_backlog/issues/249)

### Tasks

- [x] Take a look at `seqan3::phred42/63` and implement `seqan3::phred94` analogously.
- [x] Add a unit test for the alphabet (using the respective test templates and also checking individual characteristics, see the unit test for  `seqan3::phred42/63` as a reference).
- [x] Add the alphabet to the alphabet benchmarks (there are 4 of them, to_rank, from_rank, to_char, from_char)
- [x] Update the documentation on the [quality landing page](http://docs.seqan.de/seqan/3-master-dev/group__quality.html)
- [x] Check if the tutorials need an update.
- [x] Add a Changelog Entry for this new feature
