### ISSUE TITLE
API Stability of Alignment Module

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#268]
* [ ] ./alignment/aligned_sequence
    * [ ] ./alignment/aligned_sequence/aligned_sequence_concept.hpp
        * [x] aligned_sequence
        * [x] writable_aligned_sequence (TODO: is this really stable or should be marked experimental)
        * [ ] insert_gap
        * [ ] erase_gap
        * [ ] assign_unaligned
    * [x] ./alignment/aligned_sequence/all.hpp
    * [ ] ./alignment/aligned_sequence/debug_stream_alignment.hpp
* [x] ./alignment/all.hpp
* [ ] ./alignment/band
    * [ ] ./alignment/band/all.hpp
    * [x] ~~./alignment/band/static_band.hpp~~, https://github.com/seqan/seqan3/pull/2272
* [ ] ./alignment/configuration https://github.com/seqan/product_backlog/issues/55
    * [x] ./alignment/configuration/align_config_band.hpp
    * [x] ~~./alignment/configuration/align_config_debug.hpp~~
    * [x] ./alignment/configuration/align_config_edit.hpp
    * [x] ./alignment/configuration/align_config_gap_cost_affine.hpp
    * [x] ./alignment/configuration/align_config_method.hpp
    * [x] ./alignment/configuration/align_config_min_score.hpp
    * [x] ./alignment/configuration/align_config_on_result.hpp
    * [x] ./alignment/configuration/align_config_output.hpp
    * [x] ./alignment/configuration/align_config_parallel.hpp
    * [x] ./alignment/configuration/align_config_result_type.hpp
    * [x] ./alignment/configuration/align_config_score_type.hpp
    * [x] ./alignment/configuration/align_config_scoring_scheme.hpp
    * [x] ./alignment/configuration/align_config_vectorised.hpp
    * [x] ./alignment/configuration/all.hpp
    * [x] ~~./alignment/configuration/detail.hpp~~
* [ ] ./alignment/exception.hpp
    * [ ] gap_erase_failure
    * [ ] invalid_alignment_configuration
* [ ] ./alignment/matrix
    * [x] ./alignment/matrix/alignment_coordinate.hpp
        * [x] alignment_coordinate
    * [x] ~~./alignment/matrix/alignment_optimum.hpp~~
    * [x] ./alignment/matrix/all.hpp
    * [x] ~~./alignment/matrix/debug_matrix.hpp~~ (detail, except for operator<<)
    * [x] ~~./alignment/matrix/detail~~
        * [x] ./alignment/matrix/detail/affine_cell_proxy.hpp
        * [x] ./alignment/matrix/detail/aligned_sequence_builder.hpp
        * [x] ./alignment/matrix/detail/alignment_matrix_column_major_range_base.hpp
        * [x] ./alignment/matrix/detail/alignment_score_matrix_one_column_banded.hpp
        * [x] ./alignment/matrix/detail/alignment_score_matrix_one_column_base.hpp
        * [x] ./alignment/matrix/detail/alignment_score_matrix_one_column.hpp
        * [x] ./alignment/matrix/detail/alignment_score_matrix_proxy.hpp
        * [x] ./alignment/matrix/detail/alignment_trace_matrix_base.hpp
        * [x] ./alignment/matrix/detail/alignment_trace_matrix_full_banded.hpp
        * [x] ./alignment/matrix/detail/alignment_trace_matrix_full.hpp
        * [x] ./alignment/matrix/detail/alignment_trace_matrix_proxy.hpp
        * [x] ./alignment/matrix/detail/all.hpp
        * [x] ./alignment/matrix/detail/combined_score_and_trace_matrix.hpp
        * [x] ./alignment/matrix/detail/coordinate_matrix.hpp
        * [x] ./alignment/matrix/detail/matrix_coordinate.hpp
        * [x] ./alignment/matrix/detail/score_matrix_single_column.hpp
        * [x] ./alignment/matrix/detail/trace_iterator_banded.hpp
        * [x] ./alignment/matrix/detail/trace_iterator_base.hpp
        * [x] ./alignment/matrix/detail/trace_iterator.hpp
        * [x] ./alignment/matrix/detail/trace_matrix_full.hpp
        * [x] ./alignment/matrix/detail/two_dimensional_matrix.hpp
        * [x] ./alignment/matrix/detail/two_dimensional_matrix_iterator_base.hpp
        * [x] ./alignment/matrix/detail/two_dimensional_matrix_iterator_concept.hpp
    * [x] ~~./alignment/matrix/edit_distance_score_matrix_full.hpp~~
    * [x] ~~./alignment/matrix/edit_distance_trace_matrix_full.hpp~~
    * [x] ~~./alignment/matrix/matrix_concept.hpp~~
    * [x] ~~./alignment/matrix/row_wise_matrix.hpp~~
    * [x] ~~./alignment/matrix/trace_directions.hpp~~ (detail, except for operator<<)
* [x] ./alignment/pairwise
    * [x] ~~./alignment/pairwise/alignment_algorithm.hpp~~
    * [x] ~~./alignment/pairwise/alignment_configurator.hpp~~
    * [x] ~~./alignment/pairwise/alignment_result.hpp~~ (detail, except for operator<<)
    * [x] ./alignment/pairwise/align_pairwise.hpp
        * [x] align_pairwise
    * [x] ~~./alignment/pairwise/align_result_selector.hpp~~
    * [x] ./alignment/pairwise/all.hpp
    * [x] ./alignment/pairwise/detail
        * [x] ./alignment/pairwise/detail/alignment_algorithm_state.hpp
        * [x] ./alignment/pairwise/detail/concept.hpp
        * [x] ./alignment/pairwise/detail/pairwise_alignment_algorithm_banded.hpp
        * [x] ./alignment/pairwise/detail/pairwise_alignment_algorithm.hpp
        * [x] ./alignment/pairwise/detail/policy_affine_gap_recursion_banded.hpp
        * [x] ./alignment/pairwise/detail/policy_affine_gap_recursion.hpp
        * [x] ./alignment/pairwise/detail/policy_affine_gap_with_trace_recursion_banded.hpp
        * [x] ./alignment/pairwise/detail/policy_affine_gap_with_trace_recursion.hpp
        * [x] ./alignment/pairwise/detail/policy_alignment_matrix.hpp
        * [x] ./alignment/pairwise/detail/policy_alignment_result_builder.hpp
        * [x] ./alignment/pairwise/detail/policy_optimum_tracker.hpp
        * [x] ./alignment/pairwise/detail/policy_optimum_tracker_simd.hpp
        * [x] ./alignment/pairwise/detail/policy_scoring_scheme.hpp
        * [x] ./alignment/pairwise/detail/type_traits.hpp
    * [x] ~~./alignment/pairwise/edit_distance_algorithm.hpp~~
    * [x] ~~./alignment/pairwise/edit_distance_fwd.hpp~~
    * [x] ~~./alignment/pairwise/edit_distance_unbanded.hpp~~
    * [x] ~~./alignment/pairwise/policy~~
        * [x] ./alignment/pairwise/policy/affine_gap_init_policy.hpp
        * [x] ./alignment/pairwise/policy/affine_gap_policy.hpp
        * [x] ./alignment/pairwise/policy/alignment_matrix_policy.hpp
        * [x] ./alignment/pairwise/policy/all.hpp
        * [x] ./alignment/pairwise/policy/find_optimum_policy.hpp
        * [x] ./alignment/pairwise/policy/scoring_scheme_policy.hpp
        * [x] ./alignment/pairwise/policy/simd_affine_gap_policy.hpp
        * [x] ./alignment/pairwise/policy/simd_find_optimum_policy.hpp
* [ ] ./alignment/scoring
    * [x] ./alignment/scoring/all.hpp
    * [ ] ./alignment/scoring/aminoacid_scoring_scheme.hpp
        * [ ] aminoacid_similarity_matrix
        * [ ] aminoacid_scoring_scheme
        * [x] lower case member constants (BLOSUM45 -> blosum45)
        * [x] https://github.com/seqan/product_backlog/issues/317
    * [x] ~~./alignment/scoring/detail~~
        * [x] ./alignment/scoring/detail/simd_match_mismatch_scoring_scheme.hpp
        * [x] ./alignment/scoring/detail/simd_matrix_scoring_scheme.hpp
    * [ ] ~~./alignment/scoring/gap_scheme.hpp~~ (is implemented via alignment/configuration/align_config_gap_cost_affine.hpp)
        * [ ] gap_score
        * [ ] gap_open_score
    * [ ] ./alignment/scoring/nucleotide_scoring_scheme.hpp
        * [ ] nucleotide_scoring_scheme
    * [ ] ./alignment/scoring/scoring_scheme_base.hpp
        * [ ] match_score
        * [ ] mismatch_score
        * [ ] scoring_scheme_base
    * [ ] ./alignment/scoring/scoring_scheme_concept.hpp
        * [ ] scoring_scheme_for

**Comment by smehringer** [comment]
#### Core Meeting 18.01.2021

# Todos:

### High Priority
- [x] **scoring schemes**: scoring schemes must be supplied for `seqan3::align_pairwise`. If we mark `seqan3::align_pairwise` as api-stable but scoring schemes as experimental, `seqan3::align_pairwise` cannot really be used in a stable way. Discussing scoring schemes has a high priority! 
  - **MOVED TO 3.2**: https://github.com/seqan/product_backlog/issues/391
- [x] Concern: Is the the naming of `seqan3::alignment_result` maybe not compatible with later changes, when we introduce the multiple alignment. Possible alternatives: `seqan3::align_pairwise_result` `seqan3::sequence_alignment_result` (and later `seqan3::align_multiple_result`, `seqan3::multiple_sequence_alignment_result`)
  - **MOVED TO 3.2**: https://github.com/seqan/product_backlog/issues/391


### Lower Priority

- [x] Add deprecate documentation to `seqan3::static_band` (only the whole header has a doxygen deprecated documentation not the entity itself) (https://github.com/seqan/seqan3/pull/2345)
- [x] Deprecate `seqan3::alignment_coordinate` (https://github.com/seqan/product_backlog/issues/282)
- [x] Deprecate `seqan3::gap_scheme` and it's utilities (#283)
- [x] `seqan3::align_cfg::scoring_sheme` is in the wrong documentation group. fix the `\ingroup` command (seqan/seqan3#2344)
- [x] Is `writeable_aligned_sequence` concept really stable, or should it be experimental since the functions `insert_gap`, ... are not stable yet
  - **MOVED TO 3.2**: https://github.com/seqan/product_backlog/issues/391

**Comment by marehr** [comment]
Open todos were collected in epic https://github.com/seqan/product_backlog/issues/391.
