### ISSUE TITLE
API Stability of Alphabet Module

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#269]
* [x] Open: How to do conversion between two compatible types of the same group (aminoacid, nucleotide)
  * **MOVED TO Release 3.2**: https://github.com/seqan/product_backlog/issues/389 
* [x] ./alphabet/adaptation
    * [x] ./alphabet/adaptation/all.hpp API_STABLE
    * [x] ./alphabet/adaptation/char.hpp API_STABLE
    * [x] ./alphabet/adaptation/uint.hpp API_STABLE
* [x] ./alphabet/all.hpp API_STABLE
* [x] ./alphabet/alphabet_base.hpp
    * [x] alphabet_base API_STABLE
    * [x] alphabet_base.char_type protected API_STABLE
    * [x] alphabet_base.rank_type protected API_STABLE
    * [x] alphabet_base.to_char API_STABLE
    * [x] alphabet_base.to_rank API_STABLE
    * [x] alphabet_base.assign_char API_STABLE
    * [x] alphabet_base.assign_rank API_STABLE
    * [x] alphabet_base.alphabet_size API_STABLE
    * [x] alphabet_base.<=> API_STABLE
* [x] ./alphabet/aminoacid
    * [x] ./alphabet/aminoacid/aa10li.hpp
        * [x] aa10li API_STABLE
        * [x] aa10li_vector API_STABLE
        * [x] ""_aa10li API_STABLE
    * [x] ./alphabet/aminoacid/aa10murphy.hpp
        * [x] aa10murphy API_STABLE
        * [x] aa10murphy_vector API_STABLE
        * [x] ""_aa10murphy API_STABLE
    * [x] ./alphabet/aminoacid/aa20.hpp
        * [x] aa20 API_STABLE
        * [x] aa20_vector API_STABLE
        * [x] ""_aa20 API_STABLE
    * [x] ./alphabet/aminoacid/aa27.hpp
        * [x] aa27 API_STABLE
        * [x] aa27_vector API_STABLE
        * [x] ""_aa27 API_STABLE
    * [x] ./alphabet/aminoacid/all.hpp API_STABLE
    * [x] ./alphabet/aminoacid/aminoacid_base.hpp
        * [x] aminoacid_base API_STABLE
        * [x] aminoacid_base.char_is_valid API_EXPERIMENTAL (https://github.com/seqan/product_backlog/issues/269#issuecomment-757857405)
    * [x] ./alphabet/aminoacid/concept.hpp
        * [x] aminoacid_empty_base API_STABLE
        * [x] enable_aminoacid API_STABLE (except for ADL CPO, this is marked API_EXPERIMENTAL)
        * [x] aminoacid_alphabet API_STABLE
    * [x] ~~./alphabet/aminoacid/translation_details.hpp~~
    * [x] https://github.com/seqan/product_backlog/issues/318
    * [x] ./alphabet/aminoacid/translation_genetic_code.hpp
        * [x] genetic_code API_EXPERIMENTAL
    * [x] ./alphabet/aminoacid/translation.hpp
        * [x] translate_triplet API_EXPERIMENTAL
* [x] ./alphabet/cigar
    * [x] ./alphabet/cigar/all.hpp
    * [x] ./alphabet/cigar/cigar.hpp
        * [x] cigar API_STABLE
        * [x] cigar.to_string API_EXPERIMENTAL
        * [x] cigar.assign_string API_EXPERIMENTAL
    * [x] ./alphabet/cigar/cigar_op.hpp API_EXPOSITION_ONLY (we put this into the seqan3::cigar class)
* [x] ./alphabet/composite
    * [x] ./alphabet/composite/all.hpp
    * [x] ./alphabet/composite/alphabet_tuple_base.hpp
        * [x] alphabet_tuple_base API_STABLE
        * [x] alphabet_tuple_base.get API_STABLE
    * [x] ./alphabet/composite/alphabet_variant.hpp
        * [x] alphabet_variant
        * [x] alphabet_variant.holds_alternative; rename to is_alternative API_STABLE
        * [x] alphabet_variant.is_alternative; rename to holds_alternative<type> API_STABLE (holds_alternative<index> is API_EXPERIMENTAL)
        * [x] https://github.com/seqan/product_backlog/issues/314
        * [x] alphabet_variant.convert_to API_EXPERIMENTAL
        * [x] alphabet_variant.convert_unsafely_to API_EXPERIMENTAL
    * [x] ~~./alphabet/composite/detail.hpp~~
    * [x] ./alphabet/composite/semialphabet_any.hpp API_STABLE
* [x] ./alphabet/concept.hpp
    * [x] alphabet_rank_t API_STABLE
    * [x] alphabet_char_t API_STABLE
    * [x] to_rank API_STABLE (except for ADL CPO, this is marked API_EXPERIMENTAL)
    * [x] assign_rank_to API_STABLE (except for ADL CPO, this is marked API_EXPERIMENTAL)
    * [x] to_char API_STABLE (except for ADL CPO, this is marked API_EXPERIMENTAL)
    * [x] assign_char_to API_STABLE (except for ADL CPO, this is marked API_EXPERIMENTAL)
    * [x] char_is_valid_for (https://github.com/seqan/product_backlog/issues/269#issuecomment-757857405)  API_EXPERIMENTAL
    * [x] assign_char_strictly_to (https://github.com/seqan/product_backlog/issues/269#issuecomment-757857405) API_EXPERIMENTAL
    * [x] alphabet_size API_STABLE (except for ADL CPO, this is marked API_EXPERIMENTAL)
    * [x] semialphabet API_STABLE
    * [x] writable_semialphabet API_STABLE
    * [x] alphabet API_STABLE
    * [x] writable_alphabet (https://github.com/seqan/product_backlog/issues/269#issuecomment-757857405)  API_STABLE
* [x] ./alphabet/detail
    * [x] ./alphabet/detail/alphabet_proxy.hpp
    * [x] ./alphabet/detail/convert.hpp
* [x] ./alphabet/exception.hpp
    * [x] invalid_char_assignment API_EXPERIMENTAL
* [x] ./alphabet/gap
    * [x] ./alphabet/gap/all.hpp
    * [x] ./alphabet/gap/gap.hpp
    * [x] ./alphabet/gap/gapped.hpp
* [x] ./alphabet/hash.hpp std::hash overload 
* [x] ./alphabet/mask
    * [x] ./alphabet/mask/all.hpp
    * [x] ./alphabet/mask/masked.hpp  TODO: add article which explains lower and upper ans use cases
        * [x] https://github.com/seqan/product_backlog/issues/313
        * [x] masked API_STABLE
        * [x] masked.sequence_alphabet_type API_STABLE
    * [x] ./alphabet/mask/mask.hpp
        * [x] mask API_STABLE
        * [x] mask.UNMASKED lower case API_STABLE
        * [x] mask.MASKED lower case API_STABLE
        * [x] https://github.com/seqan/product_backlog/issues/311
        * [x] https://github.com/seqan/product_backlog/issues/313
* [x] ./alphabet/nucleotide 
    * [x] ./alphabet/nucleotide/all.hpp
    * [x] ./alphabet/nucleotide/concept.hpp
       * [x] complement API_STABLE (except for ADL CPO, this is marked API_EXPERIMENTAL)
       * [x] nucleotide_alphabet API_STABLE
    * [x] ./alphabet/nucleotide/dna15.hpp API_STABLE
    * [x] ./alphabet/nucleotide/dna3bs.hpp 
    * [x] ./alphabet/nucleotide/dna4.hpp API_STABLE
    * [x] https://github.com/seqan/product_backlog/issues/320
    * [x] ./alphabet/nucleotide/dna5.hpp API_STABLE
    * [x] ./alphabet/nucleotide/nucleotide_base.hpp
        * [x] nucleotide_base
        * [x] nucleotide_base.complement API_STABLE
        * [x] nucleotide_base.char_is_valid API_EXPERIMENTAL (https://github.com/seqan/product_backlog/issues/269#issuecomment-757857405)
    * [x] ./alphabet/nucleotide/rna15.hpp API_STABLE
    * [x] ./alphabet/nucleotide/rna4.hpp API_STABLE
    * [x] ./alphabet/nucleotide/rna5.hpp API_STABLE
    * [x] ./alphabet/nucleotide/sam_dna16.hpp API_STABLE TODO rename to dna16sam.hpp
    * [x] https://github.com/seqan/product_backlog/issues/312
* [x] ./alphabet/quality
    * [x] ./alphabet/quality/aliases.hpp 
    * [x] ./alphabet/quality/all.hpp
    * [x] ./alphabet/quality/concept.hpp
        * [x] to_phred API_STABLE (except for ADL CPO, this is marked API_EXPERIMENTAL)
        * [x] alphabet_phred_t API_STABLE
        * [x] assign_phred_to API_STABLE (except for ADL CPO, this is marked API_EXPERIMENTAL)
        * [x] quality_alphabet API_STABLE
        * [x] writable_quality_alphabet API_STABLE
    * [x] ./alphabet/quality/phred42.hpp
        * [x] phred42 API_STABLE
        * [x] phred42.offset_phred API_STABLE
        * [x] phred42.offset_char API_STABLE
    * [x] ./alphabet/quality/phred63.hpp API_STABLE
    * [x] ./alphabet/quality/phred68legacy.hpp API_STABLE
    * [x] https://github.com/seqan/product_backlog/issues/315
    * [x] ./alphabet/quality/phred94.hpp API_STABLE
    * [x] ./alphabet/quality/qualified.hpp 
        * [x] qualified API_STABLE
        * [x] qualified.sequence_alphabet_type API_STABLE
        * [x] qualified.quality_alphabet_type API_STABLE
        * [x] qualified.char_type API_STABLE
        * [x] qualified.phred_type API_STABLE
        * [x] qualified.assign_char API_STABLE
        * [x] qualified.assign_phred API_STABLE
        * [x] qualified.to_phred API_STABLE
        * [x] qualified.to_char API_STABLE
        * [x] qualified.complement API_STABLE
        * [x] qualified.char_is_valid API_EXPERIMENTAL (https://github.com/seqan/product_backlog/issues/269#issuecomment-757857405)
    * [x] ./alphabet/quality/quality_base.hpp rename to phred_base (see https://github.com/seqan/product_backlog/issues/269#issuecomment-804011791)
        * [x] https://github.com/seqan/product_backlog/issues/358
        * [x] quality_base API_STABLE (except for implicit constructor for phred_type, e.g. `seqan3::phred42 a = 9;`)
        * [x] https://github.com/seqan/product_backlog/issues/316
        * [x] quality_base.to_phred API_STABLE
        * [x] quality_base.assign_phred API_STABLE
* [x] ./alphabet/structure
    * [x] ./alphabet/structure/all.hpp
    * [x] ./alphabet/structure/concept.hpp
        * [x] is_pair_open API_EXPERIMENTAL
        * [x] is_pair_close API_EXPERIMENTAL
        * [x] is_unpaired API_EXPERIMENTAL
        * [x] max_pseudoknot_depth API_EXPERIMENTAL
        * [x] pseudoknot_id API_EXPERIMENTAL
        * [x] rna_structure_alphabet API_EXPERIMENTAL
    * [x] ./alphabet/structure/dot_bracket3.hpp
        * [x] dot_bracket3 : alphabet_base API_EXPERIMENTAL
        * [x] dot_bracket3.is_pair_open API_EXPERIMENTAL
        * [x] dot_bracket3.is_pair_close API_EXPERIMENTAL
        * [x] dot_bracket3.is_unpaired API_EXPERIMENTAL
        * [x] dot_bracket3.max_pseudoknot_depth API_EXPERIMENTAL
        * [x] dot_bracket3.pseudoknot_id API_EXPERIMENTAL
    * [x] ./alphabet/structure/dssp9.hpp
        * [x] dssp9 : alphabet_base API_EXPERIMENTAL
    * [x] ./alphabet/structure/structured_aa.hpp
        * [x] structured_aa : alphabet_tuple_base API_EXPERIMENTAL
        * [x] structured_aa.sequence_alphabet_type API_EXPERIMENTAL
        * [x] structured_aa.structure_alphabet_type API_EXPERIMENTAL
        * [x] structured_aa.char_type API_EXPERIMENTAL
        * [x] structured_aa.assign_char API_EXPERIMENTAL
        * [x] structured_aa.to_char API_EXPERIMENTAL
        * [x] structured_aa.char_is_valid API_EXPERIMENTAL (https://github.com/seqan/product_backlog/issues/269#issuecomment-757857405)
    * [x] ./alphabet/structure/structured_rna.hpp
        * [x] structured_rna : alphabet_tuple_base API_EXPERIMENTAL
        * [x] sequence_alphabet_type API_EXPERIMENTAL
        * [x] structure_alphabet_type API_EXPERIMENTAL
        * [x] char_type API_EXPERIMENTAL
        * [x] assign_char API_EXPERIMENTAL
        * [x] to_char API_EXPERIMENTAL
        * [x] complement API_EXPERIMENTAL
        * [x] char_is_valid API_EXPERIMENTAL (https://github.com/seqan/product_backlog/issues/269#issuecomment-757857405)
        * [x] is_pair_open API_EXPERIMENTAL
        * [x] is_pair_close API_EXPERIMENTAL
        * [x] is_unpaired API_EXPERIMENTAL
        * [x] max_pseudoknot_depth API_EXPERIMENTAL
        * [x] pseudoknot_id API_EXPERIMENTAL
    * [x] ./alphabet/structure/wuss.hpp
        * [x] wuss : alphabet_base API_EXPERIMENTAL
        * [x] wuss.is_pair_open API_EXPERIMENTAL
        * [x] wuss.is_pair_close API_EXPERIMENTAL
        * [x] wuss.is_unpaired API_EXPERIMENTAL
        * [x] wuss.max_pseudoknot_depth API_EXPERIMENTAL
        * [x] wuss.pseudoknot_id API_EXPERIMENTAL

  `***********************`

**Comment by marehr** [comment]
Core Meeting 2021-01-11:

* [x] char_is_valid in all alphabets (mark experimental)
* [x] seqan3::char_is_valid_for (mark experimental)
* [x] seqan3::assign_char_strictly_to (mark experimental, is currently a dead CPO, no one uses it)
* [x] seqan3::writable_alphabet and seqan3::writable_constexpr_alphabet remove seqan3::char_is_valid_for. (#278)
  * Let's see if we need this feature (uses cases by user) and a possible concept could be added later which has as base `writable_alphabet`

**Comment by smehringer** [comment]
#### Core Meeting 2021-01-18:

# Todos:

### High Priority

* [x] alphabet conversion currently works by converting to char and back. Is this the way we want it to be? Might have implications on the behaviour of alphabets and is thus API relevant (@rrahn will work out the details/problems)
  * **MOVED TO Release 3.2**: https://github.com/seqan/product_backlog/issues/389 

* [x] alphabet conversion is weird; dna4 = 'Y'  results in `Y` being converted to dna15, and then to dna4 (results in 'C' instead of 'A'). dna5 and aminoacid alphabets just define one letter that is used for unknown symbols
  * **MOVED TO Release 3.2**: https://github.com/seqan/product_backlog/issues/389 

* [x] What about `alphabet_base`? Is this marked as stable API?

### Low Priority

* [x] Why is cigar not stable?
* [x] Check documentation of alphabets that use non-stable `alphabet_variant` and `alphabet_tuple`, to make sure the documentation is stand alone and does not refer to unstable entities. Does it have implications on `seqan3::sam_dna16`.
  * We marked `alphabet_variant` and `alphabet_tuple` mostly stable.
* [x] Why are the quality alphabets not stable?
  * **MOVED TO Release 3.2**: https://github.com/seqan/product_backlog/issues/389

**Comment by marehr** [comment]
Core Meeting 2021-02-15:

* [x] We talked about making the look-up tables static functions, so that we can make use cases like https://github.com/seqan/seqan3/issues/1970 possible. We can still use look-up tables within the functions itself if we want to. See https://github.com/seqan/product_backlog/issues/295.

Open Questions:
* [x] Should we make ADL-lookups in CPOs API-stable? (We marked those as experimental)
* [x] enable_aminoacid:
  * [x] should we allow partial specialisation of `seqan3::enable_aminoacid`? (Undecided)
    * **MOVED TO** Release 3.2: https://github.com/seqan/product_backlog/issues/389
  * [x] should we allow ADL? (We marked this as experimental)
  * [x] seqan3::custom::alphabet seems to be the most flexible way to define custom / third-party alphabets.

**Comment by marehr** [comment]
Core-Meeting 2021-02-17:

Resolution:
* [x] Rename `seqan3::cigar_op` to `seqan3::cigar_operation` and if possible make this part of `seqan3::cigar::operation`. See https://github.com/seqan/product_backlog/issues/294

**Comment by marehr** [comment]
Core-Meeting 2021-02-22:
* [x] Documentation: How to deal with assignment operator which are inherited, e.g. cigar defines an assignment operator for documentation, but the documentations also displays the assignment operator for the tuple_base.
* [x] alphabet_tuple_base uses hidden `get` friend, so `seqan3::get<0>(tuple)` is not possible. How about `std::get<0>(tuple)`?
  * https://stackoverflow.com/questions/16173902/enable-stdget-support-on-class: This means hidden friends are okay.
  * seqan3::get not usable; add documentation to explain this.
* [x] alphabet_tuple_base is ==, !=, <= commutative with indirect alphabets?
  * **MOVED TO** Release 3.2: https://github.com/seqan/product_backlog/issues/389
* [x]  Doxygen strikes again: ![grafik](https://user-images.githubusercontent.com/103778/108706642-30e1dd80-750f-11eb-8451-c2d8aece81e6.png)

**Comment by marehr** [comment]
2021-03-22 Core-Meeting:

* [x] rename `seqan3::sam_dna16` to `seqan3::dna16sam` (to reflect the general naming scheme of alphabets, e.g. `aa10li` "alphabet_category""alphabet_size""alphabet_unique_identifier").
* [x] rename `seqan3::phred68legacy` to `seqan3::phred68solexa`
* [x] conversion between `seqan3::phred68solexa` and `seqan3::phred42` should be over the failure probability and not the phred scores.
  * **MOVED TO** Release 3.2: https://github.com/seqan/product_backlog/issues/389
* [x] rename `seqan3::quality_base` to `seqan3::phred_base`

TODO:
* [x] alphabet/concept.hpp: CPOs mark ADL cpo_overloads experimental 
* [x] alphabet/nucleotide/concept.hpp: CPOs mark ADL cpo_overloads experimental 
* [x] alphabet/quality/concept.hpp: CPOs mark ADL cpo_overloads experimental

**Comment by marehr** [comment]
We talked about "uint64_t is not an alphabet?" https://github.com/seqan/product_backlog/issues/200
* [x] What to do?
  * **MOVED TO** Release 3.2: https://github.com/seqan/product_backlog/issues/389

**Comment by marehr** [comment]
Open todos were collected in epic https://github.com/seqan/product_backlog/issues/389.
