### ISSUE TITLE
 I want to be able to specify the number of threads that can be used to distribute the search such that the run time scales with the number of threads.

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#27]
### Description 

Enable multi threading search via a search configuration. 
The internals need to be refactored to allow a similar execution mechanism within the search.
For this it would be good to change the current configuration to decouple it from the call of the actual algorithm. The algorithm can be a class template function object and be specified via policies. Then we have one configuration step and one invocation step.

### Acceptance Criteria

- [ ] If the option is not given, code is run in sequential mode.
- [ ] If the option is given but no threads uses `std::thread::hardware_concurrency` many threads.
- [ ] If the options is given with a specific number of threads then these many threads are used for the algorithm.
- [ ] If the provided thread count is less than 1 an exception is thrown indicating a wrong number of threads.

### Tasks

 

- [ ] split the algorithm into a configuration and an invocation phase
- [ ] add or resuse sequential execution handler for the search.
- [ ] add or reuse parallel execution handler for the search
- [ ] add a two-way executor for the search that is configured over the execution handlers
- [ ] refactor the search algorithm into a class template function object.

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
