### ISSUE TITLE
API Stability of Core Module

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#270]
* [ ] ./core/add_enum_bitwise_operators.hpp
    * [ ] add_enum_bitwise_operators
    * [ ] TODO: make private: https://github.com/seqan/seqan3/wiki/Core-Meeting-notes#2020-02-17-eseiler
      * [ ] **Created follow-up:** https://github.com/seqan/product_backlog/issues/390 
* [x] ./core/algorithm https://github.com/seqan/product_backlog/issues/160
    * [x] ./core/algorithm/algorithm_result_generator_range.hpp
    * [x] ./core/algorithm/all.hpp
    * [x] ~~./core/algorithm/bound.hpp~~ https://github.com/seqan/seqan3/pull/2272
    * [x] ~~./core/algorithm/concept.hpp~~
    * [x] ~~./core/algorithm/configuration_element_debug_mode.hpp~~
    * [x] ~~./core/algorithm/configuration_element_parallel_mode.hpp~~
    * [x] ~~./core/algorithm/configuration.hpp~~
    * [x] ~~./core/algorithm/configuration_utility.hpp~~
    * [x] ~~./core/algorithm/detail~~
        * [x] ~~./core/algorithm/detail/algorithm_executor_blocking.hpp~~
        * [x] ~~./core/algorithm/detail/all.hpp~~
        * [x] ~~./core/algorithm/detail/execution_handler_parallel.hpp~~
        * [x] ~~./core/algorithm/detail/execution_handler_sequential.hpp~~
    * [x] ./core/algorithm/pipeable_config_element.hpp
        * [x] move to core/configuration/. ?
        * [x] Should it be put into detail? Maybe we can add documentation for the pipe stuff for the config elements.
        * [x] https://github.com/seqan/seqan3/pull/2636
* [x] ./core/all.hpp
* [x] ./core/bit_manipulation.hpp https://github.com/seqan/product_backlog/issues/199
    * [x] utility/detail/to_little_endian and utility/detail/bits_of // remaining stuff goes into seqan3/std/bit https://gist.github.com/rrahn/f6b09ad67bebd14bd9c58f77c53e0450
* [x] ~~./core/char_operations~~
    * [x] ~~./core/char_operations/all.hpp~~
    * [x] ~~./core/char_operations/predicate_detail.hpp~~
    * [x] ~~./core/char_operations/predicate.hpp~~
    * [x] ~~./core/char_operations/pretty_print.hpp~~
    * [x] ~~./core/char_operations/transform.hpp~~
* [x] ./core/common_tuple.hpp move to core/tuple/
    * [x] ranges::common_tuple
    * [x] ranges::common_pair
* [ ] ./core/concept
    * [ ] ./core/concept/all.hpp
    * [ ] ./core/concept/cereal.hpp
        * [ ] cereal_output_archive
        * [ ] cereal_input_archive
        * [ ] cereal_archive
        * [ ] cereal_text_archive
        * [ ] cerealisable
    * [x] ./core/concept/core_language.hpp move to utility/concept/.
    * [x] ./core/concept/tuple.hpp move to utility/tuple/concept.hpp
* [ ] ./core/configuration
    * [x] ./core/configuration/all.hpp
    * [ ] ./core/configuration/configuration.hpp
        * [ ] configuration
        * [x] configuration.size
        * [x] configuration.get_or
        * [x] configuration.exists
        * [x] configuration.remove
        * [x] configuration.operator|
        * [ ] seqan3::get DISCUSSION OPEN: https://github.com/seqan/product_backlog/issues/195#issuecomment-727897166
        * [ ] std::tuple_size DISCUSSION OPEN!
        * [ ] std::tuple_element DISCUSSION OPEN!
    * [x] ./core/configuration/detail
        * [x] ~~./core/configuration/detail/all.hpp~~
        * [x] ~~./core/configuration/detail/concept.hpp~~
        * [x] ~~./core/configuration/detail/configuration_element_debug_mode.hpp~~
        * [x] ~~./core/configuration/detail/configuration_element_parallel_mode.hpp~~
        * [x] ~~./core/configuration/detail/configuration_utility.hpp~~
* [ ] ./core/debug_stream
    * [x] ~~./core/debug_stream/detail~~
        * [x] ~~./core/debug_stream/detail/to_string.hpp~~
* [ ] ./core/debug_stream.hpp
* [ ] ~~./core/detail~~
    * [x] ~~./core/detail/all.hpp~~
    * [x] ~~./core/detail/customisation_point.hpp~~
    * [x] ~~./core/detail/debug_stream_alphabet.hpp~~
    * [x] ~~./core/detail/debug_stream_optional.hpp~~
    * [x] ~~./core/detail/debug_stream_range.hpp~~
    * [x] ~~./core/detail/debug_stream_tuple.hpp~~
    * [ ] ./core/detail/debug_stream_type.hpp
        * [ ] fmtflags2
        * [ ] debug_stream_type
        * [ ] debug_stream_type.set_underlying_stream
        * [ ] debug_stream_type.operator<<
        * [ ] debug_stream_type.fmtflags
        * [ ] debug_stream_type.flags
        * [ ] debug_stream_type.setf
        * [ ] debug_stream_type.unsetf
        * [ ] debug_stream_type.flags2
        * [ ] debug_stream_type.flags2
        * [ ] debug_stream_type.setf
        * [ ] debug_stream_type.unsetf
    * [x] ~~./core/detail/debug_stream_variant.hpp~~
    * [x] ~~./core/detail/deferred_crtp_base.hpp~~
    * [x] ~~./core/detail/empty_type.hpp~~
    * [x] ~~./core/detail/endian.hpp~~
    * [x] ~~./core/detail/int_types.hpp~~
    * [x] ~~./core/detail/is_class_template_declarable.hpp~~
    * [x] ~~./core/detail/iterator_traits.hpp~~
    * [x] ~~./core/detail/pack_algorithm.hpp~~
    * [x] ~~./core/detail/strong_type.hpp~~
    * [x] ~~./core/detail/template_inspection.hpp~~
    * [x] ~~./core/detail/test_accessor.hpp~~
    * [x] ~~./core/detail/to_string.hpp~~
    * [x] ~~./core/detail/type_inspection.hpp~~
* [x] ~~./core/math.hpp~~
* [x] ./core/parallel
    * [x] ./core/parallel/all.hpp
    * [x] ./core/parallel/detail
        * [x] ./core/parallel/detail/latch.hpp
        * [x] ./core/parallel/detail/reader_writer_manager.hpp
        * [x] ./core/parallel/detail/spin_delay.hpp
    * [x] ./core/parallel/execution.hpp
* [ ] ./core/platform.hpp
* [x] ./core/pod_tuple.hpp
* [ ] ./core/range
    * [ ] ./core/range/type_traits.hpp
        * [ ] range_innermost_value
        * [ ] range_innermost_value_t
        * [ ] range_dimension_v
* [ ] ./core/semiregular_box.hpp
    * [ ] ranges::semiregular_box
    * [ ] ranges::semiregular_box_t
* [x] ~~./core/simd~~ move to utility
    * [x] ~~./core/simd/all.hpp~~
    * [x] ~~./core/simd/concept.hpp~~
    * [x] ~~./core/simd/debug_stream_simd.hpp~~
    * [x] ~~./core/simd/detail~~
        * [x] ~~./core/simd/detail/builtin_simd.hpp~~
        * [x] ~~./core/simd/detail/builtin_simd_intrinsics.hpp~~
        * [x] ~~./core/simd/detail/default_simd_backend.hpp~~
        * [x] ~~./core/simd/detail/default_simd_length.hpp~~
        * [x] ~~./core/simd/detail/simd_algorithm_avx2.hpp~~
        * [x] ~~./core/simd/detail/simd_algorithm_avx512.hpp~~
        * [x] ~~./core/simd/detail/simd_algorithm_sse4.hpp~~
    * [x] ~~./core/simd/simd_algorithm.hpp~~
    * [x] ~~./core/simd/simd.hpp~~
    * [x] ~~./core/simd/simd_traits.hpp~~
    * [x] ~~./core/simd/view_iota_simd.hpp~~
    * [x] ~~./core/simd/view_to_simd.hpp~~
* [ ] ./core/tuple_utility.hpp
    * [x] moved to utility/tuple/tuple_utility.hpp
    * [x] -> split into utility/tuple/split.hpp and utility/tuple/pop_front.hpp https://github.com/seqan/seqan3/pull/2609
    * https://gist.github.com/rrahn/f6b09ad67bebd14bd9c58f77c53e0450
* [x] ~~./core/type_list~~
    * [x] ~~./core/type_list/all.hpp~~
    * [x] ~~./core/type_list/traits.hpp~~
    * [x] ~~./core/type_list/type_list.hpp~~
* [x] ~~./core/type_traits~~
    * [x] ~~./core/type_traits/all.hpp~~
    * [x] ~~./core/type_traits/basic.hpp~~
    * [x] ~~./core/type_traits/concept.hpp~~
    * [x] ~~./core/type_traits/deferred_crtp_base.hpp~~
    * [x] ~~./core/type_traits/function.hpp~~
    * [x] ~~./core/type_traits/iterator.hpp~~
    * [x] ~~./core/type_traits/lazy.hpp~~
    * [x] ~~./core/type_traits/pack.hpp~~
    * [x] ~~./core/type_traits/pre.hpp~~
    * [x] ~~./core/type_traits/range.hpp~~
    * [x] ~~./core/type_traits/template_inspection.hpp~~
    * [x] ~~./core/type_traits/transformation_trait_or.hpp~~

**Comment by marehr** [comment]
Most of the things are done for the release, I created https://github.com/seqan/product_backlog/issues/390 to track that one open issue.
