### ISSUE TITLE
API Stability of IO Module

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#271]
General discussion: https://docs.google.com/document/d/1EuGAtT0X5tDbBNFdHeuRfU2RRVOne8CSOJt3lI0U5UY/edit#bookmark=id.c1bmao8g76c5

* [ ] ./io/alignment_file
    * [ ] ./io/alignment_file/all.hpp
    * [ ] ./io/alignment_file/detail.hpp
    * [ ] ./io/alignment_file/format_bam.hpp
    * [ ] ./io/alignment_file/format_sam_base.hpp
    * [ ] ./io/alignment_file/format_sam.hpp
    * [ ] ./io/alignment_file/header.hpp
    * [ ] ./io/alignment_file/input_format_concept.hpp
    * [ ] ./io/alignment_file/input.hpp
    * [ ] ./io/alignment_file/input_options.hpp
    * [ ] ./io/alignment_file/misc.hpp
    * [ ] ./io/alignment_file/output_format_concept.hpp
    * [ ] ./io/alignment_file/output.hpp
    * [ ] ./io/alignment_file/output_options.hpp
    * [ ] ./io/alignment_file/sam_tag_dictionary.hpp
* [ ] ./io/all.hpp
* [ ] ./io/detail
    * [ ] ./io/detail/ignore_output_iterator.hpp
    * [ ] ./io/detail/in_file_iterator.hpp
    * [ ] ./io/detail/magic_header.hpp
    * [ ] ./io/detail/misc.hpp
    * [ ] ./io/detail/misc_input.hpp
    * [ ] ./io/detail/misc_output.hpp
    * [ ] ./io/detail/out_file_iterator.hpp
    * [ ] ./io/detail/record.hpp
    * [ ] ./io/detail/safe_filesystem_entry.hpp
* [ ] ./io/exception.hpp
* [ ] ./io/record.hpp
* [ ] ./io/sequence_file
    * [ ] ./io/sequence_file/all.hpp
    * [ ] ./io/sequence_file/format_embl.hpp
    * [ ] ./io/sequence_file/format_fasta.hpp
    * [ ] ./io/sequence_file/format_fastq.hpp
    * [ ] ./io/sequence_file/format_genbank.hpp
    * [ ] ./io/sequence_file/input_format_concept.hpp
    * [ ] ./io/sequence_file/input.hpp
    * [ ] ./io/sequence_file/input_options.hpp
    * [ ] ./io/sequence_file/output_format_concept.hpp
    * [ ] ./io/sequence_file/output.hpp
    * [ ] ./io/sequence_file/output_options.hpp
* [ ] ./io/stream
    * [ ] ./io/stream/all.hpp
    * [ ] ./io/stream/concept.hpp
    * [ ] ./io/stream/iterator.hpp
* [ ] ./io/structure_file
    * [ ] ./io/structure_file/all.hpp
    * [ ] ./io/structure_file/detail.hpp
    * [ ] ./io/structure_file/format_vienna.hpp
    * [ ] ./io/structure_file/input_format_concept.hpp
    * [ ] ./io/structure_file/input.hpp
    * [ ] ./io/structure_file/input_options.hpp
    * [ ] ./io/structure_file/output_format_concept.hpp
    * [ ] ./io/structure_file/output.hpp
    * [ ] ./io/structure_file/output_options.hpp

**Comment by marehr** [comment]
TODO:

* [ ] Do we want to have a way to set record member's: (Question: https://github.com/seqan/seqan3/pull/2420/files#r585773165)
  * Before switching to explicit member functions this was possible: 
    ```c++
    get<seqan3::field::seq>(my_record) = "ACGT"_dna4; 
    ```
  * Currently it is possible via index, since the record is still a tuple: 
    ```c++
    get<1>(my_record) = "ACGT"_dna4;
    ```
  * If we also switch from a tuple backend we might provide
    ```c++
    my_record.sequence = "ACGT"_dna4;
    ```
    where `.sequence` is a function object that can set its value.

**Comment by marehr** [comment]
Moved to Release 3.2
