### ISSUE TITLE
API Stability of Range Module

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#272]
* [x] ./range/all.hpp
* [x] ./range/concept.hpp 
  * [x] const_iterable_range  EXPOSITION_ONLY
      * [x] move to `utility/range/concept.hpp`
      * [x] https://github.com/seqan/product_backlog/issues/375
  * [x] pseudo_random_access_iterator EXPOSITION_ONLY
      * [x] move to `utility/range/concept.hpp`
      * [x] https://github.com/seqan/product_backlog/issues/375
  * [x] pseudo_random_access_range EXPOSITION_ONLY
      * [x] move to `utility/range/concept.hpp`
      * [x] https://github.com/seqan/product_backlog/issues/375
  * [x] sequence STABLE_API
      * [x] move to `alphabet/range/sequence.hpp`
      * [x] https://github.com/seqan/product_backlog/issues/378
* [x] ./range/container
    * [x] ./range/container/aligned_allocator.hpp
      * [x] aligned_allocator NOAPI could be moved to utility (as e.g. BOOST has a similar implementation)
      * [x] move to `utility/container/aligned_allocator.hpp`
      * [x] https://github.com/seqan/product_backlog/issues/376
    * [x] ./range/container/all.hpp
    * [x] ./range/container/bitcompressed_vector.hpp -> RENAME to `bitpacked_sequence.hpp` STABLE_API
      * [x] Most API is STABLE_API, as it provides a standard container implementation.
      * [x] `bitcompressed_vector{range}`, `bitcompressed_vector{}.assign(range)` are marked experimental API
      * [x] move to `alphabet/container/bitpacked_sequence.hpp`
      * [x] https://github.com/seqan/product_backlog/issues/377
    * [x] ./range/container/concatenated_sequences.hpp EXPERIMENTAL_API
      * [x] `concatenated_sequences{range}`, `concatenated_sequences{}.assign(range)` are marked experimental API
      * [x] move to `alphabet/container/concatenated_sequences.hpp`
      * [x] https://github.com/seqan/product_backlog/issues/377
    * [x] ./range/container/concept.hpp
      * [x] `_container` concepts move to tests, see https://github.com/seqan/product_backlog/issues/221 NOAPI
      * [x] move to `utility/container/concept.hpp`
      * [x] https://github.com/seqan/product_backlog/issues/376
    * [x] ./range/container/dynamic_bitset.hpp EXPERIMENTAL_API (we want a size-unrestricted dynamic_bitset)
      * [x] `dynamic_bitset{range}`, `dynamic_bitset{}.assign(range)` are marked experimental API
      * [x] move to `utility/container/dynamic_bitset.hpp`
      * [x] https://github.com/seqan/product_backlog/issues/376
    * [x] ./range/container/small_string.hpp EXPERIMENTAL_API (since std::string is constexpr since C++2a and we might replace it)
      * [x] `small_string{range}`, `small_string{}.assign(range)` are marked experimental API
      * [x] move to `utility/container/small_string.hpp`
      * [x] https://github.com/seqan/product_backlog/issues/376
    * [x] ./range/container/small_vector.hpp EXPERIMENTAL_API (since std::vector is constexpr since C++2a and we might replace
      * [x] `small_vector{range}`, `small_vector{}.assign(range)` are marked experimental API it)
      * [x] move to `utility/container/small_vector.hpp`
      * [x] https://github.com/seqan/product_backlog/issues/376
* [x] ./range/decorator
    * [x] ./range/decorator/all.hpp
    * [x] ./range/decorator/gap_decorator.hpp
      * [x]  gap_decorator STABLE_API
      * [x] `gap_decorator{range}`, `gap_decorator{}.assign(range)` are marked experimental API
      * [x] hidden-friend assign_unaligned (does this need to be a hidden friend? can this be a member function?) EXPERIMENTAL_API
      * [x] https://github.com/seqan/product_backlog/issues/322
      * [x] move to `alignment/decorator/gap_decorator.hpp`
      * [x] https://github.com/seqan/product_backlog/issues/381
* [x] ./range/detail
    * [x] ./range/detail/inherited_iterator_base.hpp
      * [x] move to `core/range/detail/inherited_iterator_base.hpp`
      * [x] https://github.com/seqan/product_backlog/issues/380
    * [x] ./range/detail/misc.hpp
      * [x] move to `core/range/detail/misc.hpp`
      * [x] https://github.com/seqan/product_backlog/issues/380
    * [x] ./range/detail/random_access_iterator.hpp
      * [x] move to `core/range/detail/random_access_iterator.hpp`
      * [x] https://github.com/seqan/product_backlog/issues/380
* [x] ./range/hash.hpp
  * [x] std::hash<range<semialphabet>> EXPERIMENTAL_API is this still needed? and it defines specialisation for `std::hash<std::vector<int>>` that might interfere with a different library.
      * [x] move to `alphabet/range/hash.hpp`
      * [x] https://github.com/seqan/product_backlog/issues/378
* [x] ./range/shortcuts.hpp DEPRECATED
* [ ] ./range/views
    * [ ] ./range/views/all.hpp
    * [x] ./range/views/as_const.hpp
      * [x] as_const DETAIL_CODE; only used in concatenated_sequences, see https://github.com/seqan/seqan3/commit/12328b98a3f160d6deb8c65d99a51e0e6c2fe28f; should be detail.
      * [x] https://github.com/seqan/product_backlog/issues/323
    * [x] ./range/views/async_input_buffer.hpp
      * [x] async_input_buffer EXPERIMENTAL_API (move to seqan3/io/views, could also be in utility)
      * [x] move to `seqan3/io/views`
      * [x] https://github.com/seqan/product_backlog/issues/343
    * [x] ./range/views/char_to.hpp
      * [x] char_to STABLE_API (move to `include/alphabet/views/`)
      * [x] move to `seqan3/alphabet/views`
      * [x] https://github.com/seqan/product_backlog/issues/335
    * [x] ./range/views/chunk.hpp
      * [x] chunk NOAPI as it is currently just an alias for ::ranges::views::chunk.  (move to seqan3/utility/views)
      * [x] move to `seqan3/utility/views`
      * [x] https://github.com/seqan/product_backlog/issues/347
    * [x] ./range/views/complement.hpp
      * [x] complement STABLE_API (move to `include/alphabet/views/`)
      * [x] move to `seqan3/alphabet/views`
      * [x] https://github.com/seqan/product_backlog/issues/336
    * [x] ./range/views/convert.hpp
      * [x] convert DEPRECATED; use std::views::transform and a functor that static_casts
      * [x] https://github.com/seqan/product_backlog/issues/324
    * [x] ./range/views/deep.hpp
      * Supports `constexpr auto operator()() const` which is not required by the [standard [3][4]](https://eel.is/c++draft/ranges#range.adaptor.object)
      * [x] deep EXPERIMENTAL_API
      * [x] move to `seqan3/utility/views`
      * [x] https://github.com/seqan/product_backlog/issues/348
    * [x] ./range/views/detail.hpp
    * [x] ./range/views/drop.hpp
      * [x] drop DEPRECATED use std::views::drop
      * [x] https://github.com/seqan/product_backlog/issues/325
    * [x] ./range/views/enforce_random_access.hpp
      * [x] enforce_random_access EXPERIMENTAL_API (move to seqan3/utility/views)
      * [x] move to `seqan3/utility/views`
      * [x] https://github.com/seqan/product_backlog/issues/349
    * [x] ./range/views/get.hpp
      * [x] get DEPRECATED use std::views::elements
      * [x] https://github.com/seqan/product_backlog/issues/326
    * [x] ./range/views/interleave.hpp
      * [x] interleave EXPERIMENTAL_API (move to seqan3/utility/views)
      * [x] move to `seqan3/utility/views`
      * [x] https://github.com/seqan/product_backlog/issues/350
    * [x] ./range/views/istreambuf.hpp
      * [x] move to `seqan3/utility/views`
      * [x] https://github.com/seqan/product_backlog/issues/327
    * [x] ./range/views/join.hpp
      * [x] join DEPRECATED use std::views::join or
      * [x] join_view (if a separator is needed) NOAPI as it is currently just an alias for ::ranges::views::join. (this could be in utility)
      * [x] move to `seqan3/utility/views`
      * [x] https://github.com/seqan/product_backlog/issues/351
    * [x] ./range/views/kmer_hash.hpp
      * [x] kmer_hash STABLE_API; move to `seqan3/search/views/kmer_hash.hpp`
      * [x] move to `seqan3/search/views`
      * [x] https://github.com/seqan/product_backlog/issues/344
    * [x] ./range/views/minimiser_hash.hpp
      * [x]  minimiser_hash EXPERIMENTAL_API; move to `seqan3/search/views/minimiser_hash.hpp`
      * [x] move to `seqan3/search/views`
      * [x] https://github.com/seqan/product_backlog/issues/346
    * [x] ./range/views/minimiser.hpp
      * [x]  minimiser STABLE_API; move to `seqan3/include/views/minimiser.hpp`
      * [x] move to `seqan3/search/views`
      * [x] https://github.com/seqan/product_backlog/issues/345
    * [x] ./range/views/move.hpp
      * [x]  move DEPRECATED
      * [x] https://github.com/seqan/product_backlog/issues/328
    * [x] ./range/views/pairwise_combine.hpp
      * [x] pairwise_combine STABLE_API  (move to seqan3/utility/views and mark it NOAPI)
      * [x] move to `seqan3/utility/views`
      * [x] https://github.com/seqan/product_backlog/issues/352
    * [x] ./range/views/persist.hpp (https://github.com/seqan/product_backlog/issues/307)
      * [x] persist DEPRECATED when used internally use `detail::persist_fn` 
      * [x] move to core/detail/persist_view.hpp (for internal use only)
      * [x] TODO: use case; enrico had vague memories that std::views::reverse had some problems 
      * [x] https://github.com/seqan/product_backlog/issues/329
    * [x] ./range/views/rank_to.hpp
      * [x] rank_to STABLE_API (move to `include/alphabet/views/`)
      * [x] move to `seqan3/alphabet/views`
      * [x] https://github.com/seqan/product_backlog/issues/337
    * [x] ./range/views/repeat.hpp
      * [x] repeat EXPERIMENTAL_API
      * [x] move to `seqan3/utility/views`
      * [x] https://github.com/seqan/product_backlog/issues/353
    * [x] ./range/views/repeat_n.hpp
      * [x] repeat_n EXPERIMENTAL_API
      * [x] move to `seqan3/utility/views`
      * [x] https://github.com/seqan/product_backlog/issues/354
    * [x] ./range/views/single_pass_input.hpp
      * [x] single_pass_input EXPERIMENTAL_API
      * [x] move to `seqan3/utility/views`
      * [x] https://github.com/seqan/product_backlog/issues/360
    * [x] ./range/views/slice.hpp
      * [x] slice EXPERIMENTAL_API
      * [x] move to `seqan3/utility/views`
      * [x] https://github.com/seqan/product_backlog/issues/361
    * [x] ./range/views/take_exactly.hpp
      * [x] take_exactly DEPRECATED
      * [x] take_exactly_or_throw DEPRECATED
      * [x] https://github.com/seqan/product_backlog/issues/331
    * [x] ./range/views/take.hpp
      * [x] take DEPRECATED use std::views::take
      * [x] https://github.com/seqan/product_backlog/issues/330
    * [x] ./range/views/take_line.hpp
      * [x] take_line DEPRECATED, there is no "easy" replacement
      * [x] see take_until resolution
      * [x] https://github.com/seqan/product_backlog/issues/359
    * [x] ./range/views/take_until.hpp `take_until(pred) == take_while(!pred)` where do they stop?
      * [x] move complete header to include/seqan3/io/detail/take_until.hpp as it is primarily used in io;
      * [x] use class internal instances of `detail::take_until_fn<false, false> take_until*` in IO in place of `seqan3::views::take_until*` ASK marcel if you don't understand this sentence xD
      * [x] take_until DEPRECATED is the as std::views::take_while(!pred)
      * [x] take_until_or_throw DEPRECATED, there is no "easy" replacement
      * [x] take_until_and_consume DEPRECATED, there is no "easy" replacement
      * [x] take_until_or_throw_and_consume DEPRECATED, there is no "easy" replacement
      * [x] https://github.com/seqan/product_backlog/issues/332
    * [x] ./range/views/to_char.hpp
      * [x] to_char STABLE_API (move to `include/alphabet/views/`)
      * [x] move to `seqan3/alphabet/views`
      * [x] https://github.com/seqan/product_backlog/issues/338
    * [x] ./range/views/to.hpp
      * [x] to NOAPI as it is currently just an alias for ::ranges::views::to.  (this could be in utility)
      * [x] move to `seqan3/utility/views`
      * [x] https://github.com/seqan/product_backlog/issues/355
    * [x] ./range/views/to_lower.hpp
      * [x] to_lower DEPRECATED
      * [x] https://github.com/seqan/product_backlog/issues/333
    * [x] ./range/views/to_rank.hpp
      * [x] to_rank STABLE_API (move to `include/alphabet/views/`)
      * [x] https://github.com/seqan/product_backlog/issues/339
    * [x] ./range/views/to_upper.hpp
      * [x] to_upper DEPRECATED
      * [x] https://github.com/seqan/product_backlog/issues/334
    * [x] ./range/views/translate.hpp
      * [x] translate EXPERIMENTAL_API (move to `alphabet/views/translate.hpp`)
      * [x] translate_single EXPERIMENTAL_API (move to `alphabet/views/translate_single.hpp`)
      * [x] move to `seqan3/alphabet/views`
      * [x] https://github.com/seqan/product_backlog/issues/340
    * [x] ./range/views/translate_join.hpp
      * [x] translate_join EXPERIMENTAL_API (move to `alphabet/views/translate_join.hpp`)
      * [x] move to `seqan3/alphabet/views`
      * [x] https://github.com/seqan/product_backlog/issues/341
    * [x] ./range/views/trim_quality.hpp
      * [x] trim_quality EXPERIMENTAL_API (move to `alphabet/views/`)
      * [x] move to `seqan3/alphabet/views`
      * [x] https://github.com/seqan/product_backlog/issues/342
    * [x] ./range/views/type_reduce.hpp
      * [x] type_reduce EXPERIMENTAL_API
      * [x] move to `seqan3/utility/views`
      * [x] rename `seqan3::type_reduce_view` to `seqan3::views::type_reduce_t` 
      * [x] https://github.com/seqan/product_backlog/issues/356
    * [x] ./range/views/zip.hpp
      * [x] zip NOAPI as it is currently just an alias for ::ranges::views::zip.  (this could be in utility)
      * [x] move to `seqan3/utility/views`
      * [x] https://github.com/seqan/product_backlog/issues/357

**Comment by marehr** [comment]
### Core Meeting: 2021-01-27

Things to smooth:
* [ ] We currently have `inline auto const drop = ...;` and `inline constexpr auto`, we should change all occurrences to `inline constexpr auto`.
* [x] static_assert within `std::views::transform` makes trouble consider removing them or making them a requirement
  * it turned out that gcc-11 did some stupid things in 11.0 that could get fixed until 11.1
