### ISSUE TITLE
Some minor changes to `version.hpp`

### ISSUE THREAD

**Issue by smehringer** [seqan/product_backlog#277]
### Description 

Some minor changes to `version.hpp`

### Acceptance Criteria

- [x] `seqan3_version` should be changed to have the same meaning as the macro `SEQAN3_VERSION`
- [x] `seqan3_version_cstring` is the old `seqan3_version`, but as cstring (we need some macro vodoo to build that)
- [x] `version.hpp` should not include any other header
- [x] `platform.hpp` should include `version.hpp`

### Tasks

Tasks can be done in separate PRs.

- [x] Change `seqan3_version` to be the constexpr variable of `SEQAN3_VERSION` (a number) and not a version string. (https://github.com/seqan/seqan3/pull/2350)
- [x] Add `seqan3_version_cstring` (old `seqan3_version`), as cstring (not a std::string) (https://github.com/seqan/seqan3/pull/2350)
- [x] Remove all header includes of `version.hpp` (if not possible, report back to core)
- [x]  include `version.hpp` in`platform.hpp` 

### Definition of Done

- [x] Tasks are all done

**Comment by SGSSGene** [comment]
Adjustment of `seqan3_version` and `seqan3_version_cstring` can be found here: https://github.com/seqan/seqan3/pull/2350

**Comment by marehr** [comment]
Fixed by https://github.com/seqan/seqan3/pull/2358
