### ISSUE TITLE
[DOC] Update API stability documentation

### ISSUE THREAD

**Issue by smehringer** [seqan/product_backlog#279]
### Description 

We already document some stuff about API stability here: http://docs.seqan.de/seqan/3-master-user/about_api.html
But this needs to be updated after the [Core meeting 11.01.2020](https://github.com/seqan/product_backlog/issues/274#issuecomment-757925878).

### Tasks

- [x] Add the doxygen tags `\experimental`
  - [x] `\noapi` (already exists),
  - [x] `\experimentalapi` (currently \experimental),
  - [x] `\stableapi` (must be added)
- [x] Update the documentation on API stability (http://docs.seqan.de/seqan/3-master-user/about_api.html) to reflect what we have decided on in [Core meeting 11.01.2020](https://github.com/seqan/product_backlog/issues/274#issuecomment-757925878) (https://github.com/seqan/seqan3/pull/2878)
- [x] Also add badge to typedefs

Other nice to have features are tracked in https://github.com/seqan/product_backlog/issues/409

**Comment by eseiler** [comment]
Check if we can mark a group `\noapi` and propagate this to all entities within the group

**Comment by eseiler** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Write about API stability https://github.com/seqan/product_backlog/issues/279](https://trello.com/c/7NQpGIoj/35-write-about-api-stability-https-githubcom-seqan-productbacklog-issues-279)
