### ISSUE TITLE
Adapt the search interface such that it unifies the search on a text collection and a single text such that users don't have to change their code when switching from single text to text collections and vice versa.

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#28]
### Description 

Remove the text layout from the indices.
Make the search return a result that offers all information independent of a text collection or a single text

### Acceptance Criteria

- [x] switching from a single text to a text collection does not change the result type and code won't break

### Tasks

 

- [x] return a search result object instead of positions or pairs of positions. (see seqan/seqan3#1434)

### Definition of Done

- [x] Implementation and design approved
- [x] Unit tests pass
- [x] Test coverage = 100%
- [x] API documentation added
- [x] Tutorial/teaching material added
- [x] Test suite compiles in less than 30 seconds (on travis)
- [x] Changelog entry added

**Comment by rrahn** [comment]
NOTE from seqan/seqan3#1596: The performance drops by roughly 10% if we search for `std::vector<dna4_vector>` instead of `dna4_vector`...

**Comment by rrahn** [comment]
In general fixed by #1706. The different index text layouts can be tackled later when we have macro benchmarks. @smehringer can you please split this issue and close the part that is fixed?

**Comment by smehringer** [comment]
Follow up issue on the internal design: #105
