### ISSUE TITLE
[I/O] Deprecate seqan3::field::seq_qual

### ISSUE THREAD

**Issue by smehringer** [seqan/product_backlog#280]
### Description 

The `seqan3::field::seq_qual` field is a feature that is not really related to the IO itself. It increases complexity of I/O for a specific use case that can be handled outside of the I/O. E.g. alternatively you can use a `seqan3::views::zip` and a `std::views::transform`.

We also asked external users (Sara and Tobias) if they currently use this feature.
Sara does not use it (lambda).
Tobias uses it but would be fine with an alternative.

See [google doc comment](https://docs.google.com/document/d/1EuGAtT0X5tDbBNFdHeuRfU2RRVOne8CSOJt3lI0U5UY/edit#bookmark=id.p5j5fcijpqxf) for a reference.

### Tasks

- [ ] Deprecate the `seqan3::field::seq_qual`
- [ ] Wrap all usages of `seqan3::field::seq_qual` in `seqan3/include/io/sequence_file` in pragma warnings
     ```cpp
    #pragma GCC diagnostic push // avoid deprecation warning of field::seq_qual
    #pragma GCC diagnostic ignored "-Wdeprecated-declarations"
    // ... code that uses seq_qual 
    #pragma GCC diagnostic pop // "-Wdeprecated-declarations" 
     ```
- [ ] Remove snippets and respective documentation of this feature in include directory
- [ ] Tutorial: If there is a section just on "How to read seq_qual" remove it. But check if there might be a good place where one can incorporate an alternative example, e.g. "you can zip seq and qual for further analysis or transform it into a qualified alphabet".
- [ ] Add a cookbook entry that shows how to store the sequence and quality information within a signle `std::vector<qualified<dna4, phred42>>` (should be possible with a zip and transform view). (without using sequence IO)
- [ ] Add a changelog entry that either shows the code from the cookbook, if it is just 1-3 lines, or references the cookbook entry.

**Comment by tloka** [comment]
As @smehringer asked for a short snippet how I am currently using the `seq_qual` field.
Currently, I only use it for fastq output. I had to create some minimal example from my more complex code base and didn't test it separately, sorry if there are some minor errors (shouldn't be too relevant here, though):
```c++
// Create file stream
using fout_type = seqan3::sequence_file_output<
                    seqan3::fields<seqan3::field::seq_qual, seqan3::field::id>, 
                    seqan3::type_list<seqan3::format_fastq>>;
fout_type fastq_stream("output_file.fq");

// Create a sequence
std::vector<seqan3::qualified<seqan3::dna5, seqan3::phred42>> sequence;
// [assume sequence vector is getting filled]

// Only a subsequence will be written to the output file, so create a view
auto subsequence = sequence | seqan3::views::slice(0, 50);

std::string id = "Read 1";

// Now, I can simply do this to write the subsequence to the output stream
fastq_stream.emplace_back(subsequence, id);
``` 

I guess, once the seq_qual field is removed it would simply look like this:
```c++
// Create file stream
using fout_type = seqan3::sequence_file_output<
                    seqan3::fields<seqan3::field::seq, seqan3::field::qual, seqan3::field::id>, 
                    seqan3::type_list<seqan3::format_fastq>>;
fout_type fastq_stream("output_file.fq");

// Create a sequence
std::vector<seqan3::qualified<seqan3::dna5, seqan3::phred42>> sequence;
// [assume sequence vector is getting filled]

// Only a subsequence will be written to the output file, so create a view
auto subsequence = sequence | seqan3::views::slice(0, 50);

std::string id = "Read 1";

// Create separate views for sequence and quality
auto subsequence_seq = subsequence | seqan3::views::get<0>;
auto subsequence_qual = subsequence | seqan3::views::get<1>;

// Write the sequence and quality separately to the file stream
fastq_stream.emplace_back(subsequence_seq, subsequence_qual, id);
``` 

I know this could be simplified by concatenating `seqan3::views::slice` and `seqan3::views::get`, but I wanted to stay as similar as possible to the structure used to write the sequence using the seq_qual field.

**Comment by marehr** [comment]
@SGSSGene is this done?

**Comment by SGSSGene** [comment]
Yes, this is done!
