### ISSUE TITLE
[Alignment]  Deprecate `seqan3::alignment_coordinate`

### ISSUE THREAD

**Issue by smehringer** [seqan/product_backlog#282]
### Description 

Discussed in https://github.com/seqan/product_backlog/issues/268#issuecomment-762179494

The `seqan3::alignment_result` provides single functions for begin and end positions, so a public coordinate is not needed anymore.

### Tasks

- [x] Add `SEQAN3_DEPRECATED_310` macro to the `seqan3::alignment_coordinate` class
- [x] Add `[DEPREACTED]` in front of the brief message of `seqan3::alignment_coordinate`
- [x] Add the `\deprecated` doxygen tag to the class brief
- [x] Remove snippets used in the documentation
- [x] Check any mentions in the tutorials and remove them

Note: **Do not delete the tests** yet. This can be done if the entity is removed. Instead, wrap the (respective) tests and all other possible usage in
```cpp
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
  
#pragma GCC diagnostic pop
```

**Comment by SGSSGene** [comment]
Currently I am stuck with fixing alignment_fixture in [test/unit/alignment/pairwise/fixture/alignment_fixture.hpp](https://github.com/seqan/seqan3/blob/4f974dbdc884194ed20c824e7c74f18dd9c7605d/test/unit/alignment/pairwise/fixture/alignment_fixture.hpp#L64-L67)
It uses `seqan3::alignment_coordinate` and I don't know what I should replace it with.

**Comment by marehr** [comment]
I took over and finished this :)
