### ISSUE TITLE
[Alignment] Deprecate seqan3::gap_scheme

### ISSUE THREAD

**Issue by smehringer** [seqan/product_backlog#283]
### Description 

Discussed in https://github.com/seqan/product_backlog/issues/268

The gap scheme is not needed anymore since we handle the configuration of gap costs differently

- [x] Add `SEQAN3_DEPRECATED_310` macro to the `seqan3::gap_scheme` class

was done already but the documentation does not show it.

### Tasks

- [x] Add `[DEPREACTED]` in front of the brief message of `seqan3::gap_scheme`
- [x] Add the `\deprecated` doxygen tag to the class brief
- [x] Check any mentions in the tutorials and remove them

**Comment by SGSSGene** [comment]
Open: Is the complete gap_scheme.hpp file with all the other structs also deprecated?

**Comment by marehr** [comment]
@SGSSGene Can this be closed? Did you check the tutorials? ❤️
