### ISSUE TITLE
Migrate website content and style to github pages.

### ISSUE THREAD

**Issue by simonsasse** [seqan/product_backlog#285]
### Description 

Migrate the website to github pages.
The current state: https://github.com/marehr/www.seqan.de/
The original website: www.seqan.de

### Benefits

- security
- speed
- maintenance 

### Tasks

- [x] basic framework (https://github.com/marehr/www.seqan.de/)
- [ ] People's pages
- [ ] Posts/news
- [ ] Applications
- [ ] Publications
- [ ] create subpages for links on home (data structures, workflows, parrallelization, i/o, apps, workflows)
- [ ] make people, applications and publications collapsible or add sub pages
- [ ] redirect domain to github page

**Comment by marehr** [comment]
Automatically fetch http://publications.imp.fu-berlin.de/view/divisions/group=5Falgbioinf.html bibtex and generate publication site.
