### ISSUE TITLE
Make SEQAN3_CPO_IMPL more explicit and easier to understand.

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#298]
### Description 

Currently, we define a customisation point object like this

```c++
SEQAN3_CPO_IMPL(2, seqan3::custom::alphabet<decltype(v)>::to_rank(v))    // explicit customisation
SEQAN3_CPO_IMPL(1, to_rank(v)                                       )    // ADL
SEQAN3_CPO_IMPL(0, v.to_rank()                                      )    // member
```

it hides the semantics what the CPO overload does.

A new proposal is to make it look like this:

```c++
template <typename alphabet_t>
static constexpr auto SEQAN3_CPO_OVERLOAD(priority_tag<2>, alphabet_t && alphabet)
(
    /*return*/ seqan3::custom::alphabet<alphabet_t>::to_rank(std::forward<alphabet_t>(alphabet)) /*;*/
);

template <typename alphabet_t>
static constexpr auto SEQAN3_CPO_OVERLOAD(priority_tag<1>, alphabet_t && alphabet)
(
    /*return*/ to_rank(std::forward<alphabet_t>(alphabet)) /*;*/
);

template <typename alphabet_t>
static constexpr auto SEQAN3_CPO_OVERLOAD(priority_tag<0>, alphabet_t && alphabet)
(
    /*return*/ std::forward<alphabet_t>(alphabet).to_rank() /*;*/
);
```

This makes it easier to see that SEQAN3_CPO_IMPL is a static function declaration, makes the arguments of the function visible and the definition ends with a `;` (code formatter and reducer have a hard time understanding non-semicolon macro statements). And since it looks more like a function we can also add individual documentation.

### Acceptance Criteria

- [ ] test 1
- [ ] test 2
- [ ] test 3

### Tasks

 

- [ ] task 1
- [ ] task 2
- [ ] task 3

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by marehr** [comment]
Todo after merges of seqan/seqan3#2471 - seqan/seqan3#2487:
* [x] This either has to be `check 1 out of 3` or `1st out of 3 checks` or `first out of 3/three checks` 
 `1.` is German and not used in English to describe `first`
* [x] Dot in `(Needed to defer instantiation for incomplete types.)` (See https://github.com/seqan/seqan3/pull/2480#discussion_r600420912)
* [x] static free/member https://github.com/seqan/seqan3/pull/2475#discussion_r601694602
