### ISSUE TITLE
Improve the documentation for the search module

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#30]
### Description 

The landing pages of the submodules should provide a detailed overview over the functionality contained in the module and how it is used with examples and proper visualisation.

### Acceptance Criteria

- [ ] user has all information about the search module available on the landing page of the module.

### Tasks

 

- [ ] update/refine the module landing page

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
