### ISSUE TITLE
[FEATURE] Move the VCF parser of iGenVar to the seqan3 library

### ISSUE THREAD

**Issue by Irallia** [seqan/product_backlog#302]
### Description 

As we discussed, we want to have a VCF parser in our IO module. But as the IO resturcturing is not done, we created one in the [iGenVar](https://github.com/seqan/iGenVar) project. With this, it is still open, to move this parser to the library of seqan3.
The coded parser is here: https://github.com/seqan/iGenVar/blob/master/include/variant_parser/variant_record.hpp

### Acceptance Criteria

At the end, we would like to use this seqan3 VCF parser in the iGenVar project. You can use some code there to test the parser. Furthermore, the iGenVar tests should still run without errors.

### Tasks

- [ ] Copy the code from iGenVar and adapt it to the seqan3 standards and structures
- [ ] Write some tests
- [ ] Replace the module in iGenVar and possibly adjust the module in iGenVar. All tests should still run.

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
