### ISSUE TITLE
Doxygen 1.9.2 support

### ISSUE THREAD

**Issue by eseiler** [seqan/product_backlog#303]
### Reported bugs

* [x] Markdown HTML parsing break when parsing quotes (https://github.com/doxygen/doxygen/issues/8529) (https://github.com/seqan/seqan3/pull/2585)
* [x] Warnings when using `\if` (https://github.com/doxygen/doxygen/issues/8642)
* [x] Todos cause warnings (https://github.com/doxygen/doxygen/issues/8709)

### Fixed issues

* [x] Mismatching template parameters (https://github.com/seqan/seqan3/pull/2505)
* [x] Escape `#` (https://github.com/seqan/seqan3/pull/2762)

### Tasks

 

- Monitor the [nightly documentation builds](https://cdash.seqan.de/index.php?project=SeqAn3#!#documentation). These are build with the master branch of doxygen.
- If there is an error, investigate it and either report it upstream or adjust our documentation.

### Definition of Done

- [ ] doxygen 1.9.2 is released and works with our documentation.
