### ISSUE TITLE
As a python binding writer I want dynamic search configurations so I can handle the different configurations with runtime dispatching.

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#31]
### Description 

It is easier to handle different search configuration that depend on some runtime property when they can be set at runtime. Otherwise one has to always provide nested continuation interfaces that makes it very tedious to write code.

Also see: seqan/seqan3#1580  seqan/seqan3#1459 seqan/seqan3#1581

Which search configurations are affected?

* `mode`
* `error` and `error_rate`? Does programs set different combinations of indels and substitutions?

`result` must be static.

How would that look like? 

See  https://gist.github.com/rrahn/16f2113015d39b55f5d89e0265f61f1c for a possible candidate on the implementation.

### Acceptance Criteria

- [ ] the mode can be set at runtime depending on a runtime decision
- [ ] the error can be set dynamically depending on a runtime decision
- [ ] if wanted also a static option is possible to reduce compile time.

### Tasks

 

- [ ] prototype a version for the dynamic configuration
- [ ] add a dynamic configuration mechanism to the search configuration

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by rrahn** [comment]
Will be implemented as part of #65
