### ISSUE TITLE
rename seqan3::sam_dna16 to seqan3::dna16sam

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#312]
### Tasks

- [x] apply patch and use that as basis
- [x] rename seqan3::sam_dna16 to seqan3::dna16sam
- [x] rename header (old header `sam_dna16.hpp` should be deprecated as we did with the utility move (see https://github.com/seqan/seqan3/commit/dc7862cd0010ae80d2faf001c47bcbdc944a3807)
- [x] add type alias with deprecation for seqan3::sam_dna16
- [x] add changelog entry

```patch
From 219ebb2039e070e5c707792b4cb8945b124aba17 Mon Sep 17 00:00:00 2001
From: marehr <marehr-github@marehr.dialup.fu-berlin.de>
Date: Mon, 22 Mar 2021 16:12:58 +0100
Subject: [PATCH 02/12] TODO: [MISC] rename seqan3::sam_dna16 to
 seqan3::dna16sam

---
 include/seqan3/alphabet/nucleotide/sam_dna16.hpp | 13 +++++++++++--
 1 file changed, 11 insertions(+), 2 deletions(-)

diff --git a/include/seqan3/alphabet/nucleotide/sam_dna16.hpp b/include/seqan3/alphabet/nucleotide/sam_dna16.hpp
index 4dc23363e..90c7c2d47 100644
--- a/include/seqan3/alphabet/nucleotide/sam_dna16.hpp
+++ b/include/seqan3/alphabet/nucleotide/sam_dna16.hpp
@@ -41,6 +41,8 @@ namespace seqan3
  * therefore set to 'N'.
  *
  * \include test/snippet/alphabet/nucleotide/sam_dna16.cpp
+ *
+ * \stableapi{Since version 3.1.}
  */
-class sam_dna16 : public nucleotide_base<sam_dna16, 16>
+class dna16sam : public nucleotide_base<dna16sam, 16>
 {
@@ -139,8 +141,11 @@ private:
 // containers
 // ------------------------------------------------------------------
 
-//!\brief Alias for an std::vector of seqan3::sam_dna16.
-//!\relates sam_dna16
+/*!\brief Alias for an std::vector of seqan3::sam_dna16.
+ * \relates sam_dna16
+ * \details
+ * \stableapi{Since version 3.1.}
+ */
 using sam_dna16_vector = std::vector<sam_dna16>;
 
 // ------------------------------------------------------------------
@@ -155,6 +160,8 @@ using sam_dna16_vector = std::vector<sam_dna16>;
  * \relates seqan3::sam_dna16
  * \returns seqan3::sam_dna16
  * \param[in] c The character to assign from.
+ * \details
+ * \stableapi{Since version 3.1.}
  */
 constexpr sam_dna16 operator""_sam_dna16(char const c) noexcept
 {
@@ -170,6 +177,8 @@ constexpr sam_dna16 operator""_sam_dna16(char const c) noexcept
  * You can use this string literal to easily assign to seqan3::sam_dna16_vector:
  *
  * \include test/snippet/alphabet/nucleotide/sam_dna16_literal.cpp
+ *
+ * \stableapi{Since version 3.1.}
  */
 inline sam_dna16_vector operator""_sam_dna16(char const * s, size_t n)
 {
-- 
2.31.1
```
