### ISSUE TITLE
rename phred68{legacy,solexa}

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#315]
### Tasks

- [x] apply patch and use that as basis
- [x] rename seqan3::phred68legacy to seqan3::phred68solexa
- [x] rename header (old header `phred68legacy.hpp` should be deprecated as we did with the utility move (see https://github.com/seqan/seqan3/commit/dc7862cd0010ae80d2faf001c47bcbdc944a3807)
- [x] add type alias with deprecation for seqan3::phred68legacy
- [x] add changelog entry

```patch
From 8cba27dea8e139d9ce72da4ba6cbbc888ceb2f80 Mon Sep 17 00:00:00 2001
From: marehr <marehr-github@marehr.dialup.fu-berlin.de>
Date: Mon, 22 Mar 2021 16:13:49 +0100
Subject: [PATCH 06/12] TODO: [MISC] rename phred68{legacy,solexa}

---
 .../seqan3/alphabet/quality/phred68legacy.hpp    | 16 ++++++++++++++--
 1 file changed, 14 insertions(+), 2 deletions(-)

diff --git a/include/seqan3/alphabet/quality/phred68legacy.hpp b/include/seqan3/alphabet/quality/phred68legacy.hpp
index 26e89e817..f265e74c4 100644
--- a/include/seqan3/alphabet/quality/phred68legacy.hpp
+++ b/include/seqan3/alphabet/quality/phred68legacy.hpp
@@ -33,6 +33,8 @@ namespace seqan3
  * the Illumina [1.0;1.8[ standard.
  *
  * \include test/snippet/alphabet/quality/phred68legacy.cpp
+ *
+ * \stableapi{Since version 3.1.}
  */
-class phred68legacy : public quality_base<phred68legacy, 68>
+class phred68solexa : public quality_base<phred68solexa, 68>
 {
@@ -70,10 +72,16 @@ public:
     /*!\name Member variables.
      * \{
      */
-    //!\brief The projection offset between Phred and rank score representation.
+    /*!\brief The projection offset between Phred and rank score representation.
+     * \details
+     * \stableapi{Since version 3.1.}
+     */
     static constexpr phred_type offset_phred{-5};
 
-    //!\brief The projection offset between char and rank score representation.
+    /*!\brief The projection offset between char and rank score representation.
+     * \details
+     * \stableapi{Since version 3.1.}
+     */
     static constexpr char_type offset_char{';'};
     //!\}
 };
@@ -84,6 +92,8 @@ public:
 /*!\brief The seqan3::phred68legacy char literal.
  * \relates seqan3::phred68legacy
  * \returns seqan3::phred68legacy
+ * \details
+ * \stableapi{Since version 3.1.}
  */
 constexpr phred68legacy operator""_phred68legacy(char const c) noexcept
 {
@@ -99,6 +109,8 @@ constexpr phred68legacy operator""_phred68legacy(char const c) noexcept
  * You can use this string literal to easily assign to std::vector<seqan3::phred68legacy>:
  *
  * \include test/snippet/alphabet/quality/phred68legacy_literal.cpp
+ *
+ * \stableapi{Since version 3.1.}
  */
 inline std::vector<phred68legacy> operator""_phred68legacy(char const * s, std::size_t n)
 {
-- 
2.31.1
```
