### ISSUE TITLE
deprecate phred_type constructor

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#316]
### Tasks

- [x] deprecate phred_type constructor
- [x] remove usage from our tests/snippets
- [x] add changelog entry

```patch
From 850ebec5bd3d6d39c8a45dc9ef963d43b3313373 Mon Sep 17 00:00:00 2001
From: marehr <marehr-github@marehr.dialup.fu-berlin.de>
Date: Wed, 14 Apr 2021 11:47:02 +0200
Subject: [PATCH 05/12] TODO: [MISC] deprecate phred_type constructor

---
 include/seqan3/alphabet/quality/phred42.hpp       | 5 ++++-
 include/seqan3/alphabet/quality/phred63.hpp       | 5 ++++-
 include/seqan3/alphabet/quality/phred68legacy.hpp | 5 ++++-
 include/seqan3/alphabet/quality/phred94.hpp       | 5 ++++-
 include/seqan3/alphabet/quality/quality_base.hpp  | 5 ++++-
 5 files changed, 20 insertions(+), 5 deletions(-)

diff --git a/include/seqan3/alphabet/quality/phred42.hpp b/include/seqan3/alphabet/quality/phred42.hpp
index c0ee38782..fc39256f7 100644
--- a/include/seqan3/alphabet/quality/phred42.hpp
+++ b/include/seqan3/alphabet/quality/phred42.hpp
@@ -66,7 +66,10 @@ public:
     constexpr phred42 & operator=(phred42 &&)       noexcept = default; //!< Defaulted.
     ~phred42()                                      noexcept = default; //!< Defaulted.
 
-    //!\brief Construct from Phred score value.
+    /*!\brief Allow construction from the Phred score value.
+     * \details
+     * \deprecated This will be removed in 3.1.0. Please use seqan3::phred42::assign_phred() or '!'_phred42.
+     */
     constexpr phred42(phred_type const p) : base_t{p} {}
 
     // Inherit converting constructor
diff --git a/include/seqan3/alphabet/quality/phred63.hpp b/include/seqan3/alphabet/quality/phred63.hpp
index 06ddfb590..45d402b6e 100644
--- a/include/seqan3/alphabet/quality/phred63.hpp
+++ b/include/seqan3/alphabet/quality/phred63.hpp
@@ -66,7 +66,10 @@ public:
     constexpr phred63 & operator=(phred63 &&)       noexcept = default; //!< Defaulted.
     ~phred63()                                      noexcept = default; //!< Defaulted.
 
-    //!\brief Construct from Phred score value.
+    /*!\brief Allow construction from the Phred score value.
+     * \details
+     * \deprecated This will be removed in 3.1.0. Please use seqan3::phred63::assign_phred() or '!'_phred63.
+     */
     constexpr phred63(phred_type const p) : base_t{p} {}
 
     // Inherit converting constructor
diff --git a/include/seqan3/alphabet/quality/phred68legacy.hpp b/include/seqan3/alphabet/quality/phred68legacy.hpp
index 47f7dace6..26e89e817 100644
--- a/include/seqan3/alphabet/quality/phred68legacy.hpp
+++ b/include/seqan3/alphabet/quality/phred68legacy.hpp
@@ -57,7 +57,10 @@ public:
     constexpr phred68legacy & operator=(phred68legacy &&)       noexcept = default; //!< Defaulted.
     ~phred68legacy()                                            noexcept = default; //!< Defaulted.
 
-    //!\brief Construct from Phred score value.
+    /*!\brief Allow construction from the Phred score value.
+     * \details
+     * \deprecated This will be removed in 3.1.0. Please use seqan3::phred68legacy::assign_phred() or '!'_phred68legacy.
+     */
     constexpr phred68legacy(phred_type const p) : base_t{p} {}
 
     // Inherit converting constructor
diff --git a/include/seqan3/alphabet/quality/phred94.hpp b/include/seqan3/alphabet/quality/phred94.hpp
index 49682a3bb..7229f686d 100644
--- a/include/seqan3/alphabet/quality/phred94.hpp
+++ b/include/seqan3/alphabet/quality/phred94.hpp
@@ -63,7 +63,10 @@ public:
     constexpr phred94 & operator=(phred94 &&)       noexcept = default; //!< Defaulted.
     ~phred94()                                      noexcept = default; //!< Defaulted.
 
-    //!\brief Construct from Phred score value.
+    /*!\brief Allow construction from the Phred score value.
+     * \details
+     * \deprecated This will be removed in 3.1.0. Please use seqan3::phred94::assign_phred() or '!'_phred94.
+     */
     constexpr phred94(phred_type const p) : base_t{p} {}
 
     // Inherit converting constructor
diff --git a/include/seqan3/alphabet/quality/quality_base.hpp b/include/seqan3/alphabet/quality/quality_base.hpp
index cfd444d4b..6f7d01699 100644
--- a/include/seqan3/alphabet/quality/quality_base.hpp
+++ b/include/seqan3/alphabet/quality/quality_base.hpp
@@ -57,7 +57,10 @@ private:
     constexpr quality_base & operator=(quality_base &&)       noexcept = default; //!< Defaulted.
     ~quality_base()                                           noexcept = default; //!< Defaulted.
 
-    //!\brief Allow construction from the Phred score value.
+    /*!\brief Allow construction from the Phred score value.
+     * \details
+     * \deprecated This will be removed in 3.1.0. Please use, e.g., seqan3::phred42{}.assign_phred(p) or '!'_phred42.
+     */
     constexpr quality_base(phred_type const p) noexcept
     {
         static_cast<derived_type *>(this)->assign_phred(p);
-- 
2.31.1
```
