### ISSUE TITLE
aminoacid_scoring_scheme: lower case  member constants

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#317]
### Tasks

- [x] apply patch and use that as basis
- [x] lower case `seqan3::aminoacid_similarity_matrix::BLOSUM*`
- [x] add deprecation for upper case ([see for an example](https://github.com/seqan/seqan3/blob/d543d6ccc20195e5b7459f0eedfa49e7e4321663/include/seqan3/io/record.hpp#L113))
- [x] add changelog entry

```patch
From 6c99f913a107d8271954c01ce3ec1255ae57b5b0 Mon Sep 17 00:00:00 2001
From: marehr <marehr-github@marehr.dialup.fu-berlin.de>
Date: Tue, 23 Mar 2021 00:27:32 +0100
Subject: [PATCH 07/12] TODO: [MISC] aminoacid_scoring_scheme: lower case
 member constants

---
 .../scoring/aminoacid_scoring_scheme.hpp         | 16 ++++++++--------
 1 file changed, 8 insertions(+), 8 deletions(-)

diff --git a/include/seqan3/alignment/scoring/aminoacid_scoring_scheme.hpp b/include/seqan3/alignment/scoring/aminoacid_scoring_scheme.hpp
index 2e81b6b7f..72f877341 100644
--- a/include/seqan3/alignment/scoring/aminoacid_scoring_scheme.hpp
+++ b/include/seqan3/alignment/scoring/aminoacid_scoring_scheme.hpp
@@ -35,26 +35,26 @@ namespace seqan3
 enum class aminoacid_similarity_matrix
 {
     //ATTENTION: when you change this, also update set_similarity_matrix() below
-    /*!\brief The BLOSUM30 matrix for very distantly related proteins.
+    /*!\brief The blosum30 matrix for very distantly related proteins.
      * \details
      * \snippet include/seqan3/alignment/scoring/aminoacid_scoring_scheme.hpp matrix_data blosum30
      */
-    BLOSUM30,
-    /*!\brief The BLOSUM45 matrix for distantly related proteins.
+    blosum30,
+    /*!\brief The blosum45 matrix for distantly related proteins.
      * \details
      * \snippet include/seqan3/alignment/scoring/aminoacid_scoring_scheme.hpp matrix_data blosum45
      */
-    BLOSUM45,
-    /*!\brief The BLOSUM62 matrix recommended for most use-cases.
+    blosum45,
+    /*!\brief The blosum62 matrix recommended for most use-cases.
      * \details
      * \snippet include/seqan3/alignment/scoring/aminoacid_scoring_scheme.hpp matrix_data blosum62
      */
-    BLOSUM62,
-    /*!\brief The BLOSUM80 matrix for closely related proteins.
+    blosum62,
+    /*!\brief The blosum80 matrix for closely related proteins.
      * \details
      * \snippet include/seqan3/alignment/scoring/aminoacid_scoring_scheme.hpp matrix_data blosum80
      */
-    BLOSUM80
+    blosum80
 };
 
 /*!\brief A data structure for managing and computing the score of two amino acids.
-- 
2.31.1
```
