### ISSUE TITLE
translate: lower case translation_frames constants

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#319]
### Tasks

- [x] apply patch and use that as basis
- [x] lower case `seqan3::translation_frames::*FRAME*`
- [x] add deprecation for upper case ([see for an example](https://github.com/seqan/seqan3/blob/d543d6ccc20195e5b7459f0eedfa49e7e4321663/include/seqan3/io/record.hpp#L113))
- [ ] add changelog entry

```patch
From 41cc4905c38192daafd6c7148074639befd7cf64 Mon Sep 17 00:00:00 2001
From: marehr <marehr-github@marehr.dialup.fu-berlin.de>
Date: Tue, 23 Mar 2021 00:34:11 +0100
Subject: [PATCH 09/12] TODO: [MISC] translate: lower case translation_frames
 constants

---
 include/seqan3/range/views/translate.hpp | 24 ++++++++++++------------
 1 file changed, 12 insertions(+), 12 deletions(-)

diff --git a/include/seqan3/range/views/translate.hpp b/include/seqan3/range/views/translate.hpp
index c9106e01a..d262baf5c 100644
--- a/include/seqan3/range/views/translate.hpp
+++ b/include/seqan3/range/views/translate.hpp
@@ -65,18 +65,18 @@ namespace seqan3
 //!\sa seqan3::enum_bitwise_operators enables combining enum values.
 enum class translation_frames : uint8_t
 {
-    FWD_FRAME_0 = 1,                                    //!< The first forward frame starting at position 0
-    FWD_FRAME_1 = 1 << 1,                               //!< The second forward frame starting at position 1
-    FWD_FRAME_2 = 1 << 2,                               //!< The third forward frame starting at position 2
-    REV_FRAME_0 = 1 << 3,                               //!< The first reverse frame starting at position 0
-    REV_FRAME_1 = 1 << 4,                               //!< The second reverse frame starting at position 1
-    REV_FRAME_2 = 1 << 5,                               //!< The third reverse frame starting at position 2
-    FWD_REV_0 = FWD_FRAME_0 | REV_FRAME_0,              //!< The first forward and first reverse frame
-    FWD_REV_1 = FWD_FRAME_1 | REV_FRAME_1,              //!< The second forward and second reverse frame
-    FWD_REV_2 = FWD_FRAME_2 | REV_FRAME_2,              //!< The first third and third reverse frame
-    FWD = FWD_FRAME_0 | FWD_FRAME_1 | FWD_FRAME_2,      //!< All forward frames
-    REV = REV_FRAME_0 | REV_FRAME_1 | REV_FRAME_2,      //!< All reverse frames
-    SIX_FRAME = FWD | REV                               //!< All frames
+    forward_frame0 = 1, //!< The first forward frame starting at position 0
+    forward_frame1 = 1 << 1, //!< The second forward frame starting at position 1
+    forward_frame2 = 1 << 2, //!< The third forward frame starting at position 2
+    reverse_frame0 = 1 << 3, //!< The first reverse frame starting at position 0
+    reverse_frame1 = 1 << 4, //!< The second reverse frame starting at position 1
+    reverse_frame2 = 1 << 5, //!< The third reverse frame starting at position 2
+    forward_reverse0 = forward_frame0 | reverse_frame0, //!< The first forward and first reverse frame
+    forward_reverse1 = forward_frame1 | reverse_frame1, //!< The second forward and second reverse frame
+    forward_reverse2 = forward_frame2 | reverse_frame2, //!< The first third and third reverse frame
+    forward_frames = forward_frame0 | forward_frame1 | forward_frame2, //!< All forward frames
+    reverse_frames = reverse_frame0 | reverse_frame1 | reverse_frame2, //!< All reverse frames
+    six_frames = forward_frames | reverse_frames //!< All frames
 };
 
 //!\cond DEV
-- 
2.31.1
```
