### ISSUE TITLE
deprecate seqan3::views::as_const

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#323]
### Tasks

- [ ] deprecate seqan3::views::as_const
- [ ] remove usage from our tests/snippets
- [ ] add changelog entry

```patch
From c04335b633f749eecda02cca024021f39835f247 Mon Sep 17 00:00:00 2001
From: marehr <marehr-github@marehr.dialup.fu-berlin.de>
Date: Sun, 18 Apr 2021 12:47:47 +0200
Subject: [PATCH 01/35] TODO: [MISC] deprecate seqan3::views::as_const

---
 include/seqan3/range/views/as_const.hpp | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

diff --git a/include/seqan3/range/views/as_const.hpp b/include/seqan3/range/views/as_const.hpp
index ed2da595e..b6677cb16 100644
--- a/include/seqan3/range/views/as_const.hpp
+++ b/include/seqan3/range/views/as_const.hpp
@@ -84,8 +84,10 @@ namespace seqan3::views
  *
  * \include test/snippet/range/views/as_const.cpp
  * \hideinitializer
+ *
+ * \todo make seqan3::detail and concatenated_sequences
  */
-inline auto const as_const = std::views::transform(seqan3::detail::as_const_fn{});
+inline constexpr auto as_const = std::views::transform(seqan3::detail::as_const_fn{});
 //!\}
 
 } // namespace seqan3::views
-- 
2.31.1
```
