### ISSUE TITLE
deprecate seqan3::views::convert

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#324]
### Tasks

- [ ] deprecate seqan3::views::convert
- [ ] remove usage from our tests/snippets
- [ ] add changelog entry

```patch
From 6f91e21b52a3f3a67001b2d9dd25f38c83e55370 Mon Sep 17 00:00:00 2001
From: marehr <marehr-github@marehr.dialup.fu-berlin.de>
Date: Sun, 18 Apr 2021 12:47:48 +0200
Subject: [PATCH 02/35] TODO: [MISC] deprecate seqan3::views::convert

---
 include/seqan3/range/views/convert.hpp | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/include/seqan3/range/views/convert.hpp b/include/seqan3/range/views/convert.hpp
index 1880c16f0..2684f506c 100644
--- a/include/seqan3/range/views/convert.hpp
+++ b/include/seqan3/range/views/convert.hpp
@@ -67,6 +67,8 @@ namespace seqan3::views
  * Convert from seqan3::dna15 to seqan3::dna5:
  * \include test/snippet/range/views/convert_15_to_5.cpp
  * \hideinitializer
+ *
+ * \deprecated BHAL BLAH TODO
  */
 template <typename out_t>
 auto const convert = std::views::transform([] (auto && in) -> out_t
-- 
2.31.1
```

**Comment by eseiler** [comment]
`static_cast` doesn't always work, e.g. `bitcompressed_vector` needs an implicit cast
```cpp
diff --git a/include/seqan3/range/container/bitcompressed_vector.hpp b/include/seqan3/range/container/bitcompressed_vector.hpp
index b2015136..1f9ce70c 100644
--- a/include/seqan3/range/container/bitcompressed_vector.hpp
+++ b/include/seqan3/range/container/bitcompressed_vector.hpp
@@ -836,7 +836,7 @@ public:
         auto const pos_as_num = std::distance(cbegin(), pos);
 
         auto v = std::ranges::subrange<begin_iterator_type, end_iterator_type>{begin_it, end_it}
-               | views::convert<value_type>
+               | std::views::transform([] (auto && in) -> value_type { std::forward<decltype(in)>(in); })
                | views::to_rank;
         data.insert(data.begin() + pos_as_num, std::ranges::begin(v), std::ranges::end(v));
 
```

On second thought I would rather argue for making this a utility/detail view.
Also, we promote it:
```
* All ranges of nucleotide alphabets are convertible to each other via seqan3::views::convert.
```
So we would at least need a cookbook entry.

**Comment by marehr** [comment]
No problem than move it to utility :)

**Comment by marehr** [comment]
The only weird thing is that the ranges library did define a convert view via `static_cast`. It smells like that the implicit convert was added to ours because of the bitcompressed_vector.

In the long term, we might want to remove that implicit convert requirement.
