### ISSUE TITLE
deprecate seqan3::views::move

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#328]
### Tasks

- [ ] deprecate seqan3::views::move
- [ ] remove usage from our tests/snippets
- [ ] add changelog entry

```patch
From 1b48bb91b43870d7be376a98700785553aa97322 Mon Sep 17 00:00:00 2001
From: marehr <marehr-github@marehr.dialup.fu-berlin.de>
Date: Sun, 18 Apr 2021 12:47:49 +0200
Subject: [PATCH 06/35] TODO: [MISC] deprecate seqan3::views::move

---
 include/seqan3/range/views/move.hpp | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/include/seqan3/range/views/move.hpp b/include/seqan3/range/views/move.hpp
index 84832b859..79508353d 100644
--- a/include/seqan3/range/views/move.hpp
+++ b/include/seqan3/range/views/move.hpp
@@ -66,6 +66,8 @@ namespace seqan3::views
  *
  * A more useful example can be found in \link sequence_file_section_fun_with_ranges the tutorial \endlink.
  * \hideinitializer
+ * \deprecated Use the std::ranges::move algorithm, std::cpp20::move_iterator or an explicit for loop where you move
+ *             the value.
  */
 inline auto const move = std::views::transform(detail::multi_invocable
 {
-- 
2.31.1
```
