### ISSUE TITLE
deprecate seqan3::views::persist

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#329]
### Tasks

- [ ] deprecate seqan3::views::persist
- [ ] move to core/detail/persist_view.hpp
- [ ] remove usage from our tests/snippets
- [ ] add changelog entry

```patch
From d776332388c6f37b71c4a307efb4eecb9413ee70 Mon Sep 17 00:00:00 2001
From: marehr <marehr-github@marehr.dialup.fu-berlin.de>
Date: Sun, 18 Apr 2021 12:47:49 +0200
Subject: [PATCH 07/35] TODO: [MISC] deprecate seqan3::views::persist

---
 include/seqan3/range/views/persist.hpp | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/include/seqan3/range/views/persist.hpp b/include/seqan3/range/views/persist.hpp
index 192208016..4d0f1f0c3 100644
--- a/include/seqan3/range/views/persist.hpp
+++ b/include/seqan3/range/views/persist.hpp
@@ -229,6 +229,9 @@ namespace seqan3::views
  * \include test/snippet/range/views/persist.cpp
  *
  * \hideinitializer
+ *
+ * \deprecated TODO no alternative
+ *             move to core/detail/persist_view.hpp
  */
 inline auto constexpr persist = detail::persist_fn{};
 
-- 
2.31.1
```
