### ISSUE TITLE
deprecate seqan3::views::take_exactly

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#331]
### Tasks

- [ ] deprecate seqan3::views::take_exactly
- [ ] remove usage from our tests/snippets
- [ ] add changelog entry

```patch
From cd8d7cbfee415b15cddb4831db8636fe154dcf9a Mon Sep 17 00:00:00 2001
From: marehr <marehr-github@marehr.dialup.fu-berlin.de>
Date: Sun, 18 Apr 2021 12:47:50 +0200
Subject: [PATCH 09/35] TODO: [MISC] deprecate seqan3::views::take_exactly

---
 include/seqan3/range/views/take_exactly.hpp | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/include/seqan3/range/views/take_exactly.hpp b/include/seqan3/range/views/take_exactly.hpp
index e46f73cbc..2e3a30fc5 100644
--- a/include/seqan3/range/views/take_exactly.hpp
+++ b/include/seqan3/range/views/take_exactly.hpp
@@ -73,6 +73,8 @@ namespace seqan3::views
  * \include test/snippet/range/views/take_exactly.cpp
  *
  * \hideinitializer
+ *
+ * \deprecated TODO find alternative
  */
 inline auto constexpr take_exactly = detail::take_fn<true, false>{};
 
@@ -87,6 +89,8 @@ inline auto constexpr take_exactly = detail::take_fn<true, false>{};
  *
  * \copydetails seqan3::views::take_exactly
  * \hideinitializer
+ *
+ * \deprecated TODO find alternative
  */
 inline auto constexpr take_exactly_or_throw = detail::take_fn<true, true>{};
 
-- 
2.31.1
```
