### ISSUE TITLE
deprecate seqan3::views::to_lower

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#333]
### Tasks

- [ ] deprecate seqan3::views::to_lower
- [ ] remove usage from our tests/snippets
- [ ] add changelog entry

```patch
From d91c5bf020289433177bcbcebc2b9166d85b2448 Mon Sep 17 00:00:00 2001
From: marehr <marehr-github@marehr.dialup.fu-berlin.de>
Date: Sun, 18 Apr 2021 12:47:50 +0200
Subject: [PATCH 11/35] TODO: [MISC] deprecate seqan3::views::to_lower

---
 include/seqan3/range/views/to_lower.hpp | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/include/seqan3/range/views/to_lower.hpp b/include/seqan3/range/views/to_lower.hpp
index 1c42d808e..39beedd2a 100644
--- a/include/seqan3/range/views/to_lower.hpp
+++ b/include/seqan3/range/views/to_lower.hpp
@@ -63,6 +63,8 @@ namespace seqan3::views
  * ### Example
  * \include test/snippet/range/views/to_lower.cpp
  * \hideinitializer
+ *
+ * \deprecated Use std::views::transform([](auto && chr){return std::tolower(chr)});
  */
 inline auto const to_lower = deep{std::views::transform([] (auto const in) noexcept
 {
-- 
2.31.1
```
