### ISSUE TITLE
deprecate seqan3::views::to_upper

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#334]
### Tasks

- [ ] deprecate seqan3::views::to_upper
- [ ] remove usage from our tests/snippets
- [ ] add changelog entry

```patch
From ca326eb6b8ad1f91bd14b3555e332933feb10702 Mon Sep 17 00:00:00 2001
From: marehr <marehr-github@marehr.dialup.fu-berlin.de>
Date: Sun, 18 Apr 2021 12:47:51 +0200
Subject: [PATCH 12/35] TODO: [MISC] deprecate seqan3::views::to_upper

---
 include/seqan3/range/views/to_upper.hpp | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/include/seqan3/range/views/to_upper.hpp b/include/seqan3/range/views/to_upper.hpp
index f1e7505d1..452a413f8 100644
--- a/include/seqan3/range/views/to_upper.hpp
+++ b/include/seqan3/range/views/to_upper.hpp
@@ -63,6 +63,8 @@ namespace seqan3::views
  * ### Example
  * \include test/snippet/range/views/to_upper.cpp
  * \hideinitializer
+ *
+ * \deprecated Use std::views::transform([](auto && chr){return std::toupper(chr)});
  */
 inline auto const to_upper = deep{std::views::transform([] (auto const in) noexcept
 {
-- 
2.31.1
```
