### ISSUE TITLE
deprecate seqan3::views::join and move seqan3::views::join_with to seqan3/utility/views/

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#351]
### Tasks

- [ ] deprecate seqan3::views::join
- [ ] move seqan3::views::join_with to seqan3/utility/views/
- [ ] old header `join.hpp` should be deprecated as we did with the utility move (see https://github.com/seqan/seqan3/commit/dc7862cd0010ae80d2faf001c47bcbdc944a3807)

```patch
From 11ac3c649859c8514a1784b21b51fb165accd119 Mon Sep 17 00:00:00 2001
From: marehr <marehr-github@marehr.dialup.fu-berlin.de>
Date: Sun, 18 Apr 2021 12:47:48 +0200
Subject: [PATCH 29/35] TODO: [MISC] rename seqan3::views::join{,_with} and
 move it to seqan3/utility/views/

---
 include/seqan3/range/views/join.hpp | 14 ++++++++++++--
 1 file changed, 12 insertions(+), 2 deletions(-)

diff --git a/include/seqan3/range/views/join.hpp b/include/seqan3/range/views/join.hpp
index 41bf43814..3249fc926 100644
--- a/include/seqan3/range/views/join.hpp
+++ b/include/seqan3/range/views/join.hpp
@@ -20,7 +20,17 @@
 namespace seqan3::views
 {
 
-//TODO reimplement me and rename to join_with
-using ::ranges::views::join;
+/*!\brief A join view.
+ * \ingroup views
+ * \deprecated Please use std::views::join or seqan3::views::join_with (if a separator is needed)
+ */
+SEQAN3_DEPRECATED_310 inline constexpr auto join = ::ranges::views::join;
+
+/*!\brief A join view, please use std::views::join if you don't need a separator.
+ * \ingroup views
+ * \details
+ * \noapi{This is currently range-v3's join implementation.}
+ */
+inline constexpr auto join_with = ::ranges::views::join;
 
 } // namespace seqan3::views
-- 
2.31.1
```
