### ISSUE TITLE
move seqan3::views::type_reduce to seqan3/utility/views/

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#356]
### Tasks

- [ ] move seqan3::views::type_reduce to seqan3/utility/views/
- [ ] rename seqan3::views::type_reduce_view to seqan3::views::type_reduce_t
- [ ] old header `char_to.hpp` should be deprecated as we did with the utility move (see https://github.com/seqan/seqan3/commit/dc7862cd0010ae80d2faf001c47bcbdc944a3807)

```patch
From 62b8905158f2f6920b0668869868699b260245b1 Mon Sep 17 00:00:00 2001
From: marehr <marehr-github@marehr.dialup.fu-berlin.de>
Date: Sun, 18 Apr 2021 12:47:51 +0200
Subject: [PATCH 34/35] TODO: [MISC] move seqan3::views::type_reduce to
 seqan3/utility/views/

---
 include/seqan3/range/views/type_reduce.hpp | 10 +++++++++-
 1 file changed, 9 insertions(+), 1 deletion(-)

diff --git a/include/seqan3/range/views/type_reduce.hpp b/include/seqan3/range/views/type_reduce.hpp
index 9c4cc49bd..cab4cb2cb 100644
--- a/include/seqan3/range/views/type_reduce.hpp
+++ b/include/seqan3/range/views/type_reduce.hpp
@@ -154,6 +154,8 @@ namespace seqan3::views
 * \include test/snippet/range/views/type_reduce.cpp
  *
  * \hideinitializer
+ * \experimentalapi{Experimental since version 3.1.}
+ * \todo Move to utility
  */
 inline constexpr auto type_reduce = detail::type_reduce_fn{};
 
@@ -163,7 +165,13 @@ inline constexpr auto type_reduce = detail::type_reduce_fn{};
 
 namespace seqan3
 {
-//!\brief Deduces the return value of seqan3::views::type_reduce.
+/*!\brief Deduces the return value of seqan3::views::type_reduce.
+ * \details
+ * \noapi
+ * \todo // move to utility
+ * \todo // rename to seqan3::views::type_reduce_t in spirit of std::views::all_t
+ * \sa https://en.cppreference.com/w/cpp/ranges/all_view
+ */
 template <typename t>
 using type_reduce_view = decltype(views::type_reduce(std::declval<t>()));
 }
-- 
2.31.1
```
