### ISSUE TITLE
rename seqan3::quality_base to seqan3::phred_base

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#358]
### Tasks

- [x] rename seqan3::quality_base to seqan3::phred_base
- [x] rename header (old header `quality_base.hpp` should be deprecated as we did with the utility move (see https://github.com/seqan/seqan3/commit/dc7862cd0010ae80d2faf001c47bcbdc944a3807)
- [x] add type alias with deprecation for seqan3::phred_base
- [x] add changelog entry
