### ISSUE TITLE
deprecate seqan3::views::take_line

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#359]
### Tasks

- [x] deprecate seqan3::views::take_line
- [ ] remove usage from our tests/snippets
- [x] add changelog entry
