### ISSUE TITLE
[INFRA] Drop gcc-{7,8}

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#374]
### Description 

After release of seqan3 3.1.x, drop the following compiler

* gcc-7
* gcc-8

Add diagnostics to platform.hpp that says:

* if gcc 7 or gcc 8: "seqan3 3.1.x is the last version that supports gcc 7/8, please upgrade your compiler or stay on that version."

Afterthoughts:

* gcc-9: supports `template <> concept always_true = true`; we can drop SEQAN3_CONCEPT macro
* "support" (don't drop workarounds, don't add new workarounds, because we can't test that) three-months the latest two minor versions of gcc to give the user time to upgrade.
  * and warn if latest version is too old.
* filesystem can be simplified (get rid of std::experimental::file_system and deprecate seqan3/std/filesystem.)
* minor gcc version in other issue: https://github.com/seqan/product_backlog/issues/410

### Tasks

- [x] Update CI and drop workarounds and bump version to 3.2 [@eseiler]
- [x] Add diagnostic: if gcc 7 or gcc 8 is used 
      `"seqan3 3.1.x is the last version that supports gcc 7/8, please upgrade your compiler 
      or stay on that version."`
- [ ] Update documentation that states gcc-7 / 8.
  - [ ] README.md
  - [ ] doc/about/api/index.md 
  - [ ] snippets about concept usage
  - [ ] Check if the compiler support is documented somewhere else too (search for `gcc7`, `gcc-7`, `gcc 7`; and `gcc8`, `gcc-8`, `gcc 8`) 
- [x] filesystem can be simplified
  - [x] `seqan3/std/filsystem` should just include `<filesystem>`
  - [x] deprecate seqan3/std/filesystem (i.e. add deprecation warning)

**Comment by MitraDarja** [comment]
Workarounds to delete:
- [x] SEQAN3_WORKAROUND_GCC_83328
- [x] SEQAN3_WORKAROUND_GCC_87113
- [x] SEQAN3_WORKAROUND_GCC_90897
- [x] SEQAN3_WORKAROUND_GCC7_AND_8_CONCEPT_ISSUES
- [x] SEQAN3_WORKAROUND_GCC_94967

**Comment by eseiler** [comment]
Done
