### ISSUE TITLE
[Alignment] API Stability of Alignment Module

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#391]
### Description 

Left-overs from Release 3.1:

- [ ] **scoring schemes**: scoring schemes must be supplied for `seqan3::align_pairwise`. If we mark `seqan3::align_pairwise` as api-stable but scoring schemes as experimental, `seqan3::align_pairwise` cannot really be used in a stable way. Discussing scoring schemes has a high priority!  (see https://github.com/seqan/product_backlog/issues/268#issuecomment-762179494)
- [ ] Concern: Is the the naming of `seqan3::alignment_result` maybe not compatible with later changes, when we introduce the multiple alignment. Possible alternatives: `seqan3::align_pairwise_result` `seqan3::sequence_alignment_result` (and later `seqan3::align_multiple_result`, `seqan3::multiple_sequence_alignment_result`)  (see https://github.com/seqan/product_backlog/issues/268#issuecomment-762179494)
- [ ] Is `writeable_aligned_sequence` concept really stable, or should it be experimental since the functions `insert_gap`, ... are not stable yet  (see https://github.com/seqan/product_backlog/issues/268#issuecomment-762179494)

### Acceptance Criteria

- [ ] test 1
- [ ] test 2
- [ ] test 3

### Tasks

 

- [ ] task 1
- [ ] task 2
- [ ] task 3

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
