### ISSUE TITLE
Fixup API documentation before 3.1.0

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#393]
### Description 

Some modules are not at the correct place anymore. 

For example, we split `core` + `utility`, and `ranges`. Both splits did not fix the documentation.

**Please check the module for the following:**
1. Public API is at the right `\ingroup`. When you go through the module, everything that shows up actually belongs to this (sub-)module. 
2. Check the Landing Page. It should at least have a meaningful description, scan through the description, if there is one, and verify that it is up-to-date.
3. If you encounter an entry to appear twice. Check if the documentation may have a `\relates` AND an `\ingroup` command. They should only have one of them! If it has both, remove the `\ingroup`.
4. **NEW RULE** Every entity should link to it's (submodule page)! (This probably has to be adapted a lot) So if e.g. seqan3::align_cfg::method_global is in `\ingroup alignment_configuration` then at the same spot, one should add a `\remark` with a custom text or `\see alignment_configuration` in the end.
   <details><summary>Example</summary>
   
   ```
   /*!\brief Some brief
    * \ingroup submodule_name
    *
    *  some detailed description blah blah.
    *
    * \remark For a complete overview, take a look at \ref submodule_name 
    */
    class some_class
   ```
  
   </details>

Part of https://github.com/seqan/seqan3/issues/2685

### Tasks

- [x] #404
- [x] Alignment Module (related: https://github.com/seqan/seqan3/issues/2764) [@Irallia]
- [x] Argument Parser [@MitraDarja ]
- [x] I/O [@smehringer]
  - [x] seqan3::sam_record in the right module 
- [x] Core (fixes in https://github.com/seqan/seqan3/pull/2861) [@eaasna]
- [x] Utility (https://github.com/seqan/seqan3/pull/2871) [@marehr]
- [x] Search (adjusted in https://github.com/seqan/seqan3/pull/2840) [@SGSSGene]
  - [x] [DREAM-INDEX](https://docs.seqan.de/seqan/3-master-user/group__search__dream__index.html) `Provides seqan3:interleaved_bloom_filter. ` is missing a second `::`. (Other module pages have the same issue) - Remark: this is fixed with https://github.com/seqan/seqan3/pull/2840 (Search)
- [x] std (https://github.com/seqan/seqan3/pull/2865) [@MitraDarja]
- [x] Change all an std::... into a std::... https://github.com/seqan/seqan3/pull/2875 [@Irallia]

**Comment by smehringer** [comment]
Finally Done :tada:
