### ISSUE TITLE
To extract the argument parser we need to cut loose of SeqAn3 dependencies

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#40]
### Description 

Identify and remove argument parser dependencies.

### Acceptance Criteria

- [ ] The argument parser has no dependency to SeqAn3 anymore, except things that live in the std module of SeqAn

### Tasks

 

- [ ] remove seqan3 dependencies except for std module

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by smehringer** [comment]
Done in https://github.com/seqan/sharg-parser
