### ISSUE TITLE
Script that automatically creates all.hpp files

### ISSUE THREAD

**Issue by smehringer** [seqan/product_backlog#400]
### Description 

In each (subfolder) we want to have an `all.hpp` file for the user, s.t. the user can include the whole (sub)module.

An `all.hpp` file contains all public API files (no detail files) in it's directory plus all `all.hpp` files of it's subdirectories.

The `all.hpp` files need to be up to date but are often forgot to adapt when moving files around or adding new ones. Thus they should be created automatically.

### Tasks

- [x] Create a script (bash or pearl) that automatically creates all.hpp files (If too tricky to avoid, detail files can be included for now. including all.hpp files is inefficient concering compile times anyway)

### Definition of Done

- [x] Implementation and design approved
- [x] Unit tests pass

**Comment by smehringer** [comment]
Fixed by seqan/seqan3#2841
