### ISSUE TITLE
[INFRA] Add gcc-12 support

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#402]
#### Bugs:
* [x] https://github.com/seqan/seqan3/pull/2844
* [x] https://github.com/seqan/seqan3/pull/2848

#### External dependencies:
* [x] https://github.com/ericniebler/range-v3/pull/1665 - replaced with:
* * [x] https://github.com/seqan/seqan3/pull/2965
* [x] https://github.com/seqan/seqan3/pull/2938

#### ICE:
* [x] https://github.com/seqan/seqan3/pull/2937

**Comment by eseiler** [comment]
ICE: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100252

In:
https://github.com/seqan/seqan3/blob/75de3b1df8cf38df521f939e499d84ecf3100d8c/test/include/seqan3/test/fixture/io/sam_file/simple_three_verbose_reads_fixture.hpp#L163

https://github.com/seqan/seqan3/blob/75de3b1df8cf38df521f939e499d84ecf3100d8c/test/include/seqan3/test/fixture/io/sequence_file/standard_fixture.hpp#L55

Workaround:
```cpp
std::vector<record_type> records;
simple_three_verbose_reads_fixture() : records{record1, record2, record3} {} // or standard_fixture
```
or
```cpp
std::vector<record_type> records = [this] () { return std::vector<record_type>{record1, record2, record3}; }();
```

**Comment by eseiler** [comment]
`view_interface` is not derived from `view_base` any more:

* https://github.com/gcc-mirror/gcc/commit/53b1c382d5a6fe8dec394a7ff820d77cda02af81
* https://cplusplus.github.io/LWG/issue3549

In:
https://github.com/seqan/seqan3/blob/75de3b1df8cf38df521f939e499d84ecf3100d8c/include/seqan3/std/ranges#L49-L51

Workaround:
```cpp
//!\brief std::ranges::views are valid range-v3 views
template<typename T>
    requires ::std::derived_from<T, ::std::ranges::view_base> ||
             ::std::derived_from<T, ::std::ranges::view_interface<T>>
inline constexpr bool enable_view<T> = true;
```

we only enable this because of the ranges-v3 dependency. Once we drop the dependency this can be removed. This should be added in the comment in the code.

**Comment by eseiler** [comment]
[Nightlies ](https://cdash.seqan.de/index.php?project=SeqAn3#!#Experimental) are incorporating range-v3 fix:

```diff
Submodule submodules/range-v3 contains modified content
diff --git a/submodules/range-v3/include/range/v3/range/concepts.hpp b/submodules/range-v3/include/range/v3/range/concepts.hpp
index 36511ae2c..50879bcce 100644
--- a/submodules/range-v3/include/range/v3/range/concepts.hpp
+++ b/submodules/range-v3/include/range/v3/range/concepts.hpp
@@ -207,7 +207,7 @@ namespace ranges
     template<typename T>
     CPP_concept view_ =
         range<T> &&
-        semiregular<T> &&
+        copyable<T> &&
         enable_view<T>;

     template<typename T>
```

**Comment by eseiler** [comment]
GCC 12 is released and integrated into CI
