### ISSUE TITLE
[DOC]  Check if every doc item has an \ingroup.

### ISSUE THREAD

**Issue by smehringer** [seqan/product_backlog#406]
### Description 

Every documentation entry belongs to a certain (sub)module. If it is missing the `\ingroup` or `\relates` command. It won't appear in the respective (sub)module in the API documentation but instead, e.g. when clicking the entity while browsing the docu, you end up in this huge class list on the left TOC. 

### Tasks

- [ ] Write a script or cmd-call that checks if every documentation entry has an `\ingroup` or `\relates` (don't know if thats easily possible) 
- [ ] Check the library and add `\ingroups`, `\relates` where needed
- [ ] Could this maybe be part of the CI? Investigate shortly
