### ISSUE TITLE
As application tester I want to call `make` without arguments which will only build the application binaries and not the tests.

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#41]
### Description 

Calling `make` or `make all` does not build the tests but only the application binaries.

### Acceptance Criteria

- [ ] calling make builds only the application binaries
- [ ] ~calling make all builds only the application binaries~ (Please discuss again! Comment below.)

### Tasks

 

- [ ] use https://cmake.org/cmake/help/v3.17/prop_tgt/EXCLUDE_FROM_ALL.html to exclude the test targets from the all target

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by rrahn** [comment]
See also: https://cmake.org/cmake/help/latest/command/set_target_properties.html
This should look something like this:
```cmake
set_target_properties(target EXCLUDE_FROM_ALL true)
```

**Comment by joergi-w** [comment]
I agree to exclude tests from the default `make` target as discussed in our meeting on Monday. 
But I disagree to remove tests from the `make all`. This target is meant to build **everything** and as an application user or tester I expect it to do so.

**Comment by rrahn** [comment]
As far as I undersand `make` just calls `make all`. But not sure if you can change that behaviour.

**Comment by joergi-w** [comment]
Sorry for coming up with this question again and again, but I have not got a good answer yet: What is the underlying reason for the decision of excluding tests from the make standard target?

When I researched about this topic I found only tutorials and guidelines that include also the tests. There was no evidence that excluding tests is somehow expected for applications. The default workflow for installing an application is
`cmake` (configure)
`make` (build everything)
`make test` (run tests)
`make install` (copy executables, includes, libs etc.)

The [GNU make manual](http://www.gnu.org/software/make/manual/html_node/Standard-Targets.html) says that `make all` should be the default target and compile the entire program, excluding only rebuild of documentation, info and dvi files.
The official [CMake Tutorial](https://cmake.org/cmake/help/latest/guide/tutorial/index.html) includes the tests into the default target as well. 
Instructions for C++ project setup with CMake & unit tests ([link](https://raymii.org/s/tutorials/Cpp_project_setup_with_cmake_and_unit_tests.html)) as well as Makefile with unit tests ([link](https://stackoverflow.com/questions/3724772/makefile-for-unit-tests-in-c)) show that the tests are a target considered by both `make` and `make all`. 

@seqan/core given all the evidence above I would like to discuss this step again before I start implementing it.

**Comment by rrahn** [comment]
Good point and question. For me it has something todo with the expected build times.
So in general all our apps kind of compile a little bit. That is the burdon of a header only library that is as cool as ours. Of course any application developer is free to put stuff into precompiled static libraries allowing to build more in parallel. Nonethless, build time is always a concern. 
So in the install sequence if I do `make` and then `make install` I would not need the tests and it would be good not to build all tests. If the user adds `make test` inbetween then the tests will be build and executed. So my take is that only the developer wants to build the tests with `make all` but not the user per sé. That's why I am in favour of separting the tests fromt the all target. I mean this includes, api tests, cli tests, documentation, coverage tests etc. So you might end up in a 10 minutes or longer build and several MB of binary data that might not be needed.

**Comment by joergi-w** [comment]
I understand your concern about the build time. However, an application user installs an application **once** and then he/she just runs it. We already encourage using static libraries: I implemented the template in a way that the compiled app code can be linked to both the main and the api tests (`libfastq_to_fasta_lib.a`). Furthermore, we are going to provide binaries for different systems (if I understand CI&CD in the right way?) so an application can just be downloaded and used. 

> So in the install sequence if I do `make` and then `make install` I would not need the tests and it would be good not to build all tests. 

This is technically true, but whenever I build an application manually, I always run the tests to check if it works correctly on my system prior to running the application on my own data. Maybe this is my personal way, but probably I'm not alone. For system administrators this is a crucial step as well, as they want to provide non-failing server installations for multiple users. There are two exceptions that I agree to exclude from `make all`: Coverage test and Doxygen. This is mainly for developers and a user would not run them locally; and documentation should be online. 

> If the user adds `make test` inbetween then the tests will be build and executed. 

No, this is not true. `make test` (and `RUN_TESTS` for VS) is a builtin target by CMake which executes the tests through ctest. It fails if the tests have not been built before (try with seqan3/unit for instance). Of course, we could implement our own test target around that, but this is not the behaviour that users would expect and it would differ from seqan3.

If a user does not want to test their application and only compile what's needed, they can run `make fastq_to_fasta` for instance and we can document that in the readme file.

**Comment by joergi-w** [comment]
Can we discuss this in a short meeting today?
