### ISSUE TITLE
[FEATURE] header-replacement-script for release updates

### ISSUE THREAD

**Issue by smehringer** [seqan/product_backlog#414]
### Description 

Moving our headers is a problem for users that include all.hpp files because some stuff might not be available after updating to a newer seqan3 release. 

We should provide a search-and-replace script that fixes all header includes.

### Acceptance Criteria

- [ ] Script should replace all headers in a command line provided directory
- [ ] Script should be easily extendible for with new headers when we move them
- [ ] Script always works for the release immediately following the last one. If you want to update several releases you need to run every release script after one another.

### Tasks

- [ ] write script
- [ ] Discuss with core team were scripts should live within seqan3 repo
- [ ] Add CI
- [ ] Add how-to documentation
- [ ] Add permanent info to changelog
