### ISSUE TITLE
Doxygen 1.9.5 support

### ISSUE THREAD

**Issue by eseiler** [seqan/product_backlog#417]
### Reported bugs

- [x] https://github.com/doxygen/doxygen/issues/9379

### Tasks

 

- Monitor the [nightly documentation builds](https://cdash.seqan.de/index.php?project=SeqAn3#!#documentation). These are build with the master or release branch of doxygen.
- If there is an error, investigate it and either report it upstream or adjust our documentation.

### Definition of Done

- [ ] doxygen 1.9.5 is released 
- [ ] doxygen 1.9.5 works with our documentation.

**Comment by eseiler** [comment]
Skipping 1.9.5 because of https://github.com/doxygen/doxygen/issues/9552
