### ISSUE TITLE
As a user installing an application  I want to call `make check` so I can see if the application was properly built before calling `make install`.

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#42]
### Description 

The extra target `check` should run CLI tests or a subset of them defined by the application developer.

### Acceptance Criteria

- [ ] calling `make check` after `make` runs the cli tests of the application
- [ ] if the cli tests haven't been built before they will be built when calling `make check`
- [ ] the target fails if some cli tests don't pass and outputs a corresonding diagnostic message

### Tasks

 

- [ ] add a `check` target which runs the cli tests

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by marehr** [comment]
Core-Meeting:

This would only execute a subset of tests to test basic functionality. For a complete unit test; build all tests.
