### ISSUE TITLE
Doxygen 1.9.6 support

### ISSUE THREAD

**Issue by eseiler** [seqan/product_backlog#424]
### Fixed issues

- [x] https://github.com/seqan/seqan3/pull/3060
- [ ] https://github.com/seqan/seqan3/pull/3080

### Tasks

 

- Monitor the [nightly documentation builds](https://cdash.seqan.de/index.php?project=SeqAn3#!#documentation). These are build with the master or release branch of doxygen.
- If there is an error, investigate it and either report it upstream or adjust our documentation.

### Definition of Done

- [ ] doxygen 1.9.6 is released 
- [ ] doxygen 1.9.6 works with our documentation.

**Comment by eseiler** [comment]
Doxygen explicitly does not want `value_type` to be documented via inline syntax in two places: `seqan3::detail::two_dimensional_matrix::value_type` and `seqan3::detail::trace_iterator_base::value_type`.

Works:
```cpp
    /*!\name Associated types
     * \{
     */
    //!\brief The value type.
    using value_type = trace_directions;
    using reference = trace_directions const &;          //!< The reference type.
    using pointer = value_type const *;                  //!< The pointer type.
    using difference_type = std::ptrdiff_t;              //!< The difference type.
    using iterator_category = std::forward_iterator_tag; //!< Forward iterator tag.
    //!\}
```

Does not work:

```cpp
    /*!\name Associated types
     * \{
     */
    using value_type = trace_directions;                 //!< The value type.
    using reference = trace_directions const &;          //!< The reference type.
    using pointer = value_type const *;                  //!< The pointer type.
    using difference_type = std::ptrdiff_t;              //!< The difference type.
    using iterator_category = std::forward_iterator_tag; //!< Forward iterator tag.
    //!\}
```

Fails with
```
seqan3/alignment/matrix/detail/edit_distance_trace_matrix_full.hpp:254: warning: unexpected token TK_COMMAND_BS as the argument of \ifile
```

Works:

```cpp
    /*!\name Associated types
     * \{
     */
    using reference = trace_directions const &;          //!< The reference type.
    using value_type = trace_directions;                 //!< The value type.
    using pointer = value_type const *;                  //!< The pointer type.
    using difference_type = std::ptrdiff_t;              //!< The difference type.
    using iterator_category = std::forward_iterator_tag; //!< Forward iterator tag.
    //!\}
```

:)
