### ISSUE TITLE
As application developer I want automatic fetching of test data so I can run my tests without worrying about where the test data is downloaded.

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#43]
### Description 

Fetch the data from the given data source.

### Acceptance Criteria

- [ ] specifying a remote resource with a file to download the file will be downloaded during the build of the test.
- [ ] if the test data is already present nothing will be downloaded.
- [ ] if the data is not reachable from the remote location a build error occurs with a diagnostic message

### Tasks

 

- [ ] add cmake function to download a remote file.

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by rrahn** [comment]
Also see: https://gist.github.com/marehr/d34f6d7e92a7ca58c37ab251a0e8e3b8
For a look and feel
