### ISSUE TITLE
As application developer I want built application binaries put into a bin directory so I can easily find the binaries after building.

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#44]
### Acceptance Criteria

- [x] built binaries are placed into the bin directory below the build root
- [x] tests are excluded from this

### Tasks

 

- [x] output built  archives into a bin directory below the build root
- [x] output built  libraries into a lib directory below the build root

### Definition of Done

- [x] Implementation and design approved
- [x] Unit tests pass
- [ ] Tutorial/teaching material added

**Comment by smehringer** [comment]
@rrahn @marehr @joergi-w In the issue it says "excluding the test binaries". Where should the built test binaries go then?

**Comment by joergi-w** [comment]
I think we should discuss this briefly in a meeting. On Monday it was rather short and we could just speak about the most urgent decisions. In my opinion the most intuitive options are:
(1) `test/cli/` and `test/api` respectively: that's where gtest places them
(2) `test/`: so one can execute `./test/XY_test` without searching long for the executable

**Comment by marehr** [comment]
They should go like they go in there definition:

> `<SRC>/test/cli/module/my_test.cpp`

should produce the binaries in

> `<BUILD>/test/cli/module/my_test`

(the same behaviour as seqan3 has)

**Comment by smehringer** [comment]
We will use @marehr's approach as it also includes @joergi-w (1)

**Comment by rrahn** [comment]
@smehringer is this already in review?

**Comment by smehringer** [comment]
no
