### ISSUE TITLE
cmake: fetch googletest on demand

### ISSUE THREAD

**Issue by joergi-w** [seqan/product_backlog#47]
### Description 

As application user I want to download the googletest on first use so I can run the app with a smaller download.

Like in SeqAn3 library we want to download and build the gtest library when the tests are built for the first time.

### Acceptance Criteria

- [ ] Gtest is not anymore a git submodule of app_template.
- [ ] Gtest is made available during the first test build.
- [ ] Gtest is not required for running the app.

### Tasks

 

Moved from issue #3

- [ ] Change cmake to fetch and build gtest within configuration step using [FETCH_CONTENT](https://cmake.org/cmake/help/v3.17/module/FetchContent.html)

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] CLI tests pass (if already imlpemented)
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by marehr** [comment]
Mine, because I want this in seqan3 to.
