### ISSUE TITLE
C++20 "standard" conform

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#49]
### Description

As a Library we want to be C++20 "standard" conform

From the beginning of seqan3 development, we decided to use the ranges library and the language feature of concepts that we knew that will be part of the C++ standard at one point. 

Initially, we expected it to be in the then upcoming C++17 standard but it was postponed to C++20.

During the standardisation process, some names, syntax and paradigms changed within the ranges and concept proposal. Thus, this epic issue will keep track of those changes to make the seqan3 library "standard" conform.

### Acceptance Criteria

- [x] The seqan3 library is C++20 standard conform and
- [ ] compiles on linux with C++20 compatible compilers, e.g. gcc and clang.

### Tasks

 

- [x] Requires clauses need parenthesis for non-primary expressions #53
- [x] return-type-requirement is not a type-constraint #88
- [x] `std::span` should have signature `std::span<typename span_tp, size_t span_extent>` instead of `std::span<typename span_tp, ptrdiff_t span_extent>` seqan/seqan3#1712
- [x] Use internally `std::(ranges::range|iter)_(size|difference|value|reference|rvalue_reference)_t` instead of `seqan3::(size_type|difference_type|value_type|reference|rvalue_reference|const_reference)_t`. seqan/seqan3#1549
- [x] Update Ranges-Library to keep track of changes in the standard seqan/seqan3#1702
- [x] Remove dependencies of seqan3 in `seqan3/std/*` headers #135
- [x] Remove "Associated types" from views #51
- [x] Use `std::` versions of views and ranges instead of ranges-v3
  * [x] `std::ranges::view_base` instead of `::ranges::view_base` https://github.com/seqan/seqan3/pull/1906
  * [x] `std::ranges::ref_view` instead of `::ranges::ref_view` https://github.com/seqan/seqan3/pull/1905
- [x] Move C++20 things into `std` namespace https://github.com/seqan/product_backlog/issues/134
- [x] Introduce seqan3/std/bit and deprecate most of seqan3/core/bit_manipulation.hpp https://github.com/seqan/product_backlog/issues/199
- [x] Stuff that was renamed by the standard or was in the wrong namespace or was exposition-only:
  * [x] Rename `ranges::enable_safe_range` as `ranges::enable_borrowed_range`. #48
  * [x] Replace `seqan3::forwarding_range` by `std::ranges::borrowed_range`. https://github.com/seqan/seqan3/pull/2038
  * [x] `std::default_constructible` -> `std::default_initializable` 
  * [x] `std::boolean` -> this is exposition-only and called [`boolean-testable`](https://eel.is/c++draft/concepts#concept.booleantestable-1); either throw all usages away or implement it in `seqan3` namespace https://github.com/seqan/seqan3/pull/2023
  * [x] `std::detail::weakly_equality_comparable_with` -> this is exposition-only and called [`weakly-equality-comparable-with`](https://eel.is/c++draft/concept.equalitycomparable#1);  either throw all usages away or implement it in `seqan3` namespace (fun-fact it is already implemented in include/seqan3/core/concept/core_language.hpp) https://github.com/seqan/seqan3/pull/2023
  * [x] `std::readable` -> `std::indirectly_readable` 
  * [x] `std::writable` -> `std::indirectly_writable`  
  * [x] `std::back_inserter` -> `std::cpp20::back_inserter` (back_inserter has a new behaviour since cxx20; it is default initializable)
  * [x] `std::ranges::default_sentinel` -> `std::default_sentinel` (we wrongly assume that these are in std::ranges namespace, even though they are in std namespace) 
  * [x] `std::ranges::default_sentinel_t` -> `std::default_sentinel_t` (we wrongly assume that these are in std::ranges namespace, even though they are in std namespace) 
  * [x] `std::ranges::all_view` -> `std::views::all_t`  
  * [x] Remove iterator related stuff from `std::ranges` when in C++17 mode. (std::forward_iterator, ...) 
    * [x] Explicitly import every single entity into std namespace  https://github.com/seqan/seqan3/pull/1828

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by marehr** [comment]
This is done; since gcc-10 and gcc-11 is C++20 conforming enough for us.

Other compiler do not work yet, because of some major pending bugs. See #127 for example.
