### ISSUE TITLE
Requires clauses need parenthesis for non-primary expressions

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#53]
### Description 

See https://en.cppreference.com/w/cpp/language/expressions#Primary_expressions for what a primary expression is.
or https://en.cppreference.com/w/cpp/language/constraints#Requires_clauses

### Acceptance Criteria

- [x] All Requires clauses are valid C++ 20.

### Tasks

 

- [x] Add parenthesis to all non-primary expressions in requires clauses, e.g. 
  ```cpp
  // requires !std::is_integral_v<T> // not a primary expression
  requires (!std::is_integral_v<T>) // a primary expression
  ```

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by smehringer** [comment]
Can you explain what a primary expression is?

**Comment by marehr** [comment]
https://en.cppreference.com/w/cpp/language/expressions#Primary_expressions
