### ISSUE TITLE
[Alignment] Add basic vectorisation support for the dna global affine alignment

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#54]
These tasks are based on the dna computation using a simple scoring scheme approach.

### Todo

- [x] compute score for sequences with same length
- [x] compute score for sequences with different length
- [x] compute end position for sequences with different length
- [ ] compute begin position for sequences with different length
- [ ] compute alignment for sequences with different length
- [ ] semi-global: compute score for sequences with same length
- [ ] semi-global: compute score for sequences with different length
- [ ] semi-global: compute end position for sequences with different length
- [ ] semi-global: compute alignment for sequences with different length
- [x] compute banded score for sequences with same length
- [ ] compute banded score for sequences with different length
- [ ] compute banded end position for sequences with different length
- [ ] compute banded begin position for sequences with different length
- [ ] compute banded alignment for sequences with different length
