### ISSUE TITLE
Alignment Configuration and Interface

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#55]
### Description

Finalise the alignment configuration. We need to update some of the configurations according to the latest design discussions for the configuration for alignment.

The alignment config elements should be designed as discussed in https://github.com/orgs/seqan/projects/4#card-31347419

Here is the gist to the final design for dynamic and static config elements: https://gist.github.com/rrahn/16f2113015d39b55f5d89e0265f61f1c

----

marehr: Not sure why this is so unstructured, but https://github.com/seqan/product_backlog/issues/131 has the design decisions with the complete [google sheet](https://docs.google.com/document/d/1Lv7zxtDUgAeHGcnJ6IWFzgIbJ6rFJlUt2linAOjlIBg/edit#).

### Tasks:

- [x] align_cfg::method_global
- [x] align_cfg::method_local
- [x] align_cfg::method

- [x] align_cfg::gap_cost_affine

- [x] align_cfg::scoring_scheme

- [x] align_cfg::band_fixed_size

- [x] align_cfg::parallel
- [x] align_cfg::vectorised
- [x] align_cfg::score_type

- [x] align_cfg::output_score
- [x] align_cfg::output_end_position
- [x] align_cfg::output_begin_position
- [x] align_cfg::output_alignment
- [x] align_cfg::output_sequence1_id
- [x] align_cfg::output_sequence2_id

- [x] align_cfg::detail::debug

- [x] align_cfg::min_score
- [ ] align_cfg::detail::result_type 
  - This seems left open. But because it is detail, I think it has not much prio.

- [x] write up a nice landing page about the usage of the configs and an overview over possible configurations.
  - [x] moved to https://github.com/seqan/product_backlog/issues/392

**Comment by marehr** [comment]
@rrahn  Can this be closed?

**Comment by marehr** [comment]
I added https://github.com/seqan/product_backlog/issues/392 for the landing page, closing this as it is mostly done.
