### ISSUE TITLE
Add separate global alignment algorithm with improved performance

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#58]
### Description 

The performance of the alignment algorithm must be improved to be compatible with SeqAn2 such that algorithms that port to SeqAn3 have no performance regression. 
In this part we ony want to get a optimal version of the alignment which we can use as a reference to keep an eye on the performance regression. This will be then step-by-step refactored to beautiful code while keeping the performance.

### Acceptance Criteria

- [x] global alignment with score can be computed over the new implementation
- [x] the macrobenchmark is as fast as SeqAn2
- [x] the microbenchmarks are improved for SeqAn3 global alignment with score.

### Tasks

 

- [x] add a separate algorithm implementation in `align_pairwise/detail`
- [x] adapt the configuration to use this algorithm if the config is global alignment with score only.
- [x] adapt the tests if necessary.

### Definition of Done

- [x] Implementation and design approved
- [x] Unit tests pass
- [x] Test coverage = 100%
- [x] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [x] API documentation added
- [x] Tutorial/teaching material added
- [x] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
