### ISSUE TITLE
gcc-10 -std=c++2a support

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#61]
Keeps track of all changes for `gcc10 -std=c++2a`

Definition of Done:
* [x] All tests build with `gcc10 -std=c++2a`
* [x] `test/unit` is building and passes all tests
* [x] `test/coverage` is building and passes all tests
* [x] `test/header` is building and passes all tests
* [x] `test/performance` is building and passes all tests
* [x] `test/snippet` is building and passes all tests

Bugfixes:
* [x] requires clauses must be primary expressions (seqan/seqan3#1735)
* [x] cxx20: return-type-requirement is not a type-constraint (#88)

Error Classes:
* [x] Requires clauses need parenthesis for non-primary expressions (#53)

External Libraries (Upstream) reported:
* [ ] gcc10: range-v3 views are not combinable with std::views (https://github.com/ericniebler/range-v3/issues/1470)
* [x] all_t alias not in cpp20 namespace (https://github.com/ericniebler/range-v3/issues/1477)
* [x] gcc --std=c++2a: zip view has problems with constness (https://github.com/ericniebler/range-v3/issues/1480)
* [x] semiregular_box_t reference_wrapper not known (https://github.com/ericniebler/range-v3/issues/1499)
* [x] gcc10 invalid use of incomplete type ‘struct std::tuple_size<std::thread>’ (https://github.com/ericniebler/range-v3/issues/1430)

Reported ICEs/Compiler Bugs:
* [x] [10 Regression] Inherited and constrained constructors are "ambiguous" even if they aren't (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94549)
* [x] [10 Regression] constructing constexpr variables fail with delegated constexpr constructors (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94772)
* [x] std::filesystem::path is not concept-friendly (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93983) **Fixed for gcc 10.2**.
* [x] [10 Regression] ICE concepts with template template parameter (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95371) **Fixed for gcc 10.2**.
* [x] std::list | take | transform, expression does not work cbegin() == end() (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95322) **Fixed for gcc 10.2**.
* [x] std::ranges::copy and std::views::take_while don't want to play together (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95578) **Fixed for gcc 10.2**.
* [x] [10 Regression] ICE in tsubst_decl, at cp/pt.c:14666 (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=97745)

**Comment by marehr** [comment]
Not completely done, yet. Snippets, benchmarks and header tests are still missing.

**Comment by marehr** [comment]
@eseiler LOL?

**Comment by eseiler** [comment]
Haha, it closes the issue because I pushed the upstream master to my master and the commit message contains `fixes ...`?

**Comment by eseiler** [comment]
All tests are building and passing.
