### ISSUE TITLE
[Alignment]  unify matrix design for edit and generic alignment algorithm

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#62]
### Description 

The problem is that `two_dimensional_matrix_iterator_base` assumes a `host_iter`.
```c++
    template <typename dummy_t = derived_t>
    constexpr reference<dummy_t> operator*() const noexcept
    {
        return *as_derived().host_iter;
    }
```
https://github.com/seqan/seqan3/blob/f29ac9df7e09596722d10890a88ed1586ff0de1f/include/seqan3/alignment/matrix/detail/two_dimensional_matrix_iterator_base.hpp#L122-L126

This `host_iter` is the iterator of the storage of the `two_dimensional_matrix` (only used in the generic alignment algorithm and it is `std::vector<trace_directions>::iterator`). 

The problem: edit alignment algorithm can't use that, because it has a different memory model.

---

A `two_dimensional_matrix_iterator : two_dimensional_matrix_iterator_base` currently has the following operations (grouped by where they should belong)
* operations needed by `std::random_access_iterator`:
  * ```c++
    constexpr reference<dummy_t> operator*() const noexcept
    ```
  * ```c++
    constexpr reference<dummy_t> operator[](std::iter_difference_t<dummy_t> const offset) const noexcept
    ```
  * ```c++
    constexpr pointer<dummy_t> operator->() const noexcept
    ```
  * ```c++
    constexpr derived_t & operator++() noexcept
    ```
  * ```c++
    constexpr derived_t operator++(int) noexcept
    ```
  * ```c++
    constexpr derived_t & operator--() noexcept
    ```
  * ```c++
    constexpr derived_t operator--(int) noexcept
    ```
  * ```c++
    constexpr derived_t & operator+=(std::iter_difference_t<derived_t> const offset) noexcept
    ```
  * ```c++
    constexpr derived_t operator+(std::iter_difference_t<derived_t> const offset) const noexcept
    ```
  * ```c++
    constexpr friend derived_t operator+(std::iter_difference_t<derived_t> const offset, derived_t const iter)
    ```
  * ```c++
    constexpr derived_t & operator-=(std::iter_difference_t<derived_t> const offset) noexcept
    ```
  * ```c++
    constexpr derived_t operator-(std::iter_difference_t<derived_t> const offset) const noexcept
    ```
  * ```c++
    constexpr std::iter_difference_t<dummy_t> operator-(derived_t const rhs) const noexcept
    ```
  * ```c++
    constexpr bool operator==(two_dimensional_matrix_iterator_base<other_derived_t, order> const & rhs) const noexcept
    ```
  * ```c++
    constexpr bool operator!=(two_dimensional_matrix_iterator_base<other_derived_t, order> const & rhs) const noexcept
    ```
  * ```c++
    constexpr bool operator<(two_dimensional_matrix_iterator_base<other_derived_t, order> const & rhs) const noexcept
    ```
  * ```c++
    constexpr bool operator<=(two_dimensional_matrix_iterator_base<other_derived_t, order> const & rhs) const noexcept
    ```
  * ```c++
    constexpr bool operator>(two_dimensional_matrix_iterator_base<other_derived_t, order> const & rhs) const noexcept
    ```
  * ```c++
    constexpr bool operator>=(two_dimensional_matrix_iterator_base<other_derived_t, order> const & rhs) const noexcept
    ```
* operations needed to build aligned sequences 
  * ```c++
    constexpr seqan3::detail::matrix_coordinate coordinate() const noexcept {}
    ```
  * ```c++
    constexpr derived_t & operator+=(matrix_offset const & offset) noexcept {}
    ```
* operations that can be derived by `operator+=(matrix_offset)
  * ```c++
    constexpr derived_t operator+(matrix_offset const & offset) const noexcept
    ```
  * ```c++
    constexpr friend derived_t operator+(matrix_offset const & offset, derived_t const iter)
    ```
  * ```c++
    constexpr derived_t & operator-=(matrix_offset const & offset) noexcept
    ```
  * ```c++
    constexpr derived_t operator-(matrix_offset const & offset) const noexcept
    ```

We noted that Group1 can be automatically deduced from `inherited_iterator_base`.

That means `seqan3::detail::two_way_matrix_iterator` should really be defined like

```c++
template <typename value_t, ...>
class two_dimensional_matrix::<value_t, ...>::iterator_type : 
    seqan3::detail::inherited_iterator_base<std::vector<value_t>, // makes this iterator random_access
    seqan3::detail::two_dimensional_matrix_iterator_base<std::vector<value_t> // supports random_access with matrix_offset by inferring all other operations from operator+=(matrix_offset)
{
// needed to define Group3 of operations
constexpr iterator_type & operator+=(matrix_offset const & offset) noexcept;

matrix_coordinate coordinate() const noexcept;
};
```

A `two_dimensional_matrix_iterator` concept would look like this:

```c++
template <iterator_type>
concept two_dimensional_matrix_iterator = std::random_access_iterator<iterator_type> && requires()
{
// Group (2) operations
    constexpr iterator_type & operator+=(matrix_offset const & offset) noexcept;
    matrix_coordinate coordinate() const noexcept;

// and Group (3) operations
    constexpr iterator_type operator+(matrix_offset const & offset) const noexcept
    constexpr friend iterator_type operator+(matrix_offset const & offset, derived_t const iter)
    constexpr iterator_type & operator-=(matrix_offset const & offset) noexcept
    constexpr iterator_type operator-(matrix_offset const & offset) const noexcept
};
```

The current matrix concept can then be changed to:

```c++
template <typename matrix_t>
concept two_dimensional_matrix =
    std::ranges::range<matrix_t> &&
    seqan3::detail::two_dimensional_matrix_iterator<std::ranges::iterator_t<matrix_t>>
    && requires(matrix_t m)
{
    {m.cols()} -> std::integral;
    {m.rows()} -> std::integral;
    {m.at(matrix_coordinate{})} -> std::same_as<std::ranges::range_reference_t<matrix_t>>;
};
```

### Acceptance Criteria

- [ ] The changes are done like described in this ticket.
- [ ] `two_dimensional_matrix_iterator_base` doesn't assume that the derived class has a `host_iter` member.

### Tasks

 

- [ ] `seqan3::detail::two_way_matrix_iterator` is implemented like mentioned above
- [ ] `two_dimensional_matrix_iterator_base` only has the members functions defined by Group 3
- [ ] Implement a `two_dimensional_matrix_iterator` concept
- [ ] Edit algorithm unifies it's matrix implementation and uses  `two_dimensional_matrix_iterator` design for `score_matrices` and `trace_matrices`.

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
