### ISSUE TITLE
search configuration hit part 1

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#65]
### Description 

Following the design decissions at seqan/seqan3#1580 restructure the configuration mode.
Here are the design decisions: https://docs.google.com/document/d/1Lv7zxtDUgAeHGcnJ6IWFzgIbJ6rFJlUt2linAOjlIBg/edit#heading=h.mfoteev73s87

See following code example:
```cpp
//usage: 

seqan3::search_cfg::hit_all_best

// construction - no construction since it is a tag

seqan3::search_cfg::hit_all_best
// this is an instance of seqan3::search_cfg::hit_all_best_tag     

//access by seqan::get:

auto && var = seqan3::get<seqan3::search_cfg::hit_all_best_tag>(config);

//check if present:

constexpr bool has_hit_all_best_tag = config_t::template exists<seqan3::search_cfg::detail::hit_all_best_tag>();
```
The other configs are analoge, except for strata which captures an argument:
```cpp
// construction

seqan3::search_cfg::hit_strata hit_strata(5)    

// later access and set

hit_strata.stratum = 5;    

// access by seqan::get:

auto && hit_strata = seqan3::get<seqan3::search_cfg::hit_strata>(config);
hit_strata.stratum = 5;

// check if present:

constexpr bool has_hit_strata = config_t::template exists<seqan3::search_cfg::detail::hit_strata>();
```

### Acceptance Criteria

- [ ] The `seqan3::search_cfg::mode{seqan3::search_cfg::all}` is a top level configuration element `seqan3::search_cfg::hit_all` 
- [ ]  The `seqan3::search_cfg::mode{seqan3::search_cfg::all_best}` is a top level configuration element `seqan3::search_cfg::hit_all_best` 
- [ ]  The `seqan3::search_cfg::mode{seqan3::search_cfg::best}` is a top level configuration element `seqan3::search_cfg::hit_best` 
- [ ]  The `seqan3::search_cfg::mode{seqan3::search_cfg::strate{3}}` is a top level configuration element `seqan3::search_cfg::hit_strata{3}` 
- [ ] Combining any of these with each other will cause a static assertion

### Tasks

 

- [ ] Add seqan3::search_cfg::hit_all configuration mode with documentation
- [ ] Add seqan3::search_cfg::hit_all_best configuration mode with documentation
- [ ] Add seqan3::search_cfg::hit_best configuration mode with documentation
- [ ] Add seqan3::search_cfg::hit_strata configuration mode with documentation
- [ ] Write summary documentation on the `seqan3/search/configuration/all.hpp` module page.

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
