### ISSUE TITLE
search configuration max error

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#66]
### Description 

Following the design decissions at seqan/seqan3#1580 restructure the configuration mode.
Here the design decisions: https://docs.google.com/document/d/1Lv7zxtDUgAeHGcnJ6IWFzgIbJ6rFJlUt2linAOjlIBg/edit#heading=h.964nxukysrmc

The new format should be to use each configuration element separately.

```cpp
auto configuration = seqan3::search_cfg::max_error_total{seqan3::search_cfg::error_rate{0.1}} |
                     seqan3::search_cfg::max_error_substitution{seqan3::search_cfg::error_count{5}}  |
                     seqan3::search_cfg::max_error_deletion{seqan3::search_cfg::error_rate{0.02}};
```
More examples for usage.
```cpp
seqan3::search_cfg::max_error_total total{seqan3::search_cfg::error_rate{0.2}};
seqan3::search_cfg::max_error_total total{seqan3::search_cfg::error_count{5}};    

// later access and set

total.error = seqan3::search_cfg::error_rate{0.2};    
total.error = seqan3::search_cfg::error_count{2};    

// access by seqan::get:

auto && total = seqan3::get<seqan3::search_cfg::max_error_total>(config);
total.error = seqan3::search_cfg::error_rate{0.2};
total.error = seqan3::search_cfg::error_count{2};

// check if present:

constexpr bool has_max_error_total = config_t::template exists<seqan3::search_cfg::max_error_total>();
```

Note: The internal error member can be implemented as a `std::variant<error_rate, error_count>`. 

### Acceptance Criteria

- [ ] Setting the upper bound of allowed errors via `seqan3::search_cfg::max_error_total{error}`. Error is either a seqan3::search_cfg::error_rate or a seqan3::search_cfg::error_count{} .
- [ ] Setting the upper bound of allowed substitutions via `seqan3::search_cfg::max_error_substitution{error}`. Error is either a seqan3::search_cfg::error_rate or a seqan3::search_cfg::error_count{} .
- [ ] Setting the upper bound of allowed insertions via `seqan3::search_cfg::max_error_insertion{error}`. Error is either a seqan3::search_cfg::error_rate or a seqan3::search_cfg::error_count.
- [ ] Setting the upper bound of allowed insertions via `seqan3::search_cfg::max_error_deletion{error}`. Error is either a seqan3::search_cfg::error_rate or a seqan3::search_cfg::error_count.
- [ ] All elements can only occur once in a configuration composition.
- [ ] The configuration elements can be combined with each other
- [ ]  The error_rate can only take values between 0 and 1, otherwise throws an error
- [ ] If no error configuration is given the total error is 0.
- [ ] If no max_error_total is given but any of the other error configurations the total error is set to `error_rate{1.0}` 
- [ ]  The maximal number of errors in the search configuration corresponds to `min(max_error_total, sum(max_error_substitution, max_error_insertion, max_error_deletion))`
- [ ] There is no max_error group selector since these configs are combinable.

### Tasks

 

- [x] Add seqan3::search_cfg::error_count strong type taking only positive values
- [x] Add seqan3::search_cfg::error_rate strong type taking only values between 0 and 1
- [x] Add seqan3::search_cfg::max_error_total configuration element with documentation
- [x] Add seqan3::search_cfg::max_error_insertion configuration element with documentation
- [x] Add seqan3::search_cfg::max_error_deletion configuration element with documentation
- [x] Add seqan3::search_cfg::max_error_substitution configuration element with documentation
- [x] Adapt the search configuration to use the new configuration elements
- [x] Update the tutorial page and snippets
- [x] Update the benchmarks if any
- [x] Update the api tests
- [x] Write summary documentation on the `seqan3/search/configuration/all.hpp` module page.

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
