### ISSUE TITLE
search configuration output

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#67]
### Description 

Following the design decissions at seqan/seqan3#1580 restructure the configuration mode.
Here are the design decisions: https://docs.google.com/document/d/1Lv7zxtDUgAeHGcnJ6IWFzgIbJ6rFJlUt2linAOjlIBg/edit#heading=h.ggewfny5ettu

See reference implementation: 
```cpp
// usage: 
seqan3::search_cfg::output_text_position

// construction - no construction since it is a tag

seqan3::search_cfg::output_text_position;
// this is an instance of seqan3::search_cfg::output_text_position_tag     

// access by seqan::get:

auto && var = seqan3::get<seqan3::search_cfg::output_text_position_tag>(config);

 //  check if present:

constexpr bool with_text_position = config_t::template exists<seqan3::search_cfg::output_text_position_tag>();
```
The other options are analoge.

### Acceptance Criteria

- [ ] Select the text position via the configuration element `seqan3::search_cfg::output_text_position`
- [ ] Select the cursor via the configuration element `seqan3::search_cfg::output_index_cursor`
- [ ] Select the query id via the configuration element `seqan3::search_cfg::output_query_id`
- [ ] Select the reference id via the configuration element `seqan3::search_cfg::output_reference_id`
- [ ] Select the reference slice via the configuration element `seqan3::search_cfg::output_reference_slice`
- [ ] If no ouput option is specified the algorithm outputs the text postion, query_id, reference_id and reference_slice.
- [ ] All configurations can be combined with each other.
- [ ] Each configuration element can only occur once in a configuration composition
- [ ] If one output configuration element is specified, only this one will be present in the search result class, e.g. if the user selects `config | seqan3::search_cfg::output_query_id`, only the query id will be outputted. The algorithm only needs to do the work that is necessary to the determine the requested output.
- [ ] There is no group selector for output configurations.

### Tasks

 

- [ ] Add seqan3::search_cfg::output_query_id configuration mode with documentation
- [ ] Add seqan3::search_cfg::output_reference_id configuration mode with documentation
- [ ] Add seqan3::search_cfg::output_reference_slice configuration mode with documentation
- [ ] Add seqan3::search_cfg::output_text_position configuration mode with documentation
- [ ] Add seqan3::search_cfg::output_index_cursor configuration mode with documentation
- [ ] replace the current seqan3::search_cfg::output option with the new ones
- [ ] Update tutorial/snippets
- [ ] Update benchmarks if  any
- [ ] Update tests
- [ ] Write summary documentation on the `seqan3/search/configuration/all.hpp` module page.

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
