### ISSUE TITLE
search configuration parallel

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#68]
### Description 

Adapt `seqan3::search_cfg::parlallel` to reflect design decisions as discussed in https://github.com/seqan/product_backlog/issues/131.

### Acceptance Criteria

- [ ] Make configuration element hold directly the member in a variable called `thread_count`.
- [ ] If the option is default constructed and no thread count is set by the user, then during the configuration an exception shall be thrown that the option is not in a valid state. 

### Tasks

 

- [ ] Adapt the interface to store the variable inside of a variable called `thread_count`
- [ ] Adapt the tutorials/snippets if any
- [ ] Add documentation entry on `seqan3/search/configuration/all.hpp`
- [ ] Make the thread_count variable an std::optional and set it to `std::nullopt` when default constructed.

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
