### ISSUE TITLE
alignment improvement refactorisation - new affine gap policy and score matrix

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#70]
### Acceptance:

- [x] The alignment performance of the new alignment implementation will not be affected by the change.

### Tasks:

- [x] Join the current affine gap pollicy and the init gap policy into a single policy
- [x] Make the policy a regular base class and not a crtp base
- [x] Add a more simplified score matrix.
