### ISSUE TITLE
alignment improvement refactorisation - free end gap initialisation

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#71]
### Description

The new alignment backend should work with free end gaps such that the optimised alignment can be computed with free end gaps configuration.

### Acceptance:

- [ ] The alignment performance of the new alignment implementation will not be affected by the change.
- [ ] The new alignment backend is enabled with the new implementation.
- [ ] All tests run through

### Tasks:

- [x] Add two bool parameters in the class in `seqan3/alignment/pairwise/detail/policy_affine_gap_recursion.hpp` to handle the initialisation state of the first row/column of the alignment
- [x] In the constructor of this class read out the state to initilaise these members from the given configuration.
- [x] Adapt the methods: initialise_origin_cell, initialise_first_column_cell, initialise_first_row_cell to handle the initalisation depending on the set state of the two members.
- [x]  Add two bool parameters in the class `seqan3/alignment/pairwise/detail/policy_optimum_tracker.hpp` to handle the free end gaps in the last row/column
- [x] n the constructor of this class read out the state to initilaise these members from the given configuration object (see above).
- [x] Adapt the currently unused methods: track_last_row_cell and track_last_column_cell to track depending on the set state of these two members.
- [x] In the alignment configurator: `seqan3/alignment/pairwise/alignment_configurator.hpp` remove line 501 and check if all tests in the subdirectory `alignment/pairwise` of the unit tests run through

To check if the aligned ends have been set use the traits type defined in the top of the policy classes:
```cpp
if constexpr (traits_type::is_aligned_ends)
{
   auto align_ends_config = get<align_cfg::aligned_ends>(config);
   is_first_column_free = align_ends_config[0];
   is_first_column_free = align_ends_config[2];
}
```

Similar for the optimum tracker policy:

```cpp
if constexpr (traits_type::is_aligned_ends)
{
   auto align_ends_config = get<align_cfg::aligned_ends>(config);
   is_last_row_free = align_ends_config[1];
   is_last_column_free = align_ends_config[3];
}
```

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] API documentation updated
- [ ] Microbenchmark shows improved performance compared to previous version.
- [ ] Tutorial/teaching material updated
