### ISSUE TITLE
Concurrent bulk_contains for interleaved_bloom_filter

### ISSUE THREAD

**Issue by eseiler** [seqan/product_backlog#78]
### Description 

Currently, concurrent read access via `bulk_contains` is not possible, because the `seqan3::interleaved_bloom_filter` owns the result of `bulk_contains`.

One possible way to achieve this, is to add an overload to `bulk_contains` that takes a `binning_bitvector` as input and writes the result into it.
Then each thread can own a `binning_bitvector`.

See
https://github.com/eseiler/seqan3/commit/c7946f275ed9e1e3fdf15eb233ef20f4a4d1b837

### Acceptance Criteria

- [ ] Concurrent `bulk_contains` is possible.

### Tasks

 

- [ ] Add another overload of `bulk_contains` that accepts a `binning_bitvector` as input and write the results in the given vector.

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by marehr** [comment]
2020-06-15 Core-Meeting:

* `void ibf::bulk_contains(size_t const value, binning_bitvector & result) const noexcept` might be useful.
* Documentation issues:
  * Race-Conditions when `bulk_contains` is called concurrently
  * A second `bulk_contains` will override a previous search. IMPORTANT!

Proposal:
* Extend semantics that multiple instances of `ibf` hold one cached result for a `binning_bitvector`.
  * declare that `binning_bitvector` as static
  * Try out if `thread_local` solves the problem for concurrent accesses.

Resolution:

Documentation must be fixed.

**Comment by eseiler** [comment]
Regarding `thread_local`:

Before / on master:
```console
bulk_contains_benchmark<seqan3::interleaved_bloom_filter<seqan3::data_layout::uncompressed>>/64/512/2/1000         5984 ns         5984 ns       110180 hashes/sec=167.109M/s
bulk_contains_benchmark<seqan3::interleaved_bloom_filter<seqan3::data_layout::uncompressed>>/64/16384/2/1000       6413 ns         6413 ns       109026 hashes/sec=155.924M/s
bulk_contains_benchmark<seqan3::interleaved_bloom_filter<seqan3::data_layout::uncompressed>>/8192/4/2/1000       255268 ns       255265 ns         2734 hashes/sec=3.9175M/s
bulk_contains_benchmark<seqan3::interleaved_bloom_filter<seqan3::data_layout::uncompressed>>/8192/128/2/1000     255218 ns       255217 ns         2746 hashes/sec=3.91824M/s
bulk_contains_benchmark<seqan3::interleaved_bloom_filter<seqan3::data_layout::compressed>>/64/512/2/1000          15367 ns        15367 ns        45566 hashes/sec=65.0747M/s
bulk_contains_benchmark<seqan3::interleaved_bloom_filter<seqan3::data_layout::compressed>>/64/16384/2/1000        15365 ns        15365 ns        45598 hashes/sec=65.0839M/s
bulk_contains_benchmark<seqan3::interleaved_bloom_filter<seqan3::data_layout::compressed>>/8192/4/2/1000        1252293 ns      1252296 ns          557 hashes/sec=798.533k/s
bulk_contains_benchmark<seqan3::interleaved_bloom_filter<seqan3::data_layout::compressed>>/8192/128/2/1000      1256883 ns      1256879 ns          557 hashes/sec=795.622k/s
````

After / in PR:
```console
bulk_contains_benchmark<seqan3::interleaved_bloom_filter<seqan3::data_layout::uncompressed>>/64/512/2/1000         7783 ns         7783 ns        89319 hashes/sec=128.484M/s
bulk_contains_benchmark<seqan3::interleaved_bloom_filter<seqan3::data_layout::uncompressed>>/64/16384/2/1000       7881 ns         7881 ns        85207 hashes/sec=126.893M/s
bulk_contains_benchmark<seqan3::interleaved_bloom_filter<seqan3::data_layout::uncompressed>>/8192/4/2/1000       381196 ns       381193 ns         1798 hashes/sec=2.62334M/s
bulk_contains_benchmark<seqan3::interleaved_bloom_filter<seqan3::data_layout::uncompressed>>/8192/128/2/1000     382369 ns       382366 ns         1832 hashes/sec=2.61529M/s
bulk_contains_benchmark<seqan3::interleaved_bloom_filter<seqan3::data_layout::compressed>>/64/512/2/1000          17210 ns        17210 ns        41891 hashes/sec=58.107M/s
bulk_contains_benchmark<seqan3::interleaved_bloom_filter<seqan3::data_layout::compressed>>/64/16384/2/1000        16804 ns        16804 ns        41865 hashes/sec=59.5085M/s
bulk_contains_benchmark<seqan3::interleaved_bloom_filter<seqan3::data_layout::compressed>>/8192/4/2/1000        1437649 ns      1437643 ns          489 hashes/sec=695.583k/s
bulk_contains_benchmark<seqan3::interleaved_bloom_filter<seqan3::data_layout::compressed>>/8192/128/2/1000      1439678 ns      1439669 ns          485 hashes/sec=694.604k/s
```

Unfortunately there is quite some regression (both benchmark are not multi threaded).

**Comment by smehringer** [comment]
> #### The cost of using thread-local variable
>   Usually the cost of using thread-local variables is very small and a programmer may not even  notice it. However, if the thread-local variable is accessed very frequently, the cost may become an issue.

If I understand the post correctly it is because the compiler may not be able to inline a function that uses a thread local variables which then forces the compiler to look up the thread_local variable everytime.
As a solution they propose:
> Reducing the cost of function “__tls_get_addr” is actually not difficult. You can use the key word “__forceinline” to give hint to the compiler to inline the function “get_value”. 

or if this is not possible

> You may ask if the function “get_value” cannot be inlined for whatever reason, is it possible to reduce the cost of accessing a thread-local variable? The answer is “yes”. Since in this example, the thread-local variable is read-only, you can assign the thread-local variable to a local variable outside the “for” loop, and then use the local variable inside the loop, as shown below.

I don't know if it is applicable in your PR?
here is the blog post: https://software.intel.com/content/www/us/en/develop/blogs/the-hidden-performance-cost-of-accessing-thread-local-variables.html

Also note that `thread_local` has an extra performance penalty compared to `__thread`
if ("it" is the variable) 
> It is not function-local, and,
     1.   It is extern (the example shown above), or
     2.  The type has a non-trivial destructor (which is not allowed for __thread variables), or
     3.  The type variable is initialized by a non-constant-expression (which is also not allowed for __thread variables).

says stack overflow: https://stackoverflow.com/questions/13106049/what-is-the-performance-penalty-of-c11-thread-local-variables-in-gcc-4-8

Not sure if that's the case for us

**Comment by eseiler** [comment]
It's dynamically initialised, so we can't use `__thread`.
I may try the intel block post.

But most examples are with PODs, but we have something that allocates memory.

**Comment by marehr** [comment]
2020-06-17 Core-Meeting

* Run-time penalty for using thread local.
* New approach: use agent/proxy pattern (like an iterator)

![aww-board](https://user-images.githubusercontent.com/103778/84892640-39d80080-b09e-11ea-9f8e-d6257bd6288e.png)

![](https://www.sihui.io/wp-content/uploads/2018/01/img_5a4dc32163a00.png)

(Source: https://www.sihui.io/design-pattern-proxy/)

**Comment by rrahn** [comment]
### Resolution 24.06.2020

* We use for the IBF a access member function `membership_agent()` which returns a `membership_agent_type` wrapping a binning vetor.
* technical binning directory has a `counting_agent()`, which returns a `counting_agent_type` wrapping a counting vector.
