### ISSUE TITLE
search configuration hit configuration part 2

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#79]
### Description 

Following the design decissions at seqan/seqan3#1580 restructure the configuration mode.
Here are the design decisions: https://docs.google.com/document/d/1Lv7zxtDUgAeHGcnJ6IWFzgIbJ6rFJlUt2linAOjlIBg/edit#heading=h.mfoteev73s87

We need a dynamic selector for the `seqan3::seach_cfg::hit` configuration elements. This dynamic configuration element allows to set the hit configuration at runtime.

See following code example:
```cpp
// default constructor

seqan3::align_cfg::hit{};

// NOTE: This puts “hit” in an unassigned state. The algorithm can see that it is unassigned and will throw if the user did not provide a “hit”.

// constructor takes one method
seqan3::search_cfg::hit hit{seqan3::search_cfg::hit_all_best};

// NOTE: This puts “hit” in an unassigned state. The algorithm can see that it is unassigned and will throw if the user did not provide a “hit”.

// later access and set

hit = seqan3::search_cfg::hit_all_best;    
hit = seqan3::search_cfg::hit_single_best;    
hit = seqan3::search_cfg::hit_all;    
hit = seqan3::search_cfg::hit_strata{5};    

// access by seqan::get:

auto && hit = seqan3::get<seqan3::search_cfg::hit>(config);
hit = seqan3::search_cfg::hit_all_best;    
hit = seqan3::search_cfg::hit_single_best;    
hit = seqan3::search_cfg::hit_all;    
hit = seqan3::search_cfg::hit_strata{5};    

// check if present:

constexpr bool has_hit = config_t::template exists<seqan3::search_cfg::hit>();
```

### Acceptance Criteria

- [x] There exists a dynamic group selector `seqan3::search_cfg::hit{}`, that can be assigned with one of the above mentioned configuration element.
- [x] Within a configuration composition only one configuration element can be present including the group selector `seqan3::search_cfg::hit` 
- [x] If the group selector is default initialised no default is set. Only the algorithm later decides how to handle default initalised selectors. In this case the uni and bidirectional search use the `hit_best` option.

### Tasks

 

- [ ] Add seqan3::search_cfg::hit configuration mode with documentation
- [ ] Write summary documentation on the `seqan3/search/configuration/all.hpp` module page.
- [ ] Adapt configuration of the search algorithm to  select the proper default version if not set before.

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by rrahn** [comment]
I already have a reference implementation here:  #1446
