### ISSUE TITLE
[Alignment] Missing coverage in edit distance unbanded

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#82]
### Description 

In line 996 of https://github.com/seqan/seqan3/blob/74fb2130d3cd7ccec39f21b1f15616537b899971/include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp#L996

the branch is never executed within the tests. To get a full coverage we need to have a test that goes through this line. From looking swiftly over the code it is possible that the design might be updated when the on_result feature is implemented. @marehr should be included for the discussion to understand the design decision behind this.

### Acceptance Criteria

- [ ] code coverage for edit_distance_unbanded is 100% 

### Tasks

 

- [ ] Add test to the edit distance algorithm tests that enters this line or adapt the code if the internal design should be changed after discussing it with @marehr.

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
