### ISSUE TITLE
Minimiser View works with reverse k-mers

### ISSUE THREAD

**Issue by MitraDarja** [seqan/product_backlog#84]
### Description 

I want a minimiser_view, which accept a second range, so that the minimiser is the minimal value in a window between two ranges. I also want a minimiser_hash_view, which considers the reverese complement when calculation.  

### Acceptance Criteria

- [x] minimiser_view gets a second range, which is defaulted to empty_type
- [x] reverese complement to minimiser_hash_view is default, not using reverse_complement has to be specified by an variable (like reverese = false)

### Tasks

- [x] Add second range to minimiser_view
- [x] Add reverese complement to minimiser_hash_view as default
- [x] write a tutorial showing a use case for the minimizer view 

### Definition of Done

- [x] Implementation and design approved
- [x] Unit tests pass
- [x] Test coverage = 100%
- [x] API documentation added
- [x] Tutorial/teaching material added
- [x] Test suite compiles in less than 30 seconds (on travis)
