### ISSUE TITLE
Benchmark Minimiser_hash

### ISSUE THREAD

**Issue by MitraDarja** [seqan/product_backlog#85]
### Description 

I want a benchmark for minimiser_hash, which compares the function to a naive algorithm (without "rolling hash") and compares it to a seqan2 approach.

### Acceptance Criteria

- [x] Add seqan2 approach
- [x] Add naive approach

### Tasks

- [x] Add a benchmark comparing to seqan2
- [x] Add a benchmark comparing to naive approach

### Definition of Done

- [x] Implementation and design approved
- [x] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop (has to be checked when minimiser reverse is merged)
