### ISSUE TITLE
cxx20: return-type-requirement is not a type-constraint 

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#88]
### Description 

The following expression

```c++
template <typename t>
concept semialphabet = requires (t v)
{
    { seqan3::to_rank(v) } -> seqan3::alphabet_rank_t<t>;
}
```

is invalid starting with C++20.

In C++20 you would use the following expression :

```c++
template <typename t>
concept semialphabet = requires (t v)
{
    { seqan3::to_rank(v) } -> std::convertible_to<seqan3::alphabet_rank_t<t>>;
};
```

(The return type needs a concept requirement)

The problem is that gcc 7 and 8 does not support the C++20 syntax.

A compromise that works for every compiler version is

```c++
template <typename t>
concept semialphabet = requires (t v)
{
    requires std::convertible_to<delctype(seqan3::to_rank(v)), seqan3::alphabet_rank_t<t>>;
};
```

### Acceptance Criteria

- [ ] Replaced most of these occurrences by the compromise solution

### Tasks

 

- [ ] task 1
- [ ] task 2
- [ ] task 3

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
