### ISSUE TITLE
Remove prefixes / suffices in test suites that are not necessary anymore.

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#90]
### Description 

@simonsasse asked me why we have a underscore in

```c++
TEST(range_and_iterator, innermost_value_type_) // ...
```

I wanted to give him the rational that we have a name clash, but then it came to me that we actually don't have any name clashes any more thanks to  https://github.com/seqan/product_backlog/issues/89.

This means we can remove the leading/ trailing underscores `_` or `global_` constructs from our test cases which previously avoided ambiguous names.

### Acceptance Criteria

- [ ] No test names has a trailing underscore anymore.

### Tasks

 

- [ ] Remove  leading/ trailing underscores `_`, or other common prefixes like global_

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by rrahn** [comment]
fixed by seqan/seqan3#1833
