### ISSUE TITLE
Namespaces ranges::view, ranges::action and ranges::v3 are deprecated

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#91]
### Description 

Namespaces ranges::view, ranges::action and ranges::v3 are deprecated.

See release note:

> Rename the ranges::view namespace to ranges::views and ranges::action to
ranges::actions (with deprecated namespace aliases for migration).
>
> https://github.com/ericniebler/range-v3/releases/tag/0.9.0

We have some occurrences of them:

```c++
            auto seq = sequence | ranges::view::chunk(60);
```

https://github.com/seqan/seqan3/blob/16f1e46bfc591f6da1713180da5c9af8bcedf2ed/include/seqan3/io/sequence_file/format_genbank.hpp#L233

```c++
    auto v3 = vec | adaptor | ranges::view::unique;
```

https://github.com/seqan/seqan3/blob/16f1e46bfc591f6da1713180da5c9af8bcedf2ed/test/unit/range/views/view_take_line_test.cpp#L36

I haven't found any occurrences of `ranges::action` and `ranges::v3`, so these steps might be already done :)

### Acceptance Criteria

* [ ] Rename: `ranges::view` -> `ranges::views`
* [ ] Rename: `ranges::action` -> `ranges::actions`
* [ ] Rename: `ranges::v3` -> `ranges`

### Tasks

 

- [ ] task 1
- [ ] task 2
- [ ] task 3

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
