### ISSUE TITLE
Make the member functions of the configuration object hidden friends.

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#92]
### Description 

As an algorithm developer one needs to use the internal member functions of the configuration object to access some information. Since these are member functions that take an explicit template argument one needs to qualify the call of the function with the `template` keyword if it is called inside of a template context. This is confusing and often dificult to debug. It would be better to make these interfaces hidden friends of the class to avoid the `template` keyword.

##### Edit (10.06.2020) 
We refine this ticket due to the issues detected during the evaluation of the various possibilities to implement the functions. See seqan/product_backlog#123 which is the outcome of this discussion.

### Acceptance Criteria

- [x] In the code we can call the member function `get_or(alternative_cfg)` which either returns the stored config (the type is deduced from `alternative_cfg`) or the alternative if there is no element stored.
- [ ] All interfaces except the pipe operator and get are documented as private.
 
### Tasks

 

- [x] rename value_or a to `get_or` and determine the type from the passed alternative.
- [x] Update the documentation  
- [ ] Document the remove, get_or and exist member functions as private. 

### Definition of Done

- [x] Implementation and design approved
- [x] Unit tests pass
- [x] Test coverage = 100%
- [x] API documentation added

**Comment by smehringer** [comment]
Resolution:
* `cfg.get_or(alternative)` will be a member function (hidden from user) that checks whether there is a config element in `cfg` that has the same type as an alternative.
*  `remove`, `exists/has_element` will become hidden friends (hidden from user)
* If `exists/has_element` will become public it should become a unary type trait or inline bool constant instead of a static member function

**Comment by rrahn** [comment]
Ok after the current evaluation it seems it is not possible to the use a variable template or unary transformation trait for the `exists` since those entities cannot be overloaded based on different type specialisation like functions.

```cpp
template <typename t>
struct func;

template <template <typename...> typename tt>
struct func<tt>;
```
This and many other trials does not work.

Second we can get rid of ADL totally:

https://godbolt.org/z/Sw_rrM

**Comment by rrahn** [comment]
### Possibilities:

* we qualify everything and no named hidden friends (no operators)?
* all free functions are implemented as function objects or if looking for other namespaces is necessary implemented as CPOs
* For operators we have the same problem, but it is very unlikely since it is a very standard behavior of the language.

* in general, due to ADL calling free functions unqualified can always produce very unexpected results. So calling free functions inside of the seqan3 namespace should be called qualified.

### Resolution:
* All public member free functions are converted to either a CPO if ADL is required or a function object together with a inline constexpr variable for this function object.
* All detail free functions are implemented as function objects. An inline constexpr variable is not needed.

Problem: https://godbolt.org/z/MXK-En

Solution: https://godbolt.org/z/LyacmH

**Comment by rrahn** [comment]
resolved by seqan/seqan3#1893
