### ISSUE TITLE
Expand Iterator test template to test contiguous iterators.

### ISSUE THREAD

**Issue by smehringer** [seqan/product_backlog#94]
### Description 

The iterator test template does currently not test the functionality of a contiguous iterator and should be expanded thereof.

### Acceptance Criteria

- [ ] Specifying a contiguous iterator when the iterator does not model contiguous will cause the test to fail

### Tasks

- [ ] Add the concept check
- [ ] Expand the static_assert message in line that
- [ ] Add tests that check the following (http://eel.is/c++draft/iterator.concept.contiguous)
  ```
  Let a and b be dereferenceable iterators and c be a non-dereferenceable iterator 
  of type I such that b is reachable from a and c is reachable from b, and let D be iter_­difference_­t<I>.
  The type I models contiguous_­iterator only if

    (2.1) to_­address(a) == addressof(*a),
    (2.2) to_­address(b) == to_­address(a) + D(b - a), and
    (2.3) to_­address(c) == to_­address(a) + D(c - a). 
  ```
### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added
