### ISSUE TITLE
ISMB Bio++ tutorial

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#95]
### Appointments:

* [x] 04.06. - Zoom demo [2pm]
* [x] 15.06. - Sent names of presenters
* [x] 26.06. - Submit materials (slides, etc.)
* [x] 05.07. - SetUp Guide
* [x] 09.07. - Registration Deadline
* [x] 12.07. - Presentation [3pm - 7pm]

### Use-Full links:
* Presentation at: https://seqan.github.io/learning-resources/doc/biocpp/presentation/#/
* Source code: https://github.com/seqan/learning-resources

### TODOS:

Orga:
- [x] how and when to register (https://www.iscb.org/ismb2020-registration) [Thursday, July 9, 5:00 pm Eastern Time Zone (EDT)]
- [x] what to present (04.06. 12pm?) [all]
- [x] who presents? [@rrahn, @smehringer, @marehr, @eseiler (@joergi-w, @Irallia)?]
- [ ] check that the de.NBI/Elixir logo is displayed on the ISMB site []
- [x] Please take a moment to review the details we have listed for your tutorial and send me any updates or changes: https://www.iscb.org/ismb2020/4399#tut5. []
     smehringer: There is still the mention of " or, VirtualBox if the attendee wishes to use the provided virtual image running Ubuntu." which we will not provided anymore right? Maybe instead we should mention that they should have a github account. 
- [x] registration at de.NBI (write daniel wibberg a mail with the registration template) [@marehr]
- [ ] twitter, email announcement [@rrahn]

> All,
> The ISMB Tutorial sessions are rapidly approaching!
> If you have any installation instructions, pre-readings, folders or content to share with the participants who have registered for your ISMB Tutorial, please send through to Steven Leard at steven(ät)iscb.org or tutorials(ät)iscb.org
>  
> We will make sure this content gets sent out to your participants and posted online accordingly.
> DUE: July 5, 2020 to give a week notice (July 2 for Robert Majovski)
>  
> Kind regards,
> Michelle

Feedback:
* [x] Add slide numbers - there is a typo (c++ instead of C++) but I can't tell you in which slide it was. And trainees may want to refer to a specific slide when talking to you.
* [x] Most of your content are not on the slides (hands-on). It's difficult to evaluate the timing based only on the slides. I guessing you will handle it and you will be just fine.
* [x] Svenja Mehringer, Free University Berlin, Algorithmic Bioinformatics, Germany not is slides, but in the tutorial description. Is that correct?

Presentation:
- [ ] prepare online tutorial
- [ ] prepare slides
  - [x] update slides from Malta (schedule etc..)
  - [x] Remove flash drives mention from set up
  - [ ] maybe add benchmark comparison to python
  - [x] add survey to slides
- [x] prepare online editor gitpod
- [ ] ~prepare VMs and where to host them~
- [ ] how to react on questions of the learners (googledoc or etherpad, zoom chat?, gitter?)
- [ ] breakout rooms?
- [ ] survey
- [ ] de.NBI and elixir logo

### Zoom

- How to use break-out rooms?
- How to multiscreen-share? (https://support.zoom.us/hc/en-us/articles/115000424286-Sharing-multiple-screens-simultaneously)
- How to do remote control? (https://support.zoom.us/hc/en-us/articles/201362673-Requesting-or-giving-remote-control)
- How to become a Host, co-Host or Panellist? (requires desktop app)

At least version 5.

### Material from ISMB

https://docs.google.com/presentation/d/1Atd-Vu-AGSQVuDdUQdWh7tOKBEeRJgm1KvBEobrT9xE/edit#slide=id.p

[Zoom Meeting Cheatsheet.pdf](https://github.com/seqan/product_backlog/files/4730168/Zoom.Meeting.Cheatsheet.pdf)

**Comment by smehringer** [comment]
@rrahn Can you append a link/file with the tutorial material from the last conference?
