### ISSUE TITLE
Adapt the mode configuration of the alignment algorithm

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#97]
### Description 

Following the discussion on seqan/seqan3#1580 adapt the output configuration of the alignment algorithm.

##### construction

```cpp
// default constructor

// constructor takes one method
namespace seqan3::detail
{
struct method_global_tag : public pipeable_config_element<method_global_tag, empty_type>
{
    static constexpr detail::align_config_id id{detail::align_config_id::method};
};

namespace seqan3::align_cfg
{
    inline constexpr seqan3::detail::method_global_tag method_global{};
}
} // namespace seqan3::align_cfg
```
##### query if configuration was piped

```cpp
config_t::template exists<seqan3::detail::method_global_tag>()
```

#### seqan3::align_cfg::method_local

```cpp
// default constructor

// constructor takes one method
namespace seqan3::detail
{
struct method_local_tag : public pipeable_config_element<method_local_tag, empty_type>
{
    static constexpr detail::align_config_id id{detail::align_config_id::method};
};

namespace seqan3::align_cfg
{
    inline constexpr seqan3::detail::method_local_tag method_local{};
}
} // namespace seqan3::align_cfg
```

##### query if configuration was piped

```cpp
config_t::template exists<seqan3::detail::method_local_tag>()
```

### Acceptance Criteria

- [x] The alignment algorithms configuration is ported to handle the new method variant
- [x] The old mode variant is deleted.
- [x] The above requested interfaces work

### Tasks

 

- [x] Add a new header in configuration and add the implementation for global method.
- [x] Add a new align_config_id for method in `seqan3/alignment/configuration/detail.hpp`
- [x] Adapt the file `seqan3/alignment/pairwise/alignment_configurator.hpp` to handle the new method configuration.
- [x] Adapt the configuration traits class to read the new global alignment method tag `seqan3/alignment/pairwise/detail/type_traits.hpp`
- [x] Run and adapt all test cases in the alignment subdirectory of the unit tests.
- [x] Repeat the same steps for adding local alignment method.
- [x] After porting to the new configuration remove the old mode configuration header and all existing references
- [x] Update the API documentation and the tutorials that reference to the methods.

### Definition of Done

- [x] Implementation and design approved
- [x] Unit tests pass
- [x] Test coverage = 100%
- [x] API documentation updated
- [x] Tutorial/teaching material updated
- [x] Changelog entry added
