### ISSUE TITLE
Update alignment configuration band

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#98]
### Description 

Following the discussion on seqan/seqan3#1580 adapt the band configuration for alignment algorithms.

```cpp
seqan3::align_cfg::band_fixed_size

// If this config was not set it calculates with a band width of `∞`

// construction

seqan3::align_cfg::band_fixed_size band{seqan3::align_cfg::lower_diagonal{-4}, seqan3::align_cfg::upper_diagonal{10}}; 

// later access and set

band.lower_diagonal = seqan3::align_cfg::lower_diagonal{-4};
band.upper_diagonal = seqan3::align_cfg::upper_diagonal{10};

// or by seqan::get

auto && band = seqan3::get<seqan3::align_cfg::band_fixed_size>(config);
band.lower_diagonal = seqan3::align_cfg::lower_diagonal{-4};
band.upper_diagonal = seqan3::align_cfg::upper_diagonal{10};

// query if configuration was piped

config_t::template exists<seqan3::align_cfg::band_fixed_size>() 

```

### Acceptance Criteria

- [x] code snippet as described above work
- [x] default constructed band is infinity
- [x] The constructor with parameters throws if the upper diagonal is smaller than the lower diagonal.

### Tasks

 

- [x] add implementation
- [x] add tests
- [x] add documentation

### Definition of Done

- [x] Implementation and design approved
- [x] Unit tests pass
- [x] Test coverage = 100%
- [x] API documentation updated
- [x] Tutorial/teaching material updated
- [x] Changelog entry added
